### ISSUE TITLE
Bug / Question: "braces" -> Keep newline?

### ISSUE THREAD

**Issue by voku** [PHP-CS-Fixer/PHP-CS-Fixer#3863] opened 2018-07-03 21:12 UTC
#### The PHP version you are using (`$ php -v`):
=> 7.1.18-1+ubuntu16.04.1+deb.sury.org+1

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
=> PHP CS Fixer 2.12.1 Long Journey by Fabien Potencier and Dariusz Ruminski (beef6cb)

#### The command you use to run PHP CS Fixer:
=> .../projectX/framework/thirdparty/php-cs-fixer.phar fix --verbose --config=.../projectX/App/scripts/githooks/phpcs.php .../projectX/Framework/modules/Framework/lib/MenuDisplayer.php

#### The configuration file you are using, if any:
```php
[ 
  'braces' => [
     'position_after_anonymous_constructs'         => 'same',
     'position_after_control_structures'           => 'same',
     'position_after_functions_and_oop_constructs' => 'same',
  ]
]
```

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):
 * before running PHP CS Fixer (no changes):
```php
<?php

if (true) {

    // here comes an info

    echo "lall";
    // ...more code

} else {

    if (false) {
        // ...more code
    }

}
```

 * with unexpected changes applied when running PHP CS Fixer:
```php
<?php

if (true) {

    // here comes an info

    echo "lall";
// ...more code
} else {
    if (false) {
        // ...more code
    }
}
```

 * with the changes you expected instead:

-> no changes, because "braces" are already on the same line

```php
<?php

if (true) {

    // here comes an info

    echo "lall";
    // ...more code

} else {

    if (false) {
        // ...more code
    }

}
```

**Comment by SpacePossum** [comment] 2018-07-04 05:12
Hi @voku,

Thanks for the detailed reported, made it very easy to quickly do some checks locally :+1:

The behavior of the `braces` rule here comes from a bit of history, now we've dedicated rules that can be used to remove empty lines. When this was added the `braces` fixer was not changed to stop removing the lines, I think because of BC concerns but maybe together with the fact that the `braces` rules is not the easiest code ;)

I would be in favor of changing the `braces` rule by taking out functionality we provide through other rules, making it a more easy rule and giving more control to the end user.

**Comment by davi5e** [comment] 2019-11-19 15:30
> I would be in favor of changing the `braces` rule by taking out functionality we provide through other rules, making it a more easy rule and giving more control to the end user.

I have a related question to this general assertion over [#4003](https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/4003#issuecomment-555556219).

Non related, is there a way to configure the rule so that I can use the following?
```php
}
else {
```

I just disabled `Braces` for now, but I'd consider using it because it's obviously helps a lot (but I'd need to change nearly every line of code as is).

**Comment by SpacePossum** [comment] 2019-12-18 10:29
Hi,

The CS like:

```
}
else {
```

is not support by the various rules within this project. Main reason is that this style is not part of a standard used by a big community. 
You are right though, a lot of the things the `braces` - rule does should be split into dedicated rules so you would get more configuration options here.

**Comment by davi5e** [comment] 2019-12-18 12:48
Well, if this ever comes to pass, I hope this option is added since there are IDE shortcuts to go to the opening/closing bracket whenever the caret is adjacent to the bracket. It's just easier to click anywhere in an blank the line than to point the mouse just before the `else`...

**Comment by Wirone** [comment] 2023-03-15 23:17
I'm going to close this one as it's stale for a long time, and I believe there are plans for `braces` fixer to be divided into smaller rules. Feel free to check your code example with newest release of Fixer and reopen it if expected behavior is still different than actual result 🙂.

**Closed by Wirone** 2023-03-15 23:17 UTC
