### ISSUE TITLE
Braces - MethodChainingIndentationFixer - priority conflict

### ISSUE THREAD

**Issue by bluedasher13** [PHP-CS-Fixer/PHP-CS-Fixer#4718] opened 2019-12-29 06:28 UTC
For configuration or updating questions please read the README and UPGRADE documentation,
or visit: https://gitter.im/PHP-CS-Fixer

When reporting an issue (bug) please provide the following information:

#### The PHP version you are using (`$ php -v`):
=> 7.3.8

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
=> 2.16

#### The command you use to run PHP CS Fixer:
=> php-cs-fixer fix

#### The configuration file you are using, if any:
```php
return PhpCsFixer\Config::create()
    ->setUsingCache(true)
    ->setRules([
        'braces' => true,
        'method_argument_space' => [
            'on_multiline' => 'ensure_fully_multiline'
        ]
    ]);
```

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):
 * before running PHP CS Fixer (no changes):
```php
<?php
class MyClass
{
public function test(
$a = null,
$b = null
)
{
$form = $this->someFunction(
$param1,
$param2,
['key' => 'value']
);
}
}

```

 * with unexpected changes applied when running PHP CS Fixer:
```php
<?php
class MyClass
{
    public function test(
    $a = null,
    $b = null
) {
        $form = $this->someFunction(
    $param1,
    $param2,
    ['key' => 'value']
);
    }
}

```
 * with the changes you expected instead:
 **I must "disable cache" and run fix "twice" to get this result.**
```php
<?php
class MyClass
{
    public function test(
        $a = null,
        $b = null
    ) {
        $form = $this->someFunction(
            $param1,
            $param2,
            ['key' => 'value']
        );
    }
}

```

It seems that there's a problem.

I **MUST** run _``php-cs-fixer fix``_ **twice** and **MUST**  add the _``--using-cache=no``_ command-line option or the in-script option _``->setUsingCache(false)``_ to **disable cache**, then I cound get the correct indents.

**Comment by taylankasap** [comment] 2020-02-02 22:27
Probably caused by same bug but just wanted to add because it occured with `method_chaining_indentation` instead of `method_argument_space` (and example is more minimal/compact).

```php
<?php

$values
    ->map(function ($value) {
        return $value;
    })
;
```

PHP 7.4.1 (cli)
PHP CS Fixer 2.16.1 Yellow Bird

Command that needs to be run twice:
`./vendor/bin/php-cs-fixer fix php-cs-fixer-test.php --diff --using-cache=no --rules='{"braces": true, "method_chaining_indentation": true}'`

**Comment by SpacePossum** [comment] 2020-02-26 16:23
Thanks for reporting!

I could reproduce on 2.15.dev.
Input:

```php
<?php

$values
->map(function ($value) {
return $value;
})
;
```

**Comment by julienfalque** [comment] 2020-02-26 17:28
I think this might become easier to fix once I finish splitting `BracesFixer`, but I have yet a lot of work to do :)

**Comment by Wirone** [comment] 2023-04-05 16:48
Thank you for taking your time reporting this, but unfortunately I'm going to close this because it's related to Fixer version which is not maintained anymore (2.x). Feel free to reproduce it on latest version (3.x) and create new issue.

**Closed by Wirone** 2023-04-05 16:48 UTC
Labels: kind/bug
