### ISSUE TITLE
PhpUnitAttributesFixer cannot handles multiple `@depends` tag

### ISSUE THREAD

**Issue by kayw-geek** [PHP-CS-Fixer/PHP-CS-Fixer#8157] opened 2024-08-06 02:40 UTC
### Problem description

When a test method have multiple the `@depends` tag, the `PhpUnitAttributesFixer` only one of the tags is converted to attribute.

### Minimal reproducer

```PHP
    /** 
     * @depends testFoo
     * @depends testBar
     */
    public function testDelete(): void
    {
    }
```
After fixed
```PHP
    /** 
     * @depends testBar
     */
    #[\PHPUnit\Framework\Attributes\Depends('testFoo')]
    public function testDelete(): void
    {
    }
```
At this time, phpunit will ignore the execution of the `testBar` method.

### Fixer version

3.59.3

### PHP version

8.3

### How do you run Fixer?

Composer package

### Contribution Checks

- [X] I have verified if this problem was already reported
- [X] I am familiar with ["Feature or bug?"](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/master/feature-or-bug.rst)

**Comment by kubawerlos** [comment] 2024-08-06 09:54
Duplicate of https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/issues/8072

**Closed by kubawerlos** 2024-08-06 09:54 UTC
Labels: kind/bug, status/to verify

**Comment by kayw-geek** [comment] 2024-08-07 02:15
> Duplicate of #8072

Hi @kubawerlos, This is not the same problem, I tested it again, the problem still exists, this problem is about multiple `@depends` tags not is `@group`.
