### ISSUE TITLE
Wrong indentation of arguments for multiline constructor params

### ISSUE THREAD

**Issue by ghost** [PHP-CS-Fixer/PHP-CS-Fixer#4282] opened 2019-01-27 13:57 UTC
#### The PHP version you are using (`$ php -v`):
=> PHP 7.2.12 (cli) (built: Nov  9 2018 11:00:45) ( NTS )

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
=> PHP CS Fixer 2.14.0 Sunrise by Fabien Potencier and Dariusz Ruminski

#### The command you use to run PHP CS Fixer:
=> php vendor/bin/php-cs-fixer fix ./src

#### The configuration file you are using, if any:
No custom configuration.

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):
 * before running PHP CS Fixer (no changes):
```php
<?php

class C{
  public function __construct(
    A $a,
    B $c
  ){
    // ..
  }
}
```

 * with unexpected changes applied when running PHP CS Fixer:
```php
<?php

class C
{
    public function __construct(
    A $a, // -> wrong indentation level (should be +4 spaces)
    B $c
  ) {
        // ..
    }
}
```

 * with the changes you expected instead:
```php
<?php

class C
{
    public function __construct(
        A $a,
        B $c
    ) {
        // ..
    }
}
```

**Comment by dmvdbrugge** [comment] 2019-01-28 10:36
I _think_ this is just a duplicate of #4281

**Comment by Wirone** [comment] 2023-04-06 08:05
Thank you for taking your time to report this, but unfortunately I'm going to close it since it refers to Fixer's version (2.x) which is not maintained anymore. Feel free to reproduce it on a latest version (3.x) and create new issue if problem still exists 🙂.

**Closed by Wirone** 2023-04-06 08:05 UTC
