### ISSUE TITLE
Incompatible with PHPUnit 10

### ISSUE THREAD

**Issue by raveren** [PHP-CS-Fixer/PHP-CS-Fixer#6790] opened 2023-02-23 09:42 UTC
When running `composer update`:

```
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - friendsofphp/php-cs-fixer[v3.10.0, ..., v3.14.3] require sebastian/diff ^4.0 -> satisfiable by sebastian/diff[4.0.0, ..., 4.0.4].
    - You can only install one version of a package, so only one of these can be installed: sebastian/diff[3.0.0, 3.0.1, 3.0.2, 3.0.3, 4.0.0, ..., 4.0.4, 5.0.0].
    - phpunit/phpunit[10.0.0, ..., 10.0.11] require sebastian/diff ^5.0 -> satisfiable by sebastian/diff[5.0.0].
```

I think `sebastian/diff` must be version bumped.

**Comment by kubawerlos** [comment] 2023-02-23 10:58
Duplicate of https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/pull/6771

**Closed by kubawerlos** 2023-02-23 10:58 UTC
Labels: kind/bug
