### ISSUE TITLE
class definitions in one line

### ISSUE THREAD

**Issue by bwoebi** [PHP-CS-Fixer/PHP-CS-Fixer#2782] opened 2017-05-18 10:19 UTC
Would it be possible to set some option which retains one liner class defs like:

```
class FooException extends Foo {} // or maybe { }
```

… currently the braces fixer (I don't really want to disable it…) transforms that into:

```
class FooException extends Foo {
}
```

which is a totally unnecessary newline. [And is driving me nuts mhm…]

(If requested I may also provide a PR.)

**Comment by SpacePossum** [comment] 2017-05-18 10:30
The current configuration options of the `braces` fixer do not provide what you want.
If you want you can add a new option through a PR.
You can follow something like the `allow_single_line_closure` option as an example how to add the option, and later how to provide sample code and documentation for it. 
As a new option I would suggest calling it something like `allow_single_line_anonymous_class`

**Comment by bwoebi** [comment] 2017-05-20 15:42
I've tried to implement it, but when I've fixed it on the braces fixer, the ClassDefinitionFixer reverted it.
Now I tried to fix it on the ClassDefinition fixer, and the braces fixer reverted it.

I somehow needed to add an option for both of them. Not sure what I can do to just need a single option here?

Concretely, the code I used for both:

```diff
diff --git a/src/Fixer/Basic/BracesFixer.php b/src/Fixer/Basic/BracesFixer.php
index f00ea6b8..3eef382f 100644
--- a/src/Fixer/Basic/BracesFixer.php
+++ b/src/Fixer/Basic/BracesFixer.php
@@ -160,6 +160,10 @@ protected function createConfigurationDefinition()
                 ->setAllowedTypes(['bool'])
                 ->setDefault(false)
                 ->getOption(),
+            (new FixerOptionBuilder('allow_single_line_class', 'Whether single line class notation should be allowed.'))
+                ->setAllowedTypes(['bool'])
+                ->setDefault(false)
+                ->getOption(),
             (new FixerOptionBuilder('position_after_functions_and_oop_constructs', 'whether the opening brace should be placed on "next" or "same" line after classy constructs (non-anonymous classes, interfaces, traits, methods and non-lambda functions).'))
                 ->setAllowedValues([self::LINE_NEXT, self::LINE_SAME])
                 ->setDefault(self::LINE_NEXT)
@@ -297,9 +301,14 @@ function ($item) {
             }
 
             if (
-                $this->configuration['allow_single_line_closure']
-                && $token->isGivenKind(T_FUNCTION)
-                && $tokensAnalyzer->isLambda($index)
+                (
+                    $this->configuration['allow_single_line_closure']
+                    && $token->isGivenKind(T_FUNCTION)
+                    && $tokensAnalyzer->isLambda($index)
+                ) || (
+                    $this->configuration['allow_single_line_class']
+                    && $token->isGivenKind(T_CLASS)
+                )
             ) {
                 $braceEndIndex = $tokens->findBlockEnd(
                     Tokens::BLOCK_TYPE_CURLY_BRACE,
diff --git a/src/Fixer/ClassNotation/ClassDefinitionFixer.php b/src/Fixer/ClassNotation/ClassDefinitionFixer.php
index d0e33604..a8ec9e4d 100644
--- a/src/Fixer/ClassNotation/ClassDefinitionFixer.php
+++ b/src/Fixer/ClassNotation/ClassDefinitionFixer.php
@@ -140,6 +140,10 @@ protected function createConfigurationDefinition()
                 ->setAllowedTypes(['bool'])
                 ->setDefault(false)
                 ->getOption(),
+            (new FixerOptionBuilder('classDeclSingleLine', 'Whether class declarations should be single line.'))
+                ->setAllowedTypes(['bool'])
+                ->setDefault(false)
+                ->getOption(),
         ]);
     }
 
@@ -265,6 +269,14 @@ private function fixClassyDefinitionOpenSpacing(Tokens $tokens, $classDefInfo)
             return $openIndex;
         }
 
+        if ($this->configuration['classDeclSingleLine'] && $tokens[$tokens->getNextNonWhitespace($openIndex)]->equals("}")) {
+            if ($tokens[$openIndex + 1]->isWhitespace()) {
+                $tokens[$openIndex + 1]->clear();
+            }
+
+            return $openIndex;
+        }
+
         if ($tokens[$openIndex - 1]->isWhitespace()) {
             if (' ' !== $spacing || !$tokens[$tokens->getPrevNonWhitespace($openIndex - 1)]->isComment()) {
                 $tokens[$openIndex - 1]->setContent($spacing);
```

**Comment by bwoebi** [comment] 2017-05-23 20:35
@SpacePossum I've been trying, but haven't got to any real end here - could you please give me some guidance? (See also the code diff above)

**Comment by SpacePossum** [comment] 2017-05-24 07:46
Hi @bwoebi sorry for not getting back earlier on this.
Thanks for the effort trying to get this fixed :)

The root cause of the problem with the solution is two fixers trying to do the same thing (i.e. fix class definition open braces). This can resolved by;
- adding the configuration option on both fixers
- drop the functionality of fixing the class opening on one fixer and add configuration to the other

TBH I'm kind of surprised we didn't run into a similar issue with the `braces` and `function_declaration` fixers when `allow_single_line_closure` was added.

Anyway...my preference would be to make the `braces` fixer stop moving the opening/closing braces of all `classy`'s (`class`, `interface` and `trait`). Than we move that responsibility over to `class_definition` and add a new configuration option there.
There are two things to note with that;
- `allow_single_line_closure` would be on `braces`, while `allow_single_line_anonymous_class` on `class_definition`, might be odd but still I think it would be better. Maybe in the future `allow_single_line_closure`  can be moved `function_declaration`
- changing the behavior of the `braces` fixer can be considered a feature loss

Like to hear more opinions on this, so I'm going to ping some people ;) @keradus @julienfalque

**Comment by bwoebi** [comment] 2017-05-24 08:05
Just to add, I wanted to allow these single line classes for everything, not just anon classes.  So, just `allow_single_line_class` (We could then allow `true|'anonymous'|false` as possible values or similar?).

**Comment by bwoebi** [comment] 2017-07-06 07:12
@SpacePossum Any news on this?

**Comment by SpacePossum** [comment] 2017-07-06 07:48
@julienfalque any thoughts?

**Comment by julienfalque** [comment] 2017-07-06 07:59
Making `braces` fixer stop moving braces for classy elements would be a BC break so we would have to add an option. Same for changing the behavior of `class_definition`. I would just add the options to both fixers and postpone any refactoring until next major release.

**Comment by SpacePossum** [comment] 2020-01-29 19:45
fixed in https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/4012 AFAIK

**Comment by julienfalque** [comment] 2020-01-30 07:21
Actually #4012 was only about anonymous classes.

**Comment by SpacePossum** [comment] 2020-01-30 07:25
check, thanks @julienfalque  :)

I makes me wonder how often a non-anonymous class is declared on one line, therefore I'm not in favor of supporting this case.

**Comment by Wirone** [comment] 2023-05-17 13:12
Hey!

Thanks for your report.

We identified that `braces` fixer is too complex and has too many responsibilities. With that, [we decided to deprecate it](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/pull/4885).

That also means that we will not be extending, changing the behaviour or fixing anything around braces fixer. Please, use [replacement rules](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/master/doc/rules/basic/braces.rst#this-rule-is-deprecated-and-will-be-removed-on-next-major-version) instead.

If you see the issue that you reported to be present in one of the replacement rules, please report a new issue.

Big thanks!

**Closed by Wirone** 2023-05-17 13:12 UTC
Labels: status/to verify, kind/feature request
