### ISSUE TITLE
function arguments space after comma doesn't work with built-in functions.

### ISSUE THREAD

**Issue by rufhausen** [PHP-CS-Fixer/PHP-CS-Fixer#4744] opened 2020-01-15 22:49 UTC
For configuration or updating questions please read the README and UPGRADE documentation,
or visit: https://gitter.im/PHP-CS-Fixer

When reporting an issue (bug) please provide the following information:

#### The PHP version you are using (`$ php -v`):
PHP 7.3.13 (cli) (built: Dec 18 2019 16:08:06) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.13, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.13, Copyright (c) 1999-2018, by Zend Technologies

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
 PHP CS Fixer 2.16.1 Yellow Bird by Fabien Potencier and Dariusz Ruminsk

#### The command you use to run PHP CS Fixer:
vendor/bin/php-cs-fixer fix -vv

#### The configuration file you are using, if any:
```php
$finder = PhpCsFixer\Finder::create()
    ->notPath('bootstrap/cache')
    ->notPath('storage')
    ->notPath('vendor')
    ->in(__DIR__)
    ->name('*.php')
    ->notName('*.blade.php')
    ->ignoreDotFiles(true)
    ->ignoreVCS(true);

return PhpCsFixer\Config::create()
    ->setRules([
        '@PSR2'                  => true,
        'binary_operator_spaces' => [
            'operators' => [
                '=>' => 'align_single_space_minimal',
                '='  => 'align_single_space_minimal', ],
        ],
        'array_indentation'                         => true,
        'array_syntax'                              => ['syntax' => 'short'],
        'combine_consecutive_unsets'                => true,
        'method_separation'                         => true,
        'no_multiline_whitespace_before_semicolons' => true,
        'single_quote'                              => true,
        'blank_line_before_return' => true,
        'braces'                   => [
            'allow_single_line_closure' => true,
        ],
        // 'cast_spaces' => true,
        // 'class_definition' => array('singleLine' => true),
        'concat_space'            => ['spacing' => 'one'],
        'declare_equal_normalize' => true,
        'function_typehint_space' => true,
        'hash_to_slash_comment'   => true,
        'include'                 => true,
        //'lowercase_cast' => true,
        // 'native_function_casing' => true,
        // 'new_with_braces' => true,
        'no_blank_lines_after_class_opening' => true,
        'no_blank_lines_after_phpdoc'        => true,
        'no_empty_comment'                   => true,
        // 'no_empty_phpdoc' => true,
        // 'no_empty_statement' => true,
        'no_extra_consecutive_blank_lines' => [
            'curly_brace_block',
            'extra',
            'parenthesis_brace_block',
            'square_brace_block',
            'throw',
            'use',
        ],
        'no_leading_import_slash' => true,
        'no_multiline_whitespace_around_double_arrow' => true,
        'no_singleline_whitespace_before_semicolons' => true,
        'no_spaces_around_offset'                    => true,
        'no_whitespace_before_comma_in_array' => true,
        'no_whitespace_in_blank_line'         => true,
        'object_operator_without_whitespace' => true,
        'phpdoc_align' => true,
        'return_type_declaration' => true,
        'single_blank_line_before_namespace' => true,
        'ternary_operator_spaces'           => true,
        'trailing_comma_in_multiline_array' => true,
        'trim_array_spaces'                 => true,
        'unary_operator_spaces'             => true,
        'whitespace_after_comma_in_array'   => true,
    ])
    ->setLineEnding("\n")
    ->setFinder($finder);
```

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):
 * before running PHP CS Fixer (no changes):
```php
    $bar = 'foo';
    $baz = 'foo';
    $boo = 'foo';

    unset($bar,$baz,$boo);
    foo($bar,$baz,$boo);
```

 * with unexpected changes applied when running PHP CS Fixer:
```php
    $bar = 'foo';
    $baz = 'foo';
    $boo = 'foo';

    unset($bar,$baz,$boo);
    foo($bar, $baz, $boo);
```

 * with the changes you expected instead:
```php
    $bar = 'foo';
    $baz = 'foo';
    $boo = 'foo';

    unset($bar, $baz, $boo);
    foo($bar, $baz, $boo);
```

Maybe this is expected behavior (?), but spacing is only added to arguments for custom function, not built-in functions.

**Comment by kubawerlos** [comment] 2020-01-15 23:43
> spacing is only added to arguments for custom function, not built-in functions.

No, no, no - that's not true.

Especially, in your example, I cannot see any built-in function - spoiler alert: `unset` is not a function, but [language construct](https://www.php.net/manual/en/function.unset.php#refsect1-function.unset-notes).

And you can [see](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v2.16.1/src/Fixer/FunctionNotation/MethodArgumentSpaceFixer.php#L155) it is expected behavior.

**Comment by rufhausen** [comment] 2020-01-16 02:41
# 
While unforgivable, please forgive me for referring to unset as a "function" as you are correct - in spite of it being listed under "Variable handling **functions**" on the official PHP docs and a thousand other places on the Internet.
[PHP: unset - Manual](https://www.php.net/manual/en/function.unset.php)
Example #1 of the official documentation displays a code snippet using unset()  (Not a function!!) very similar to my example with spacing. 

`list()` (also a Language Construct god dammit!) does format as I would expect in the following example.  I'm sure there's some language purity reason or whatever for this. I was just hoping that the formatting could be consistent regardless.

```php
    $array = ['one', 'two', 'three'];
	  list($bar, $baz, $boo) = $array;
```

**Comment by kubawerlos** [comment] 2020-01-16 17:20
Well, that's interesting. I've tracked it down to this PR: https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/2440/files#diff-4cfdb64e15658046dbe0cda315ed9a99R103

@greg0ire @keradus @julienfalque @SpacePossum do you know why all keywords are banned with the exception of `list` and `function` only? `isset`, `unset` or `printf` could be allowed as well or is there any reason for only these two?

**Comment by greg0ire** [comment] 2020-01-16 21:44
I probably overlooked them. Please make a PR.

**Comment by kubawerlos** [comment] 2020-01-17 07:35
@greg0ire no, you didn't overlooked them - you have added a test for them: https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/2440/files#diff-c2d4cc2096dd614d141880c5036ee9b0R639 so it was expected then not to fix `isset` and `unset`, but why? 🤔

**Comment by greg0ire** [comment] 2020-01-17 08:00
I did some more archaeology, here is the most related comment: https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/2440#issuecomment-307302637

**Comment by julienfalque** [comment] 2020-01-17 08:03
I see no reason not to fix `isset` or `unset`, let's update the tests.

**Comment by SpacePossum** [comment] 2020-01-17 15:47
See here for another example of the function vs. language construct discussion; https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/1692#issuecomment-173545467  

It boils down to most CS standards/descriptions like the PSR and also the rule names we have here like `*function*fixer` do not state that functions and language construction should be treated equally, even if `isset`, `unset`, `die`, `exit`, etc. look and typically behave exactly like functions, but than again they are not.

**Comment by sudofox** [comment] 2023-04-05 15:29
Ran into this today (I think) when I was like "hey, why isn't it putting a space after the comma in these define() calls?"

**Comment by Wirone** [comment] 2023-04-05 16:42
I'm going to close this because this report is related to Fixer version which is not maintained anymore (2.x). Feel free to reproduce it on latest version (3.x) and create new issue.

**Closed by Wirone** 2023-04-05 16:42 UTC
Labels: kind/enhancement

**Comment by SpacePossum** [comment] 2023-04-05 17:48
Reading back on this I just want so so say/clarify I think/feel language constructs CS should be fixed like functions in the context of the issues reported here (and possible others).

**Comment by Wirone** [comment] 2023-04-05 17:54
I agree, but if it's still the case (lack of support for language constructs), we should rather create new, clear issue with explicit context and scope 🙂.
