### ISSUE TITLE
why are indention and code styles being ignored 

### ISSUE THREAD

**Issue by snake-py** [PHP-CS-Fixer/PHP-CS-Fixer#6631] opened 2022-09-12 10:29 UTC
I followed the installation instructions and I am trying to utilize this as pre-commit hook, but the output looks awful: 

If I provide the command with the following php code it will not format it at all - is this intended or am I doing something wrong
```php
    public $elasticTemplate = [
        '_id' => null,
        'id' => null,
        'type' => null,
                    '@timestamp' => null,
        'environment' => null,
                 'internal_api_log_id' => null,
        'base_url' => null,
        '       product' => null,
        'stage' => null,
        'exception'
        =>
        [
            'trace' => null,
            'place'
            => null,
            'previousThrowable' =>
            null,
            'type' => null,
                'message' => null,
            'code' => null,
        ],
```
The command I am using:
```bash
tools/php-cs-fixer/vendor/bin/php-cs-fixer fix --using-cache=no --path-mode=intersection 
```

The config I have:
```php
<?php

$finder = PhpCsFixer\Finder::create()
    ->exclude('tools')
    ->in(__DIR__)
;

$config = new PhpCsFixer\Config();
return $config->setRules([
        '@PSR12' => true,
        'array_syntax' => ['syntax' => 'short'],
    ])
    ->setFinder($finder)
;
```

**Comment by keradus** [comment] 2022-12-04 21:28
hey, can you provide min-reproducible code snippet (cutting few lines from middle of file could hide the root cause of issue you are raising), as well as version of PHP CS Fixer that you are using?

**Comment by keradus** [comment] 2023-01-03 02:05
would you mind to create a min-preproduceable repository, when we have the actual Fixer config and an example PHP file [not small piece of it, but actual file that compiles] ?
otherwise, I am afraid that we will struggle to help, as struggle to reproduce.

**Comment by Wirone** [comment] 2023-06-17 13:44
With your code snippet and config from the reproducer repo:

<img width="901" alt="image" src="https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/assets/600668/f7c22e54-8729-42ee-a529-adc03b8cd1a6">

As you can see, applied fixers are: `semicolon_after_instruction`, `echo_tag_syntax`, and `yoda_style`. [`no_alternative_syntax`](https://cs.symfony.com/doc/rules/control_structure/no_alternative_syntax.html) is not used there because there's no control structure alternative syntax to fix (like `if($something):`).

In terms of initial question: if this is exact snippet that you were trying to fix, then there's no `<?php` opening tag so it is not considered as PHP to fix.

This issue clearly shows misusage and misunderstanding of the tool, that's why I am going to close it 🙂.

**Closed by Wirone** 2023-06-17 13:44 UTC
Labels: kind/question, status/to verify
