### ISSUE TITLE
align_double_arrow doesn't work for nested arrays

### ISSUE THREAD

**Issue by aario-k24** [PHP-CS-Fixer/PHP-CS-Fixer#5546] opened 2021-03-16 12:11 UTC
## Bug report
```
# php -v
PHP 7.4.6 (cli) (built: Jun  9 2020 13:55:33) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Xdebug v3.0.0, Copyright (c) 2002-2020, by Derick Rethans
```
```
# php-cs-fixer -V
PHP CS Fixer 2.18.2 Remote Void by Fabien Potencier and Dariusz Ruminski
```
```
# php-cs-fixer --using-cache=no -vvv fix 'a.php' --rules='{"binary_operator_spaces": {"align_double_arrow": true}}'
PHP CS Fixer 2.18.2 Remote Void by Fabien Potencier and Dariusz Ruminski
Runtime: PHP 7.4.6
Loaded config default from "/var/www/.php_cs.dist".
Paths from configuration file have been overridden by paths provided as command arguments.
F
Legend: ?-unknown, I-invalid file syntax (file ignored), S-skipped (cached or empty file), .-no changes, F-fixed, E-error
   1) www/a.php (binary_operator_spaces)

Fixed all files in 0.019 seconds, 12.000 MB memory used
```

### Code snippet that reproduces the problem

```php
<?php
$array1 = [
    'a' => [
        '1',
    ],
    'ab' => [
        '2',
    ],
    'abc' => [
        '3',
    ],
];

$array2 = [
    'a' => '1',
    'ab' => '2',
    'abc' => '3',
];
```
**Results:**
Array 1 is ignored while array 2 gets aligned.
```php
$array1 = [
    'a' => [
        '1',
    ],
    'ab' => [
        '2',
    ],
    'abc' => [
        '3',
    ],
];

$array2 = [
    'a'   => '1',
    'ab'  => '2',
    'abc' => '3',
];
```
**Expected Results:**
Both arrays must be aligned.

**Comment by VincentLanglet** [comment] 2021-11-16 11:11
Duplicate of https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/4395

**Closed** 2022-11-21 19:12 UTC
Labels: kind/bug
