### ISSUE TITLE
Function call arguments are not indented correctly; they are not left aligned

### ISSUE THREAD

**Issue by jdufresne** [PHP-CS-Fixer/PHP-CS-Fixer#3971] opened 2018-08-14 22:22 UTC
#### The PHP version you are using (`$ php -v`):

```
$ php -v
PHP 7.1.20 (cli) (built: Jul 19 2018 06:17:27) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
    with Xdebug v2.6.0, Copyright (c) 2002-2018, by Derick Rethans
```

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):

```
$ ./vendor/bin/php-cs-fixer --version
PHP CS Fixer 2.12.2 Long Journey by Fabien Potencier and Dariusz Ruminski
```

#### The command you use to run PHP CS Fixer:

```
./vendor/bin/php-cs-fixer fix src/my.php
```

#### The configuration file you are using, if any:

Default configuration.

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):
 * before running PHP CS Fixer (no changes):
```php
<?php
func(
    'arg1',
            'arg2',
                        'arg3'
);
```

 * with unexpected changes applied when running PHP CS Fixer:

(no change)

 * with the changes you expected instead:

```php
<?php
func(
    'arg1',
    'arg2',
    'arg3'
);
```

**Comment by Wirone** [comment] 2023-04-02 13:31
I'm going to close this because issue mentions Fixer version which is not maintained anymore. Feel free to reproduce it on latest version (if problem still exists) and create new issue.

**Closed by Wirone** 2023-04-02 13:31 UTC
Labels: kind/feature request
