### ISSUE TITLE
Typed properties not converted to use statment

### ISSUE THREAD

**Issue by alexander-schranz** [PHP-CS-Fixer/PHP-CS-Fixer#6105] opened 2021-11-12 14:41 UTC
## Bug report

PHP: 8.0.1
PHP CS FIXER: 3.2.1

### Code snippet that reproduces the problem

I'm not sure which rule is used for this but currently it seems like it does not work correctly for typed properties to convert `\Doctrine\ORM\EntityRepository` on a property to a use statenemt like it does for function or constructor arguments.

```php
class Test
{
    /**
     * @var EntityRepository<User>
     */
    private \Doctrine\ORM\EntityRepository $entityRepository; // <--

    public function __construct(
        private EntityManagerInterface $entityManager,
        protected \Doctrine\ORM\EntityRepository $entityRepository2
    ) {
        $this->entityRepository = $entityManager->getRepository(User::class);
    }
```

Only the `entityRepository2` is correctly converted from `\Doctrine\ORM\EntityRepository` -> `EntityRepository`.

Current result:

```php
use Doctrine\ORM\EntityRepository;

class Test
{
    /**
     * @var EntityRepository<User>
     */
    private \Doctrine\ORM\EntityRepository $entityRepository; // <--

    public function __construct(
        private EntityManagerInterface $entityManager,
        protected EntityRepository $entityRepository2
    ) {
        $this->entityRepository = $entityManager->getRepository(User::class);
    }
```

Expected result:

```php
use Doctrine\ORM\EntityRepository;

class Test
{
    /**
     * @var EntityRepository<User>
     */
    private EntityRepository $entityRepository; // <--

    public function __construct(
        private EntityManagerInterface $entityManager,
        protected EntityRepository $entityRepository2
    ) {
        $this->entityRepository = $entityManager->getRepository(User::class);
    }
```

**Comment by alexander-schranz** [comment] 2021-11-12 14:47
Could be related to #6074

**Comment by Wirone** [comment] 2023-06-16 14:53
Closing as duplicate of #5004.

**Closed by Wirone** 2023-06-16 14:53 UTC
Labels: status/duplicate, kind/feature request, topic/fqcn
