### ISSUE TITLE
Indentation of multiline annotation parameter is wrong

### ISSUE THREAD

**Issue by DieterHolvoet** [PHP-CS-Fixer/PHP-CS-Fixer#5755] opened 2021-06-01 13:07 UTC
### PHP version
8.0.3

### PHP CS Fixer version
2.19.0 Testament

### The command used to run PHP CS Fixer
```
./vendor/bin/php-cs-fixer fix --config=.php_cs.php public/modules/custom/wmcustom/src/Plugin/Filter/FilterTelUriSpaces.php -vvv
```
```
PHP CS Fixer 2.19.0 Testament by Fabien Potencier and Dariusz Ruminski
Runtime: PHP 8.0.3
Loaded config Wieni (PHP 8.0) from ".php_cs.php".
Using cache file "/Users/dieter/Projects/sites-wieni/xxx/backend/.cache/.php_cs.cache".
Paths from configuration file have been overridden by paths provided as command arguments.
F
Legend: ?-unknown, I-invalid file syntax (file ignored), S-skipped (cached or empty file), .-no changes, F-fixed, E-error
   1) /Users/dieter/Projects/sites-wieni/xxx/backend/public/modules/custom/wmcustom/src/Plugin/Filter/FilterTelUriSpaces.php (doctrine_annotation_indentation)

Fixed all files in 0.021 seconds, 16.000 MB memory used
```

### The configuration (file) you used
https://github.com/wieni/wmcodestyle/blob/release/v1/src/PhpCsFixer/Config/RuleSet/Php80.php

#### Before
```php
<?php

namespace Drupal\wmcustom\Plugin\Filter;

/**
 * @Filter(
 *     description = @Translation("According to <a href="":url"" target=""_blank"" rel=""noreferrer noopener"">RFC 3966</a>,
 *         ""tel"" URIs MUST NOT use spaces in visual separators to avoid excessive escaping.",
 *         arguments = { ":url" : "https://tools.ietf.org/html/rfc3966#section-5.1.1" }),
 * )
 */
class FilterTelUriSpaces
{
}
```

#### After
```php
<?php

namespace Drupal\wmcustom\Plugin\Filter;

/**
 * @Filter(
 *     description = @Translation("According to <a href="":url"" target=""_blank"" rel=""noreferrer noopener"">RFC 3966</a>,
 *         ""tel"" URIs MUST NOT use spaces in visual separators to avoid excessive escaping.",
 *     arguments = { ":url" : "https://tools.ietf.org/html/rfc3966#section-5.1.1" }),
 * )
 */
class FilterTelUriSpaces
{
}
```

**Comment by keradus** [comment] 2021-08-03 10:28
@DieterHolvoet  thanks for report! can you prepare a PR, please?

**Comment by Wirone** [comment] 2023-04-06 08:49
Thank you for taking your time to report this, but unfortunately I'm going to close it since it refers to Fixer's version (2.x) which is not maintained anymore. Feel free to reproduce it on a latest version (3.x) and create new issue if problem still exists 🙂.

Also, issue does not provide information *what* is wrong in the code after the change. For me it's correct: `arguments` was moved and has the same indentation as `description`. If you plan reproducing this on latest version and problem remains, please provide expected output too.

**Closed by Wirone** 2023-04-06 08:49 UTC
Labels: kind/bug
