### ISSUE TITLE
linebreak_after_opening_tag for non-monolithic files

### ISSUE THREAD

**Issue by nobuf** [PHP-CS-Fixer/PHP-CS-Fixer#5870] opened 2021-08-10 08:25 UTC
## Feature request

Apply `--rules=braces,linebreak_after_opening_tag` to the below code snippet:

  ```php
<div>

    <?php if (true) {
        foreach ([] as $value) { ?>

            <div>1</div>

        <?php } ?>

    <?php } else { ?>

        <div>2</div>

    <?php } ?>

</div>
  ```

After:

```php
<div>

    <?php if (true) {
    foreach ([] as $value) { ?>

            <div>1</div>

        <?php } ?>

    <?php
} else { ?>

        <div>2</div>

    <?php } ?>

</div>
```

Expected result:

```php
<div>

    <?php
    if (true) {
        foreach ([] as $value) { ?>

            <div>1</div>

        <?php } ?>

    <?php
    } else { ?>

        <div>2</div>

    <?php } ?>

</div>
```

```
php ~/Downloads/php-cs-fixer.phar -vvv fix --rules=braces,linebreak_after_opening_tag .

PHP CS Fixer 3.0.2 Constitution by Fabien Potencier and Dariusz Ruminski (990b979)
Runtime: PHP 7.3.28
...
```

While `braces` modified the indentation unexpectedly (it might be a separated issue), `linebreak_after_opening_tag` does nothing as it ignores non-monolithic files.

I'd like to see `linebreak_after_opening_tag` rule works on any multiple lines of php code. To keep `<?php } ?>` a single line seems reasonable though.

Can we possibly change the current behavior, or would adding an option be better?

Thanks!

**Comment by SpacePossum** [comment] 2021-09-02 07:25
Hi @nobuf and thanks for sharing your idea,

The `braces` changes might indeed be unexpected, currently this rule is being revised so lets see if after that there are still things left to do.

The current limitation of `linebreak_after_opening_tag` is by design. The tool supports little specifically CS for non-monolithic files, only where it is very easy and straight forward. As non-monolithic files come with a lot of CS considerations and also there being a lot of nice template systems out there to use as replacement of inline HTML - PHP  templating, we have to consider the amount of logic we can support and maintain here, as such we typically place requests for non-monolithic CS out of scope. Like to hear what the others think though :)

**Comment by keradus** [comment] 2023-03-31 19:51
Hey. thanks for your report!

I understand this is not best outcome for you, but core team will not put effort to fix this issue - I will also close it now [but feel free to continue discussion with anyone interested]

The HTML support will be revoked in code as it was never supposed to be officially supported. If you mix PHP with any other language, we consider it as bad practice and encourage to separate your logic from your view, and if you need code-support in view like for templating, we suggest to use one of templating engines.

If you want to still rely on Fixer for HTML-mixed files, till it's officially dropped, and you want to have bug you noticed fixed, I do encourage you to run PR with the fix. It will be recognised and merged with same flow as any other ticket - the only difference is that the fix need to come from interested ppl [and not from the core team]

You may take a look at search feature looking for HTML keyword to get extra context.

Big thanks for understanding!

----

also, `braces` fixer is deprecated by now

**Closed by keradus** 2023-03-31 19:51 UTC
Labels: status/won't do, kind/feature request
