### ISSUE TITLE
[method_argument_space] Adds a line break between attribute and variable in function declarations

### ISSUE THREAD

**Issue by guelosuperstart** [PHP-CS-Fixer/PHP-CS-Fixer#7260] opened 2023-08-30 06:52 UTC
### Description

In my function, the parameters are on several lines to respect the maximum line length.
One of my parameters is typed with an attribute, with the new version, the attribute and the variable are on 2 lines.
I'd like to keep method_argument_space.on_multiline = ensure_fully_multiline, to force all parameters to be on several lines if necessary.

### Runtime version
friendsofphp/php-cs-fixer  : v3.24.0
php : 8.2.8
SF : 6.3.4

### Used command

```sh
php-cs-fixer fix ./src ./tests --config=./devops/.php-cs-fixer.dist.php -v --diff --ansi --dry-run
```
### Configuration file

```php
<?php

declare(strict_types=1);

/*
 * This document has been generated with
 * https://mlocati.github.io/php-cs-fixer-configurator/#version:2.16.0|configurator
 * you can change this configuration by importing this file.
 */

return (new PhpCsFixer\Config())
    ->setRiskyAllowed(true)
    ->setRules([
        '@Symfony' => true,
        '@Symfony:risky' => true,
        '@PhpCsFixer' => true,
        '@PhpCsFixer:risky' => true,
        '@DoctrineAnnotation' => true,
        'concat_space' => ['spacing' => 'one'],
        'ordered_imports' => ['sort_algorithm' => 'alpha'],
        'multiline_whitespace_before_semicolons' => ['strategy' => 'no_multi_line'],
        'declare_strict_types' => true,
        'phpdoc_summary' => false,
        'native_function_invocation' => ['include' => ['@internal'], 'scope' => 'namespaced', 'strict' => true],
        'self_accessor' => false,
        'ordered_traits' => false,
        'types_spaces' => ['space' => 'single'],
        'class_definition' => ['single_line' => false],
        'phpdoc_align' => ['align' => 'left'],
        'class_attributes_separation' => [
            'elements' => ['method' => 'one', 'property' => 'one', 'trait_import' => 'one'],
        ],
    ])
    ->setUsingCache(false)
    ->setFinder(
        PhpCsFixer\Finder::create()
            ->exclude('vendor')
            ->in(__DIR__)
    );
```

### Code snippet that reproduces the problem

  ```php
  <?php
public function getExperiences(
        ExperienceSvc $experienceSvc,
        Request $req,
        #[CurrentUser] UserInterface $user
    ):{}
```

Result :
 ```php
  <?php
public function getExperiences(
        ExperienceSvc $experienceSvc,
        Request $req,
        #[CurrentUser] 
        UserInterface $user
    ):{}
```

Thank you

**Comment by Wirone** [comment] 2023-08-30 09:22
Hi @guelosuperstart, thanks for the report. I understand your consternation after the upgrade, but this is not a bug 🙂. First of all, before v3.24 attributes were not covered by Fixer in any way, there were not test cases for that. Behavior introduced in v3.24 is a new default, which is compliant with [PER-CSv2 §12.2](https://www.php-fig.org/per/coding-style/#122-placement):

> Attributes on classes, methods, functions, constants and properties MUST be placed on their own line, immediately prior to the structure being described.
> 
> For attributes on parameters, if the parameter list is presented on a single line, the attribute MUST be placed inline with the parameter it describes, separated by a single space. If the parameter list is split into multiple lines for any reason, the attribute MUST be placed on its own line prior to the parameter, indented the same as the parameter. If the parameter list is split into multiple lines, a blank line MAY be included between one parameter and the attributes of the following parameter in order to aid readability.

You're using `@PhpCsFixer` ruleset, which includes `method_argument_space` with a config `['on_multiline' => 'ensure_fully_multiline']` - that's why attributes are enforced on new line (strategy's name implies that, right?).

If you change to `['on_multiline' => 'ignore']`, then this fixer does not touch signatures like these:

```php
class MyClass
{
    public function __construct(
        private string $id,
        #[Foo] #[Bar] private ?string $name = null
    ) {}
}

class MyClass
{
    public function __construct(private string $id, #[Foo] #[Bar] private ?string $name = null) {}
}
```

If you would like to keep `ensure_fully_multiline`, but leave attributes untouched, then we would need to introduce some new strategy or additional option to be able to configure how attributes are handled.

Anyway, I'm going to close this as this is expected behavior (considering your config and what I said above). Feel free to [open new discussion with feature idea](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/discussions/new?category=feature-ideas) 🙂.

**Closed by Wirone** 2023-08-30 09:22 UTC
Labels: kind/bug

**Comment by guelosuperstart** [comment] 2023-08-30 09:41
Thank you @Wirone for your answer
Yes, I tested this configuration `['on_multiline' => 'ignore']` and it worked fine.

But i have this code : 


```php
class MyClass
{
    public function test(
        string $id,
        ?string $name = null, ?string $email = null, ?string $tel = null
    ): void {
    }
}
```

phpcsfixer no longer sets parameters on multiple lines :/

I'm safe for now because phpstorm or phpcsbeautifier can make the correction, but not all my developers can.

Thank you

**Comment by Wirone** [comment] 2023-08-30 09:55
Yes, this is the tradeoff of `['on_multiline' => 'ignore']`. But when you think about it, it's totally what you would expect - if Fixer encounters multiline signature (`on_multiline`), then `ignore` leaves everything as-is, while `ensure_fully_multiline`, well, ensures fully multiline, also for attributes 😅. As I said, we would need to introduce some kind of config to tell Fixer to keep attributes in the same line as params, but it again gets complicated:
- multiple short attributes may be OK-ish to fit in one line
- even one, but long attribute may decrease readability of the param
- what about multiline attribute?

I believe it's easier to get used to what PER-CS proposes - each attribute in separate line 😉.

**Comment by guelosuperstart** [comment] 2023-08-31 05:28
Hello @Wirone 

ok I see, you refer to this point `https://www.php-fig.org/per/coding-style/#122-placement`
I think it's a lot of linefeed and doesn't really improve the readability of the code, but if it's good practice ^.

Thank you very much for your answers and time 👌

**Comment by guelosuperstart** [comment] 2023-09-14 09:13
@Wirone Yes ^^ : It's soon : version 3.2 will be released on September, 2023;
