### ISSUE TITLE
(Priority?) binary_operator_spaces misbehaving together with array_indentation

### ISSUE THREAD

**Issue by dmvdbrugge** [PHP-CS-Fixer/PHP-CS-Fixer#3859] opened 2018-07-03 13:09 UTC
#### The PHP version you are using (`$ php -v`):
```
PHP 7.1.18 (cli) (built: May 25 2018 19:18:59) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.1.18, Copyright (c) 1999-2018, by Zend Technologies
```

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
`PHP CS Fixer 2.12.1 Long Journey by Fabien Potencier and Dariusz Ruminski`

#### The command you use to run PHP CS Fixer:
`vendor/bin/php-cs-fixer fix -v --using-cache=no`

#### The configuration file you are using, if any:
Basically the same as [dmvdbrugge/dynamic-components](https://github.com/dmvdbrugge/dynamic-components/blob/5dfba1d7ea9573b2f2d75468556c988019be541c/.php_cs.dist), except `explicit_string_variable`, `header_comment`, `no_alternative_syntax`, and `no_unset_on_property`

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):
 * before running PHP CS Fixer (no changes):
```php
function show_conflict($priority, $binary, $array)
{
    if (!$priority ||
        in_array($priority, [
            $binary,
            $array,
        ]) ||
        $binary == $array // Here's a comment
    ) {
        break;
    }
}
```

* after first run:
```diff
--- Original
+++ New
@@ @@
 function show_conflict($priority, $binary, $array)
 {
-    if (!$priority ||
-        in_array($priority, [
+    if (!$priority || in_array($priority, [
             $binary,
             $array,
-        ]) ||
-        $binary == $array // Here's a comment
+        ]) || $binary == $array // Here's a comment
     ) {
         break;
     }
 }
```

* after second run:
```diff
--- Original
+++ New
@@ @@
 function show_conflict($priority, $binary, $array)
 {
     if (!$priority || in_array($priority, [
-            $binary,
-            $array,
-        ]) || $binary == $array // Here's a comment
+        $binary,
+        $array,
+    ]) || $binary == $array // Here's a comment
     ) {
         break;
     }
 }
```
Note the ugly resulting alignment.

* expected:
Immediately arrive at the last step

**Alternatively**
`binary_operator_spaces` could have fixed it differently, because the end result is doubtful anyway.

When I manually change the code to the following (moving the first `||` to the start of the next line):
```php
function show_conflict($priority, $binary, $array)
{
    if (!$priority
        || in_array($priority, [
            $binary,
            $array,
        ]) ||
        $binary == $array // Here's a comment
    ) {
        break;
    }
}
```

And then run fixer, the result is this (and doesn't change when running again):
```php
function show_conflict($priority, $binary, $array)
{
    if (!$priority
        || in_array($priority, [
            $binary,
            $array,
        ]) || $binary == $array // Here's a comment
    ) {
        break;
    }
}
```
Which is imho much more acceptable.

Meta: this is case 24 of #3844

**Comment by Wirone** [comment] 2023-04-02 13:36
I'm going to close this because issue mentions Fixer version which is not maintained anymore. Feel free to reproduce it on latest version (if problem still exists) and create new issue.

**Closed by Wirone** 2023-04-02 13:36 UTC
Labels: kind/bug
