### ISSUE TITLE
Rule request to avoid breaking #region comments

### ISSUE THREAD

**Issue by m4n50n** [PHP-CS-Fixer/PHP-CS-Fixer#7789] opened 2024-01-30 12:49 UTC
I constantly use the _#region_ and _#endregion_ comments to separate chunks of code, but for them to work there must be no separation between "#" and "region".

The *single_line_comment_spacing* rule is replacing ```#region``` with ```// region``` and ```#endregion``` with ```// endregion```

Is there an option to set some configuration to avoid this? I can't find a way to do it.

Thanks!

**Comment by Wirone** [comment] 2024-01-30 12:58
Duplicate of #6968, I am going to close this [for the same reason](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/issues/6968#issuecomment-1680520048).

**Closed by Wirone** 2024-01-30 12:58 UTC
Labels: kind/feature request
