### ISSUE TITLE
multiline_whitespace_before_semicolons fixer using new_line_for_chained_calls config fails on a parenthesis surrounded statement followed by fluid function calls

### ISSUE THREAD

**Issue by robfrawley** [PHP-CS-Fixer/PHP-CS-Fixer#5763] opened 2021-06-07 03:27 UTC
## Bug Report: `multiline_whitespace_before_semicolons`

When running the `multiline_whitespace_before_semicolons` fixer with a `{strategy: new_line_for_chained_calls}` config, the *final semicolon placement* is incorrect for a *parenthesis surrounded statement (such as an instantiation assignment) followed by fluid function calls*.

Example snippet (before running fixer):

```php
<?php

function foo(): array
{
    ($bar = new Bar())
        ->qux();
}
```

Expected result:
```php
<?php

function foo(): array
{
    ($bar = new Bar())
        ->qux()
    ;
}
```

Actual result:
```php
<?php

function foo(): array
{
    ($bar = new Bar())
        ->qux()
;
}
```

### Environment Details

- __PHP Version:__ 
  `PHP 8.0.5 (cli) (built: May  3 2021 11:31:15) ( NTS )`

- __PHP-CS-Fixer Version:__
  `Latest Git 3.0 Branch`

- __System Information:__
  `Linux oompa 5.11.0-19-generic #20-Ubuntu SMP Tue Jun 1 10:51:47 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

- __Invocation Type:__
  Added a test case to [`MultilineWhitespaceBeforeSemicolonsFixerTest::provideSemicolonForChainedCallsFixCases()`](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/3.0/tests/Fixer/Semicolon/MultilineWhitespaceBeforeSemicolonsFixerTest.php#L233), ran my local `phpunit` phar (version `9.5.4`) from the repo root by passing the project's [`phpunit.xml.dist`](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/3.0/phpunit.xml.dist) file to the config option and specifying the problematic fixer filepath of [`MultilineWhitespaceBeforeSemicolonsFixerTest`](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/3.0/tests/Fixer/Semicolon/MultilineWhitespaceBeforeSemicolonsFixerTest.php) as the only argument.

### Reproduction Instructions

You can quickly reproduce the issue by cloning my fork of the repository, which has a single commit containing an added test case the relevant fixer unit test, fetching the vendor dependencies, and running `phpunit` as specified.

```bash
git clone git@github.com:robfrawley/php-cs-fixer.git
cd php-cs-fixer
composer install
phpunit \
    --config phpunit.xml.dist \
    --stop-on-error \
    --stop-on-failure \
    tests/Fixer/Semicolon/MultilineWhitespaceBeforeSemicolonsFixerTest.php
```

### Problematic Test Diff

If you want to apply a patch to your own copy of the repository `3.0` branch, you can view the appropriate patch at [robfrawley/php-cs-fixer/commit/300f7865bb10c347374cd5f58affe3eee4c86d56.diff](https://github.com/robfrawley/php-cs-fixer/commit/300f7865bb10c347374cd5f58affe3eee4c86d56.diff) containing the following diff:

```diff
diff --git a/tests/Fixer/Semicolon/MultilineWhitespaceBeforeSemicolonsFixerTest.php b/tests/Fixer/Semicolon/MultilineWhitespaceBeforeSemicolonsFixerTest.php
index 02c03c545f..df46c6ec87 100644
--- a/tests/Fixer/Semicolon/MultilineWhitespaceBeforeSemicolonsFixerTest.php
+++ b/tests/Fixer/Semicolon/MultilineWhitespaceBeforeSemicolonsFixerTest.php
@@ -838,6 +838,27 @@ function foo($bar)
         ->methodA()
         ->methodB();',
             ],
+            [
+                '<?php
+
+                    function foo(): array
+                    {
+                        ($bar = new Bar())
+                            ->qux()
+                        ;
+                    }
+
+                ?>',
+                '<?php
+
+                    function foo(): array
+                    {
+                        ($bar = new Bar())
+                            ->qux();
+                    }
+
+                ?>',
+            ],
         ];
     }
 
```

**Comment by robfrawley** [comment] 2021-06-08 00:46
The issue is likely with the [MultilineWhitespaceBeforeSemicolonsFixer::findWhitespaceBeforeFirstCall()](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/6cee2bedbb432941a0c894ab35a9920b6ffe8562/src/Fixer/Semicolon/MultilineWhitespaceBeforeSemicolonsFixer.php#L207) implementation, which incorrectly determines that `function foo(): array` is the first part of the chained call, instead of the correct determination of `($bar = new Bar())` in the following code:

```php
function foo(): array // <-- Incorrectly determines this is the chained call first line
{
    ($bar = new Bar()) // <-- Instead of the correct beginning of the chained call, here
        ->qux();
}
```

**Comment by keradus** [comment] 2021-08-03 10:27
@robfrawley thanks for report! can you prepare a PR, please?

**Comment by robfrawley** [comment] 2021-11-21 23:02
> "@robfrawley thanks for report! can you prepare a PR, please?" - @keradus 

@keradus I've been exceptionally busy, so apologies for the lack of any response from me; is this issue still unresolved? If so, I can now put some time into attempting a fix toward eventually offering a PR.

**Comment by Wirone** [comment] 2023-05-12 22:24
Cannot reproduce on `3.16-DEV` (current master):

<img width="1265" alt="image" src="https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/assets/600668/0395b21e-9653-4b8e-a8f3-b910caa72392">

I'm going to close this, because it works as expected (or will be in upcoming release 😉).

**Closed by Wirone** 2023-05-12 22:24 UTC
Labels: kind/bug
