### ISSUE TITLE
Return error code on invalid file

### ISSUE THREAD

**Issue by julienfalque** [PHP-CS-Fixer/PHP-CS-Fixer#4133] opened 2018-12-04 15:28 UTC
Currently, when PHP CS Fixer processes a file and somehow introduces a syntax error in it (because of a bug), the command exits with `0`. IMO the command should exit with an error code in such case.

Maybe we could also add a new option to make the command fail even for files that are invalid _before_ being processed. WDYT?

**Comment by SpacePossum** [comment] 2018-12-04 16:03
The first case sounds like a bug to me :)

Second case, sounds logical to me, so +1 as well

**Comment by keradus** [comment] 2018-12-08 09:58
> Currently, when PHP CS Fixer processes a file and somehow introduces a syntax error in it (because of a bug), the command exits with `0`.

we have the fail-safe mechanism, that if "fixing" process would corrupt the file, we don't apply it. For that, the whole CLI took worked. I agree it may make sense to raise warning in such case, maybe even we already have it, not sure

> Maybe we could also add a new option to make the command fail even for files that are invalid before being processed. WDYT?

we already have:
> 4 Some files have invalid syntax (only in dry-run mode).

**Comment by SpacePossum** [comment] 2018-12-10 07:38
> we have the fail-safe mechanism, that if "fixing" process would corrupt the file, we don't apply it. For that, the whole CLI took worked.

If a fixer find something that it should fix and than fails and causes an internal exception, we indeed do not apply it, however the file is than not fixed so the whole CI didn't work as expected (the result is that a file still needs fixing which wasn't done).

**Comment by dmvdbrugge** [comment] 2019-06-03 14:50
I agree with @SpacePossum here. In a pre-commit hook, I want to abort when a file could not be fixed (aka it failed fixing). If however the cli-tool says it succeeds (exit 0), how can I know that it failed?

**Comment by dmvdbrugge** [comment] 2019-06-03 15:15
To add even more to this: on lint exception, `--dry-run --diff` exits with 0 as well even though it has a diff and thus tried to fix the file. (So the 8 flag should've been set at least imho.)

**Comment by keradus** [comment] 2019-06-04 04:53
> If a fixer find something that it should fix and than fails and causes an internal exception, we indeed do not apply it, however the file is than not fixed so the whole CI didn't work as expected (the result is that a file still needs fixing which wasn't done).

We dont know that. Internal exception can happen on anything. But good reasoning for linting-after-fixing error

**Comment by SpacePossum** [comment] 2019-10-11 19:24
First part (exit code on lint failure after fixing) has been covered, second FR is still up for discussion.

**Comment by keradus** [comment] 2019-10-21 05:50
What is a 2nd FR part here?

**Comment by julienfalque** [comment] 2019-10-21 06:26
The second part is about returning a non zero code when the tool tried to fix a file that already has invalid syntax by making it global behavior, i.e. not only in dry-run mode, either by default or using a new option.

I wanted to start a discussion because I think it can be useful but finding files with invalid syntax can be done with other tools such as PHPStan anyway so I'm fine if we don't change the current behavior :)

**Comment by Wirone** [comment] 2023-06-15 00:50
Non-zero exit code is used when file has invalid syntax before applying fixes:

<img width="1641" alt="image" src="https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/assets/600668/5baa43ec-bc96-46df-ab72-f4b780b02f1b">

Non-zero exit code for linting error after fixes was [also added at some point](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/issues/4133#issuecomment-541193072), so it looks like all scenarios are covered. I'm going to close this, feel free to report any problems with exit code in separate issue.

**Closed by Wirone** 2023-06-15 00:50 UTC
Labels: status/to verify, kind/feature request, topic/I/O

**Comment by SpacePossum** [comment] 2023-06-15 05:11
>Non-zero exit code is used when file has invalid syntax before applying fixes

sure, but the first first ask is

>Currently, when PHP CS Fixer processes a file and somehow introduces a syntax error in it (because of a bug), the command exits with 0.

so _after_ applying fixes and only not _before_ , so I think half of this issue is confirmed resolved ;)

**Comment by Wirone** [comment] 2023-06-15 05:22
@SpacePossum I read comments and:

> First part (exit code on lint failure after fixing) has been covered, second FR is still up for discussion.

> The second part is about returning a non zero code when the tool tried to fix a file that already has invalid syntax

 [First was confirmed by you](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/issues/4133#issuecomment-541193072), [second was confirmed by me](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/issues/4133#issuecomment-1592171672). So either it's fully covered or you provided wrong information before 😉.
