### ISSUE TITLE
method_argument_space: Useful algorithm-control options. braces: PSR-2 compatibility

### ISSUE THREAD

**Issue by ghost** [PHP-CS-Fixer/PHP-CS-Fixer#3097] opened 2017-09-25 17:30 UTC
### Edit: This ticket has now turned into a suggestion for improving the `method_argument_space` code by adding control over its algorithms (its current behavior is haphazard and useless), and giving it support for a PSR-2 style requirement that it currently violates. See further posts below.

-----

Hey guys, I've constantly had trouble with open-source projects because people can't format function arguments properly. I noticed that there is no fixer for it, but I have an idea that seems pretty easy to implement.

This proposed fixer algorithm would only need to affect the portion between the `()` after the function name. It would ignore the `function () { // bracket` that comes after the `)`, since the function-opening-bracket formatting is up to the user or another fixer (such as a `newline after function parameter () block before the {` fixer). And this algorithm also doesn't need to care about `$a=null` vs `$a = null` (assignment operator spacing) since that could be yet another separate fixer.

So this proposed algorithm would _only_ need to manipulate the area within the function's `()` for its argument list... and can ignore everything else. And it will _only_ need to concern itself with the comma-separated "argument entities" within that argument list, and doesn't need to care about how each entity is internally formatted (ie `$a=null` vs `$a = null` doesn't matter to this fixer).

Therefore it should be pretty easy to code this particular fixer, since all it would do is look at comma-separated function argument tokens, and affecting the whitespace _around_ those tokens.

* `multiline = false`:

Puts all arguments on a single line and ensures that there's a single space between each argument (`$a, $b = null, $c=true` instead of `$a,$b = null,$c=true`; note how it ignores the spacing around the `=` operator, but fixes the spacing between `arg, arg, arg`).

```
function foo($a, $b = null, $c)
{
    ...
}
```

* `multiline = true, preNewline = true, postNewline = false`

This is my preferred style in all projects because it makes functions ultra-clear.

```
function foo(
    $a,
    $b = null,
    $c)
{
    ...
}
```

* `multiline = true, preNewline = false, postNewline = false`

```
function foo($a,
             $b = null,
             $c)
{
    ...
}
```

* `multiline = true, preNewline = false, postNewline = true`

```
function foo($a,
             $b = null,
             $c
)
{
    ...
}
```

* `multiline = true, preNewline = true, postNewline = true`

```
function foo(
    $a,
    $b = null,
    $c
)
{
    ...
}
```

It _seems_ like it would be really simple to someone who knows how to write fixers. Does any of the PHP-CS-Fixer professionals feel up to the task, perhaps as a bit of recreational hobby programming some evening? I have literally no insight into the internals of this project, beyond the fact that it tokenizes the source code and acts on tokens. So it would take me weeks to code this fixer. But I think it would be of great value to the community to help ensure unified and clear function argument lists, so I don't want to let the idea go wasted. Hopefully some ninja out there feels up to implementing it. :-)

**Comment by SpacePossum** [comment] 2017-09-26 08:22
>Does any of the PHP-CS-Fixer professionals feel up to the task, perhaps as a bit of recreational hobby programming some evening

There are no professionals, its all a hobby to us (maintainer and members) here ;)

About your idea, nice listing and good read!

This one `This is my preferred style in all projects because it makes functions ultra-clear.` is PSR2 and I think it is the only we should support TBH.

Using the `method_argument_space` with the `ensure_fully_multiline`-option I think should already do this. Can you give it a try or if you already did can you provide a sample of something that is not fixed as expected?

**Comment by SteveJobzniak** [comment] 2017-09-26 10:57
Hey @SpacePossum, thanks for the nice response! :-)

I know about `method_argument_space` precisely because that one is such a _totally-useless_ fixer (at the moment). But you bring us to a good idea: _That_ fixer can be improved to make it awesome, since some ninja has already written all of the code to handle correctly re-arranging argument spacing, as well as all the tests to handle weird cases (holy... sh... https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/2.6/tests/Fixer/FunctionNotation/MethodArgumentSpaceFixerTest.php, there was a lot more to test than I thought about).

Now let me demonstrate why `method_argument_space` is probably the most useless fixer in PHP-CS-Fixer at the moment. ;-)

- `.php_cs.dist`

```php
<?php

return PhpCsFixer\Config::create()
    ->setFinder(
        PhpCsFixer\Finder::create()
        ->in(__DIR__)
    )
    ->setIndent('    ')
    ->setLineEnding("\n")
    ->setRules([
        'method_argument_space' => [
            'ensure_fully_multiline' => true,
            'keep_multiple_spaces_after_comma' => true,
        ],
    ]);
```

- `bad.php` BEFORE FIXING:

```php
<?php

function a($a,$b,$c)
{
    other(sprintf(
        'Example with %s and %s and %s.',
        $a, $b, $c
    ));
}
```

- `bad.php` AFTER FIXING:

```php
<?php

function a($a, $b, $c)
{
    other(sprintf(
        'Example with %s and %s and %s.',
        $a,
        $b,
        $c
    ));
}
```

"Wow"... it did... nothing except waste more space on the inner function call. ;-)

But the fixer obviously has the correct _internal_ algorithms for being _able_ to re-arrange arguments to either single-line or multi-line... I'll think for a moment about some potential new flag to fix the fixer... in a backwards-compatible way (so that the old, useless behavior is still the default and works the same way)...

**Comment by SteveJobzniak** [comment] 2017-09-26 11:12
```php
        'method_argument_space' => [
            'ensure_fully_multiline' => true, // DEPRECATED
            'keep_multiple_spaces_after_comma' => true,
            'line_style' => [
                'function_definition' => 3,
                'function_call'       => 0,
            ],
        ],
```

Where the following changes are made to the fixer:

- Deprecate `ensure_fully_multiline` as follows: If the `line_style` option has been provided, then TOTALLY IGNORE the value of `ensure_fully_multiline`.
- Let `line_style` independently control the behavior of function definitions and function calls.
- Style `-1`: Do nothing. Totally ignore that call/definition, as if the fixer didn't even exist. Don't even fix commas.
- Style `0`: Only fix commas (`$a,$b` into `$a, $b`). This totally ignores the newline style of the call/definition. This is exactly like the behavior of `ensure_fully_multiline => false` in current fixer.
- Style `1`: "Ensure fully multiline". If this call/definition contains a single newline anywhere, then force ALL arguments onto individual lines. This is exactly like the behavior of `ensure_fully_multiline => true` in current fixer.
- Style `2`: "Force single line". Forces all arguments of this call/definition onto a single line... POTENTIAL ISSUE HERE: What do we do if they provide a multiline string as argument, or a multiline comment inside the argument list? The "force to single line" fixer would be very difficult to implement.
- Style `3`: "Force multi-line". Forces all arguments of this call/definition onto separate lines. NO ISSUES HERE: This fixer would always be safe, since anything that's single-line can safely be made into multi-line.

**Comment by SteveJobzniak** [comment] 2017-09-26 11:41
Lastly, there needs to be a fix to the current `ensure_fully_multiline` algorithm. It violates PSR-2.

http://www.php-fig.org/psr/psr-2/#44-method-arguments

```php
// Before fix:
function a($a,
    $b,$c)
{
}

// After fix (violates PSR-2):
function a(
    $a,
    $b,
    $c
)
{
}
```

However, PSR-2 dictates:

> Argument lists MAY be split across multiple lines, where each subsequent line is indented once. When doing so, the first item in the list MUST be on the next line, and there MUST be only one argument per line.
> When the argument list is split across multiple lines, the closing parenthesis and opening brace MUST be placed together on their own line with one space between them.

In other word, the `)` and `{` of a multiline function definition in PSR-2 `MUST` be _exactly_: `) {`.

So the correct "convert it to multiline" result must be:

```php
function a(
    $a,
    $b,
    $c
) {
}
```

Perhaps leave that as a separate option: `line_style` value: `multiline_psr2` (so `multiline` = current behavior, `multiline_psr2` = also enforce the `) {` style they require).

**Comment by SteveJobzniak** [comment] 2017-09-26 12:06
To recap the 3 posts above, here's the trivial lists of changes needed to turn `method_argument_space` into a good fixer:

1. Add a new `line_style` option that provides individual control over "function calls" vs "function definitions", as well as allowing the user to always force multiline (unlike the current algorithm which only does it when a partially-multiline scenario is discovered). Very easy, since the internal algorithms to handle all options already exist in the code.
2. Add a handful of tests to ensure that the `line_style` option is applied properly. Very easy, since all other fixing-scenarios are handled by the existing tests.
3. Add a new `multiline_psr2` mode which is like "multiline" but also enforces the PSR-2 `MUST` of opening the function bracket after the arguments as `) {`.

**Comment by SpacePossum** [comment] 2017-09-26 12:11
I've to reread everything for a full response on all of this. However point 3 is not valid. The fixer has a single responsibility; fix the CS, i.e. the spacing, around arguments. The space after the closing brace and the opening bracket is not part of that.

**Comment by SteveJobzniak** [comment] 2017-09-26 12:26
@SpacePossum Understood. Another reason to re-read is because I've edited all posts to clarify any unclear sections. ;-)

As for point 3: As I said in my original post, I thought the fixer has a single responsibility: Argument spacing. The problem is that when it changes something to multiline arguments, it violates a PSR-2 "`MUST`" if it doesn't also fix the `) {`. And the fixer, in "force-multiline" mode, would _always_ generate such invalid non-PSR2 output anytime it turns a single-line function definition into multiline.

So in this case, I think the fixer is responsible for ensuring that the opening bracket follows PSR-2. At least as separate options: `multiline_psr2` and `ensure_fully_multiline_psr2`. For those who want it to enforce valid PSR-2 style whenever the fixer chooses "multiline style" for a function definition.

**Comment by SteveJobzniak** [comment] 2017-09-26 15:59
Hmm, about the PSR-2 stuff... I see that there's a separate fixer for that:

https://github.com/FriendsOfPHP/PHP-CS-Fixer

Read about `braces`. It has `position_after_functions_and_oop_constructs = same`. It defaults to `next`...

It's kinda not-right, though... See http://www.php-fig.org/psr/psr-2/

> Opening braces for classes MUST go on the next line, and closing braces MUST go on the next line after the body.
> Opening braces for methods MUST go on the next line, and closing braces MUST go on the next line after the body.

In the case of multiline function definitions, the following is needed:

```php
class Foo
{
    function a(
        $a,
        $b
    ) {
    }
}
```

But since `braces` only supports `position_after_functions_and_oop_constructs` as a single option, then we cannot set up: "oop: next, functions: same".

This is a good example of why options should never affect multiple structural elements at once. :-)

The `braces` fixer needs separate options for `position_after_functions` and `position_after_oop_constructs`. It can be added to it in a backwards-compatible way, by deprecating `position_after_functions_and_oop_constructs`.

**Closed** 2023-03-10 00:21 UTC
Labels: kind/question, kind/feature request
