### ISSUE TITLE
`?xxx` to `xxx|null` for phpdoc fixer

### ISSUE THREAD

**Issue by mvorisek** [PHP-CS-Fixer/PHP-CS-Fixer#7792] opened 2024-01-31 10:48 UTC
## Feature request

Expected output:

```diff
 <?php

 class {
-    /** @var ?MyClass */
+    /** @var MyClass|null */
     public $v;
 }
```

**Comment by Wirone** [comment] 2024-01-31 11:15
Duplicate of #3562.

**Closed by Wirone** 2024-01-31 11:15 UTC
Labels: kind/feature request
