### ISSUE TITLE
Something wrong with an indentation and switch statement

### ISSUE THREAD

**Issue by F8ER** [PHP-CS-Fixer/PHP-CS-Fixer#4986] opened 2020-06-01 13:04 UTC
Dear Developers,

Thank you for this project.

Although, there might be some issue when it turn such code:
![](https://i.imgur.com/tOhzVh1.png)
into
![](https://i.imgur.com/N3oJP58.png)
Thus, it does not convert indention into tabs and adds some space before `break;` command.

This is the `php_cs.dist`:

```
<?php

return PhpCsFixer\Config::create()
	->setRules([
		'@PSR2' => true,
		'@PhpCsFixer' => true,
		'array_indentation' => true,
		'array_syntax' => ['syntax' => 'short'],
		'combine_consecutive_unsets' => true,
		'method_separation' => true,
		'no_multiline_whitespace_before_semicolons' => true,
		'single_quote' => true,
		'binary_operator_spaces' => [
			'align_double_arrow' => false,
			'align_equals' => false,
		],
		'braces' => [
			'allow_single_line_closure' => true,
		],
		'concat_space' => ['spacing' => 'one'],
		'declare_equal_normalize' => true,
		'function_typehint_space' => true,
		'hash_to_slash_comment' => true,
		'include' => true,
		'lowercase_cast' => true,
		'no_extra_consecutive_blank_lines' => [
			'curly_brace_block',
			'extra',
			'parenthesis_brace_block',
			'square_brace_block',
			'throw',
			'use',
		],
		'no_multiline_whitespace_around_double_arrow' => true,
		'no_spaces_around_offset' => true,
		'no_whitespace_before_comma_in_array' => true,
		'no_whitespace_in_blank_line' => true,
		'object_operator_without_whitespace' => true,
		'single_blank_line_before_namespace' => true,
		'ternary_operator_spaces' => true,
		'trim_array_spaces' => true,
		'unary_operator_spaces' => true,
		'whitespace_after_comma_in_array' => true,
		'no_closing_tag' => false,
        'blank_line_before_statement' => false
	])
	->setIndent("\t")
	->setLineEnding("\n");
```

This is the command:
```
php C:\php-cs-fixer.phar fix --config C:\php_cs.dist --using-cache=no C:\1.php
```
This is the version:
```
Version: PHP CS Fixer 2.16.3 Yellow Bird by Fabien Potencier and Dariusz Ruminski (83baf82)
```

What might this be?

Best regards

**Comment by SpacePossum** [comment] 2020-06-01 16:05
Hi and thanks for reporting,

Minimal example (copy-paste-able):

```php
<?php

switch ($foo) {
	case 'bar': {
    } break;
}
```

running:

>$ php php-cs-fixer fix test.php -vvv --diff --rules=no_unneeded_curly_braces --dry-run

Basically; after the `no_unneeded_curly_braces` has been run there is `\n\t break;` and no rule removes the space after the tab. Not sure which rule it should fix, maybe we expect `indentation_type` to fix it..

**Comment by Wirone** [comment] 2023-04-05 16:46
Thank you for taking your time reporting this, but unfortunately I'm going to close this because it's related to Fixer version which is not maintained anymore (2.x). Feel free to reproduce it on latest version (3.x) and create new issue.

**Closed by Wirone** 2023-04-05 16:46 UTC
Labels: kind/bug
