### ISSUE TITLE
no_superfluous_phpdoc_tags fixer: return type self

### ISSUE THREAD

**Issue by OskarStark** [PHP-CS-Fixer/PHP-CS-Fixer#3932] opened 2018-07-19 05:43 UTC
For configuration or updating questions please read the README and UPGRADE documentation,
or visit: https://gitter.im/PHP-CS-Fixer

When reporting an issue (bug) please provide the following information:

#### The PHP version you are using (`$ php -v`):
```
PHP 7.1.16 (cli) (built: Mar 31 2018 02:59:59) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
```

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
`PHP CS Fixer 2.12.2 Long Journey by Fabien Potencier and Dariusz Ruminski`

#### The command you use to run PHP CS Fixer:
`vendor/bin/php-cs-fixer fix`

#### The configuration file you are using, if any:
```php
<?php

$finder = PhpCsFixer\Finder::create()
    ->in('src')
    ->in('tests')
    ->exclude('Migrations')
;

return PhpCsFixer\Config::create()
    ->setRiskyAllowed(true)
    ->setRules([
        '@Symfony' => true,
        'ordered_imports' => true,
        'no_unused_imports' => true,
        'psr4' => true,
        'psr0' => true,
        'array_syntax' => ['syntax' => 'short'],
        'no_superfluous_phpdoc_tags' => true,
    ])
    ->setFinder($finder)
;
```

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):
 * before running PHP CS Fixer (no changes):
```php

     /**
      * @param array $columnSettings
      *
      * @return $this
      */
     public function setColumnSettings(array $columnSettings): self
```

 * with unexpected changes applied when running PHP CS Fixer:
```php

     /**
      * @return $this
      */
     public function setColumnSettings(array $columnSettings): self
```

 * with the changes you expected instead:
```php

     public function setColumnSettings(array $columnSettings): self
```

**If return type is self, `return $this` should be removed**

**Comment by julienfalque** [comment] 2018-07-19 07:04
I disagree, `@return self` and `@return $this` are different. The `self` keyword is an alias of the current class while `$this` means the method will return the object it is called on. Using `self` as return type doesn't prevent the method from returning a new instance instead (e.g. immutable objets).

**Comment by ntzm** [comment] 2018-07-19 07:04
`return $this` has a different meaning to `return self` though

**Comment by SpacePossum** [comment] 2018-07-30 11:42
so these could be fixed:

```php
<?php
class C {}

/**
 * @return self
 */
public function getC(): C {
    return new C();
}
```

```php
<?php
class C {}

/**
 * @return static
 */
public function getC(): C {
    return new C();
}
```

?

**Comment by OskarStark** [comment] 2019-02-17 12:59
I would say yes, this looks promising 👍🏻

**Comment by dmvdbrugge** [comment] 2019-02-25 21:47
I agree with @SpacePossum's `self` case, however not with the `static` one:
just as with @julienfalque's `$this` vs `self`, it's about intent, in this case regarding extension.

I think the typehint would've been `: static` had the language allowed it, thereby signalling that any child-classes should return the child-version.

One could question then if the typehint makes sense, but it's at least something. (Same as for example having `string[]` as docblock while also having `: array`.)

**Comment by Wirone** [comment] 2023-04-02 13:33
I'm going to close this because issue mentions Fixer version which is not maintained anymore. Feel free to reproduce it on latest version (if problem still exists) and create new issue.

**Closed by Wirone** 2023-04-02 13:33 UTC
Labels: kind/feature request
