### ISSUE TITLE
Data provider attribute must be recognized

### ISSUE THREAD

**Issue by mvorisek** [PHP-CS-Fixer/PHP-CS-Fixer#8227] opened 2024-09-29 16:22 UTC
### Feature request

Currently `DataProviderAnalyzer` does not recognize data provider usages using native attribute.

Once implemented, `php_unit_data_provider_name` should be improved to rename data provider methods in attributes as well.

/cc @kubawerlos as you are the author of these

**Comment by kubawerlos** [comment] 2024-09-29 18:21
Duplicate of https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/issues/7244

**Closed by kubawerlos** 2024-09-29 18:21 UTC
Labels: status/to verify, kind/feature request
