### ISSUE TITLE
Add empty last line even if risky

### ISSUE THREAD

**Issue by Yivan** [PHP-CS-Fixer/PHP-CS-Fixer#4815] opened 2020-02-14 14:09 UTC
Hello,

The last version of fixer at this day has this problem (v2.16.1 Yellow Bird).
In case of closed php with short notation and mixed content, empty last line is not added.

Exemple closed php tag:

```
<?php if (!empty($this->relations('brands_footer')) && !$this->relations('brands_footer')->isEmpty()) :?>

    <div class="fixed-content">
        ANY CONTENT
    </div>

<?php endif; ?> <= this is the last line of the file, no empty last line has been added below
```

Exemple mixed content, empty last line is not added too:
```
<?php if (!empty($this->relations('brands_footer')) && !$this->relations('brands_footer')->isEmpty()) :?>

    <div class="fixed-content">
        ANY CONTENT
    </div>

<?php endif; ?>
DUMMY TEXT  <= this is the last line of the file, no empty last line has been added below
```

Here is the ruleset:

```
    ->setRules([
        '@PhpCsFixer'                         => true,

        // one space when concatenation
        'concat_space' => ['spacing' => 'one'],

        // force class element order alphabetically
        'ordered_class_elements'              => ['sortAlgorithm' => 'alpha'],

        // if views are fixed better to activate those
        'no_alternative_syntax'               => false, // this one do the bug
        'no_short_echo_tag'                   => false,
    ])
```

Thanks.

**Comment by SpacePossum** [comment] 2020-02-14 16:30
Hi,

Looking at your report I think what is going on is by design. The rule does not add a extra line break at the end of the file when that would change the behavior of the code. In this case, adding a line after the close tag will change the behavior because it will be added to the output of the script, before it would not output that line.

**Comment by Yivan** [comment] 2020-02-14 17:56
But any linux file finish with a "lf". The moment with use "lf" as ending lines a last empty line should be mandatory whatever ?
If you open a file in vi/vim on linux it constently add this empty ending line. (more information on this principe here: https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline)

Maybe it is not to php-cs-fixer to handle this, but would be nice it handle it, so without relying on any tools we are sure to have clean respectfull standard format file.
Or maybe a new rule could be added, or as option for an existing rule.

In fact to be simple, running php-cs-fixer if we want it easy it should end with clean linux file format (if this is what the user has choose): "lf" on all each end lines of the files (no mix content), last empty line, no utf bom (you strip it already, but this one is more risky thant last empty line i find). Trailing empty space is a plus.

**Comment by Yivan** [comment] 2020-02-14 23:23
@SpacePossum I made further testing, and in fact PHP CS Fixer remove the last empty line if it was existing before run fix command : (
So there is really a problem as it alter the original file intent to have an empty line at the end. It not just keep as it.

Use case:
- a script add missing ending empty lines to conform linux norm
- running php cs fixer
- the empty last line has been removed

This happens on the code exemple I have submit in the fist post of this issue.
It breaks our CI system as we cannot no more enforce this ending empty line rule as php cs fixer alter it to a non-linux convention.

I change the title of this post to be more revelant.

Thanks

**Comment by SpacePossum** [comment] 2020-02-15 06:06
The reason is because it would change code behavior. For example, on my ubuntu linux type setup I have this file:

test.php

```php
<?php

?>123
```

run it
>$ php test.php

```
$ php test.php 
123

```

now lets add this "mandatory" new line add the end of the file:

test.php

```php
<?php

?>123\n
```

run it
>$ php test.php

```
$ php test.php 
123


```

The output changed because we change code behavior. Therefore we only add a newline at the end of file when it does not change code behavior.

All other points can be discussed in your other issues I think? For us it is more easy if issues are focused around one issue, like linefeed at the end of file, removing UTF bom, etc. and not all in one, thanks!

**Comment by Yivan** [comment] 2020-02-15 16:38
Yes other points (utf, bom,...) if needed i have already opened issues. Thanks.

I totally agree with you and it is better to preserve original code result, this is the **top priority rule**.

In your example, if you open in vi/vim/nano and just save and close, the last line will be added. So vi/vim/nano detroy the file... In fact the problem is in the file itself, it should have an ending line, and if the developper don't add one volontary it will have the mission to be very carefull of it's text editor.
For my use case, I use linux command to fix files before going into php cs fixer. Result code must no rely on this ending line to prevent further problem, so it is added forcibly at the start of the project and a rule to follow.
Finally i agree this is not the mission to php cs fixer to change the file and alter code result.
But as you can implement some "risky" rules, maybe this could be done at this level ?

So this issue can be close, except if you find that adding a rule as "risky" which will add this ending line would be a good thing!

Thanks.

**Comment by Wirone** [comment] 2023-04-05 16:47
Thank you for taking your time reporting this, but unfortunately I'm going to close this because it's related to Fixer version which is not maintained anymore (2.x). Feel free to reproduce it on latest version (3.x) and create new issue.

**Closed by Wirone** 2023-04-05 16:47 UTC
Labels: kind/feature request
