### ISSUE TITLE
`fully_qualified_strict_types` - conversion from `Foo\Bar::class` to `Bar::class` should not happen for imported function

### ISSUE THREAD

**Issue by keradus** [PHP-CS-Fixer/PHP-CS-Fixer#7652] opened 2024-01-01 12:42 UTC
```php
<?php

use function Symfony\Component\String\u;

echo Symfony\Component\String\u::class;
echo "\n";
echo u::class;
```

ref https://github.com/symfony/symfony/pull/53233#discussion_r1438916844

**Comment by Wirone** [comment] 2024-01-06 20:47
@mvorisek how about this one? Will #7679 fix this one too?

**Comment by mvorisek** [comment] 2024-01-06 23:01
This seems like a duplicate of #7460, this is not touch by my PR, but easy to fix after.

**Comment by keradus** [comment] 2024-01-07 17:28
I'm not sure if it's really a duplicate.

7460 wants to convert `\foo\bar();` into `bar();` (feature)
while this PR asks to prevent `\foo\bar::class` into `bar::class` conversion (bug)

**Comment by mvorisek** [comment] 2024-01-08 00:03
#7679 solves all classy bugs :)

**Comment by keradus** [comment] 2024-01-08 01:10
can you link a test case in your PR that covers `\myNs\myFunction::class` case described by this issue?

**Comment by Wirone** [comment] 2024-01-08 22:17
As I think about it, are we even able to distinguish imports for classes and functions if both can use `::class`? Currently we import only classy symbols found in several places. We can safely import functions from FQN-based function call, but for `::class` we actually don't know the context 😕. The [root cause](https://github.com/symfony/symfony/pull/53233#pullrequestreview-1799683375) of this issue shows this clearly...

**Comment by mvorisek** [comment] 2024-01-08 22:35
`u::class` is basically a refactorable string. It can refer class, it can refer namespace, ... I belive `::class` should be always imported as class or do you want to try to guess the context from the surrounding function usage?

**Comment by Wirone** [comment] 2024-01-08 23:28
I would rather avoid it, because with token-based logic it would be awfully hard probably. However, importing `::class` always as class makes this fixer somehow risky... 🤔. But if it's behind an opt-in flag, then we probably can add such information to the option instead of marking whole fixer as such. @keradus what do you think?

**Comment by keradus** [comment] 2024-01-09 22:06
I think you folks are wondering of "how to import such ::class usage with `use` import statement.

This issue is not about it.

This issue is to prevent this conversion:

# input
```
<?php

use function Symfony\Component\String\u;

echo Symfony\Component\String\u::class;
```

# expected output
no change

# actual output
```
<?php

use function Symfony\Component\String\u;

echo u::class;
```

**Comment by kbond** [comment] 2024-01-16 15:45
Not entirely sure if this is the same issue but feels similar.

For the following example: `HasView` is in the same namespace as `ViewFactory`

input:
```php
namespace App\Support\View;

use App\Support\View;

interface ViewFactory
{
    public function create(HasView $what): View;
}
```

expected output:
(no change)

actual output:
```diff
namespace App\Support\View;

use App\Support\View;

interface ViewFactory
{
-    public function create(HasView $what): View;
+   public function create(View\HasView $what): View;
}
```

**Closed** 2024-08-07 22:05 UTC
Labels: kind/bug, topic/fqcn
