### ISSUE TITLE
Declare after PHP Opening Tag

### ISSUE THREAD

**Issue by ktomk** [PHP-CS-Fixer/PHP-CS-Fixer#4252] opened 2019-01-10 10:36 UTC
Using 2.14 I'm looking for a fixer that takes care of moving the `declare(...)` statement right after the `<?php` opening tag (and one space in front).

```
<?php delcare(strict_types=1);
```
> (If there is a declare statement in the file, it's location is one space character after the opening PHP tag)

I imagined it would already exists so I was searching for it but after doing so my assumption grows it does not yet.

So I'd like to ask if there is anything like that in existence incl. preparation first of all, I see a lot of potential related issues as well so I can imagine this is perhaps a rule to apply PHP-CS-Fixer can not apply a working strategy across all rules, so any kind of feedback is welcome.

**Comment by apfelbox** [comment] 2019-02-09 13:11
I would love that as well.

So, the rule should not allow it for anything *except* `declare()`.

That is currently not possible:

* `true` -> `declare()` is in next line
* `false` -> anything else can be on the same line

**Comment by ktomk** [comment] 2019-02-10 09:18
Speaking of rules and which configuration they could (theoretically have), this is my own mental model representation:
~~~
'blank_line_after_opening_tag'                  => 'true_unless_declare_which_is_forced_in_first_line_with_single_space_if_in_use',
/* commented out by intention 'declare_strict_types'                          => true, */
~~~

Important part here is that `declare_strict_types` should be independent to this setting, I use strict types in some files, but in some other files I do not and this is not a per directory rule or so, but just differs between files.

**Comment by ktomk** [comment] 2019-11-03 21:01
@apfelbox You still have interest for this one? And re-reading your suggestion somehow looks pretty viable in a rule on it's own. If other declare related rules are done beforehand (as we can say there should be none), your suggestion should be non-conflicting and it's perhaps possible to implement it.

**Comment by a666** [comment] 2020-10-18 00:51
I don't know about @apfelbox but as someone who has to review the strictification of a PHP app I sure would enjoy standardizing the `declare` on these files.

**Comment by mvoelker** [comment] 2021-01-13 22:26
Is this (question / problem) still a thing?
Required the declare statement in a project with many (~6.000) existing files.
Had to play around with some parameters.

But in the end this setup did the job for me ... the declare statement on the first line.

```
$config = PhpCsFixer\Config::create()
    ->setRiskyAllowed(true)
    ->setUsingCache(false)
    ->setRules([
        '@Symfony' => true,
        '@PSR2' => true,
        '@PhpCsFixer' => true,

        'declare_strict_types' => true,
        'linebreak_after_opening_tag' => false,
        'blank_line_after_opening_tag' => false,
        ...
```

**Comment by a666** [comment] 2021-01-14 04:05
Those three last lines are those we use for enforcement.

They do solve the situation somewhat, but currently we have a lot of files with divergent declarations:

```php
<?php declare(strict_types=1);
```
```php
<?php
declare(strict_types=1);
```
or even
```php
<?php
declare(encoding='SJIS');
declare(strict_types=1);
```

**Comment by a-r-m-i-n** [comment] 2021-02-10 16:01
The problem is, that here it only ensures the existing line break (or not). It does not ensure, that there is no line break. So when you already have a line break here, it won't get removed. Probably this requires a new rule which ensures declare on same line as <?php opening tag.

**Comment by cavo789** [comment] 2021-12-01 20:10
Hello

If you still search for this rule, just found https://github.com/kubawerlos/php-cs-fixer-custom-fixers

Not tested..

**Comment by Arkemlar** [comment] 2022-11-29 11:08
Checked out, that works!

**Comment by keradus** [comment] 2023-03-31 19:48
Hey! I'm closing this as no traffic around anymore. The idea could be valid, yet it didn't get any movement around.
If any of you see a value in it and are ready to implement it, please draft mini-RFC what you would like to achieve and how.

**Closed by keradus** 2023-03-31 19:48 UTC
Labels: kind/feature request
