### ISSUE TITLE
declare_strict_types doesn't play nice with header docblocks

### ISSUE THREAD

**Issue by RentecTravis** [PHP-CS-Fixer/PHP-CS-Fixer#4455] opened 2019-06-26 20:46 UTC
This isn't quite the same as #2590

#### The PHP version you are using (`$ php -v`):
=> 7.3.6

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
=> 2.15.1 Europe Round

#### The command you use to run PHP CS Fixer:
=> ./vendor/bin/php-cs-fixer fix ...

#### The configuration file you are using, if any:
```php
<?php
/**
 * @file Configure PhpCsFixer with our custom settings
 *
 * @see https://mlocati.github.io/php-cs-fixer-configurator/#version:2.15
 */

declare(strict_types=1);

$finder = PhpCsFixer\Finder::create()
    ->in(__DIR__)
    ->exclude(['var', 'legacy', 'node_modules', 'bin'])
;

return PhpCsFixer\Config::create()
    ->setRiskyAllowed(true)
    ->setRules(['declare_strict_types' => true])
    ->setFinder($finder)
;
```

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):
 * before running PHP CS Fixer (no changes):
```php
<?php
/**
 * @author Example Name <example@example.com>
 */

namespace App\Bundle\AppBundle;

use Symfony\Component\HttpKernel\Bundle\Bundle;

class AppBundle extends Bundle
{
}
```

 * with unexpected changes applied when running PHP CS Fixer:
```php
<?php declare(strict_types=1);
/**
 * @author Example Name <example@example.com>
 */

namespace App\Bundle\AppBundle;

use Symfony\Component\HttpKernel\Bundle\Bundle;

class AppBundle extends Bundle
{
}
```

 * with the changes you expected instead:
```php
<?php
/**
 * @author Example Name <example@example.com>
 */

declare(strict_types=1);

namespace App\Bundle\AppBundle;

use Symfony\Component\HttpKernel\Bundle\Bundle;

class AppBundle extends Bundle
{
}

```

**Comment by SpacePossum** [comment] 2019-10-09 10:49
Hi and thanks for the report,

Can you share the configuration you use for the `header_comment` rule? Configuring it like `'location' => 'after_open'` should already do this for you.

For details you can run:

>$ php-cs-fixer describe header_comment

**Comment by tvanc** [comment] 2019-10-09 15:52
Hola, thanks for the response. I tried `location => after_open` and unfortunately I still get unexpected behavior.

**Configuration file**
```php
$finder = PhpCsFixer\Finder::create()
    ->in(__DIR__)
    ->exclude(['var', 'legacy', 'node_modules', 'bin'])
;

return PhpCsFixer\Config::create()
    ->setRiskyAllowed(true)
    ->setRules([
        'declare_strict_types' => true,
        'header_comment' => [
            'location' => 'after_open',
            'comment_type' => 'PHPDoc',
            'separate' => 'bottom',
            'header' => '@author Example Name <example@example.com>',
        ],
    ])
    ->setFinder($finder);
```

**Before running PHP CS Fixer**
```php
<?php
/**
 * @author Example Name <example@example.com>
 */

namespace App\Bundle\AppBundle;

use Symfony\Component\HttpKernel\Bundle\Bundle;

class AppBundle extends Bundle
{
}
```

**After running PHP CS Fixer**
```php
<?php
/**
 * @author Example Name <example@example.com>
 */

declare(strict_types=1);
/**
 * @author Example Name <example@example.com>
 */

namespace App\Bundle\AppBundle;

use Symfony\Component\HttpKernel\Bundle\Bundle;

class AppBundle extends Bundle
{
}
```

**Expected changes**
```php
<?php
/**
 * @author Example Name <example@example.com>
 */

declare(strict_types=1);

namespace App\Bundle\AppBundle;

use Symfony\Component\HttpKernel\Bundle\Bundle;

class AppBundle extends Bundle
{
}
```

**Comment by SpacePossum** [comment] 2019-10-09 18:03
Hi sorry that didn't help. Looking at your case, the issue is the declare strict being inserted directly after the open token (`<?php `) and when that is done the header gets inserted after the open token and thus before the declare statement.  Currently I don't see a fix for this through configuration, I think we indeed not to patch the code... not sure how but yeah.. : |

**Comment by Wirone** [comment] 2023-04-06 08:08
Thank you for taking your time to report this, but unfortunately I'm going to close it since it refers to Fixer's version (2.x) which is not maintained anymore. Feel free to reproduce it on a latest version (3.x) and create new issue if problem still exists 🙂.

**Closed by Wirone** 2023-04-06 08:08 UTC
Labels: kind/bug
