### ISSUE TITLE
Enforce spaces inside parenthesis

### ISSUE THREAD

**Issue by mclaurent** [PHP-CS-Fixer/PHP-CS-Fixer#3855] opened 2018-07-03 09:33 UTC
I am trying to get PHP-CS-Fixer to enforce spaces inside parenthesis. I have found the fixer "no_spaces_inside_parenthesis" which, when enabled, will strip spaces inside parenthesis. But disabling this fixer does not enforce spaces inside parenthesis. This behaviour seems correct and expected to me, but I am not seeing a way to achieve my goal in any other way. Do you know if it is possible to make PHP-CS-Fixer enforce spaces inside parenthesis?

When reporting an issue (bug) please provide the following information:

#### The PHP version you are using (`$ php -v`):
=>
`PHP 7.1.15 (cli) (built: Mar  1 2018 01:51:52) ( ZTS MSVC14 (Visual C++ 2015) x64 )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
    with Xdebug v2.6.0, Copyright (c) 2002-2018, by Derick Rethans`

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
`PHP CS Fixer 2.12.1 Long Journey by Fabien Potencier and Dariusz Ruminski`

#### The command you use to run PHP CS Fixer:
`php-cs-fixer fix  .\website --verbose --config=config.php_cs`

#### The configuration file you are using, if any:
```php
<?php

$finder = PhpCsFixer\Finder::create()
    ->exclude('vendor')
    ->in(__DIR__)
;

return PhpCsFixer\Config::create()
    ->setIndent("\t")
    ->setLineEnding("\r\n")
    ->setRules([
        '@Symfony' => true,
		'array_syntax' => ['syntax' => 'long'],
		'blank_line_after_namespace' => true,
		'blank_line_after_opening_tag' => true,
		'blank_line_before_return' => false,
		'blank_line_before_statement' => false,
		'function_declaration' => ['closure_function_spacing' => 'one'],
		'braces' => [
			'allow_single_line_closure' => true,
			'position_after_anonymous_constructs' => 'same',
			'position_after_control_structures' => 'same',
			'position_after_functions_and_oop_constructs' => 'same'
		],
		'full_opening_tag' => true,
		'no_closing_tag' => true,
		'no_trailing_whitespace_in_comment' => false,
		'whitespace_after_comma_in_array' => true,
		'no_spaces_inside_parenthesis' => false,
		'phpdoc_no_package' => false,
		'method_argument_space' => true,
		'no_spaces_around_offset' => ['outside'],
		'concat_space' => [ 'spacing' => 'one' ],
		'no_spaces_after_function_name' => false,
		'general_phpdoc_annotation_remove' => false,
		'include' => true,
		'array_indentation' => true,
		'trim_array_spaces' => false,
		'cast_spaces' => ['space' => 'single']
    ])
    ->setFinder($finder)
;

```

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):
 * before running PHP CS Fixer (no changes):
```php
explode($a, $b);
```

 * with unexpected changes applied when running PHP CS Fixer:
```php
explode($a, $b);
```

 * with the changes you expected instead:
```php
explode( $a, $b );
```

**Comment by keradus** [comment] 2018-07-03 09:37
Hi there !

Is this an established standard? Like, is there a community that's follow it ?

**Comment by mclblock** [comment] 2018-07-03 09:49
Hi

Yes, the WordPress community is following it (although their core code base is not 100% following it at this point)
https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/#space-usage

**Comment by kkmuffme** [comment] 2018-12-08 22:32
This feature would be greatly appreciated since WordPress is among the biggest ecosystems out there, so it would be really, really useful for a lot of people.

**Comment by newRahulVerma** [comment] 2018-12-22 10:30
In addition to `no_spaces_inside_parenthesis`, when `trim_array_spaces` is set to `false` PHP CS Fixer should add space inside parentheses/square brackets. People can use `null` if they want to ignore the rule.

**Comment by tareq1988** [comment] 2019-07-04 14:22
👍 for this request.

**Comment by ipromz** [comment] 2020-02-21 07:30
This is the only thing that's preventing me from using PHP-CS-Fixer.

**Comment by abTec** [comment] 2020-05-30 10:09
yep, there are 455,000,000 self hosted webs running WP out there. You definitely should to add `spaces_inside_parenthesis_style` config to CS Fixer 💯

**Comment by kubawerlos** [comment] 2020-05-30 16:52
> You definitely should

@abTec who exactly do you mean that definitely should? Do not forget that this tool is driven by the community and made in the free time of people.

If you want that fixer to be done please simply consider helping to create it ([guide](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/1.7/COOKBOOK-FIXERS.md)).

**Comment by Wirone** [comment] 2023-04-02 13:39
I'm going to close this because issue mentions Fixer version which is not maintained anymore. Feel free to reproduce it on latest version (if problem still exists) and create new issue.

**Closed by Wirone** 2023-04-02 13:39 UTC
Labels: kind/feature request
