### ISSUE TITLE
doctrine_annotation_indentation issue

### ISSUE THREAD

**Issue by MatTheCat** [PHP-CS-Fixer/PHP-CS-Fixer#5146] opened 2020-09-15 09:39 UTC
## Bug report

- PHP version: 7.2.32
- PHP CS Fixer version: 2.16.4
- Command used to run PHP CS Fixer: `php-cs-fixer fix --allow-risky=yes`
- Configuration file:

```php
<?php

return PhpCsFixer\Config::create()
    ->setFinder(PhpCsFixer\Finder::create()->in(['libraries/*/src', 'applications/*/src', 'applications/*/tests']))
    ->setRules([
        '@DoctrineAnnotation' => true,
        '@Symfony' => true,
        '@PHP70Migration' => true,
        '@PHP71Migration' => true,
        'array_syntax' => ['syntax' => 'short'],
        'concat_space' => ['spacing' => 'one'],
        'declare_strict_types' => true,
        'linebreak_after_opening_tag' => true,
        'no_superfluous_phpdoc_tags' => [
            'allow_mixed' => false,
            'allow_unused_params' => false,
            'remove_inheritdoc' => true,
        ],
        'phpdoc_order' => true,
        'phpdoc_summary' => false,
        'single_line_throw' => false,
        'yoda_style' => false,
    ])
;
```

### Code snippet that reproduces the problem

```php
<?php

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Table(uniqueConstraints={
 *     @ORM\UniqueConstraint(name="index", columns={
 *     "first",
 *     "second"
 * })})
 * @ORM\Entity
 */
class SomeClass
{
}
```

Once run, this class is fixed as

```php
<?php

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Table(uniqueConstraints={
 *     @ORM\UniqueConstraint(name="index", columns={
 *         "first",
 *         "second"
 *     })})
 *     @ORM\Entity
 */
class SomeClass
{
}
```

I guess it should be

```php
<?php

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Table(uniqueConstraints={
 *     @ORM\UniqueConstraint(name="index", columns={
 *         "first",
 *         "second"
 *     })
 * })
 * @ORM\Entity
 */
class SomeClass
{
}
```

**Comment by Wirone** [comment] 2023-05-10 22:24
Reproduced with `3.16`:

<img width="897" alt="image" src="https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/assets/600668/a9fbccee-ccb8-4b1e-94ce-e27850c189db">

**Comment by Wirone** [comment] 2023-11-08 12:41
FYI: if you break `})})` into 2 `})`, then it's formatted properly:

![image](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/assets/600668/46c8efcc-8aa3-484c-9d57-f4bf520b3083)

The problem here is that `doctrine_annotation_indentation` does not check the syntax and don't enforce proper new lines, it's only indenting existing code. I'll close this now, as it looks like it's rather feature request for something more sophisticated and I'm not sure if it makes sense to invest time in it at this point, because PHP language and community are leaning towards native attributes.

If anyone is interested in providing fix for this, it would be welcomed anyway.

**Closed by Wirone** 2023-11-08 12:41 UTC
Labels: kind/bug, kind/enhancement, topic/annotation, contribution welcome
