### ISSUE TITLE
array multiline indentation issue

### ISSUE THREAD

**Issue by asuri0n** [PHP-CS-Fixer/PHP-CS-Fixer#4409] opened 2019-05-09 10:00 UTC
For configuration or updating questions please read the README and UPGRADE documentation,
or visit: https://gitter.im/PHP-CS-Fixer

When reporting an issue (bug) please provide the following information:

#### The PHP version you are using (`$ php -v`):
=> 7.3.1

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
=> 2.15

#### The command you use to run PHP CS Fixer:
=> ${PHP_CS_FIXER} fix --config=.php_cs.dist --verbose "$line";

#### The configuration file you are using, if any:
```php
'@Symfony' => true,
'align_multiline_comment' => ['comment_type' => 'all_multiline'],
'array_indentation' => true,
'array_syntax' => ['syntax' => 'short'],
'backtick_to_shell_exec' => true,
'braces' => true,
'indentation_type' => true,
'method_chaining_indentation' => true,
```

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):
 * before running PHP CS Fixer (no changes):
```php
$post_data = http_build_query(
  [
    'secret' => '6L***********************eFQ41',
    'response' => $request->get('g-recaptcha-response'),
    'remoteip' => $_SERVER['REMOTE_ADDR'],
  ]
);
```

 * with unexpected changes applied when running PHP CS Fixer:
```php
  $post_data = http_build_query(
[
  'secret' => '6L***********************eFQ41',
  'response' => $request->get('g-recaptcha-response'),
  'remoteip' => $_SERVER['REMOTE_ADDR'],
]
);
```

 * with the changes you expected instead:
```php
$post_data = http_build_query(
  [
    'secret'      => '6L***********************eFQ41',
    'response' => $request->get('g-recaptcha-response'),
    'remoteip' => $_SERVER['REMOTE_ADDR'],
  ]
);
```

Hello,
I have this unexpected changes.
I was expected good indentation for `(` and `[` and for `=>` too`

thank you

**Comment by julienfalque** [comment] 2019-05-09 11:45
I'm not able to reproduce the issue you reported. Is it possible for you to provide the whole PHP file? Maybe that would help.

Note: I edited your message to modify the `secret` key in the first snippet but the initial version is still available so if this is an actual secret, I suggest you change it.

**Comment by asuri0n** [comment] 2019-05-09 12:08
Here is the file : 
```php
<?php

$finder = PhpCsFixer\Finder::create()
  ->in(__DIR__)
  ->exclude('config')
  ->exclude('var')
  ->exclude('web')
  ->exclude('bin')
  ->exclude('node_modules')
;

return PhpCsFixer\Config::create()
  ->setRiskyAllowed(true)
  ->setRules([
    '@Symfony' => true,
    'align_multiline_comment' => ['comment_type' => 'all_multiline'],
    'array_indentation' => true,
    'array_syntax' => ['syntax' => 'short'],
    'backtick_to_shell_exec' => true,
    'braces' => true,
    'indentation_type' => true,
    'method_chaining_indentation' => true,
  ])
  ->setFinder($finder)
  ->setIndent("\t")
  ;
```

Yes i've already change the key, stupid mistake ...

**Comment by asuri0n** [comment] 2019-05-09 12:17
With that code too : 

```
$this->addFlash(
  'success',
  'Compte supprimé.'
);

```
render

```
				$this->addFlash(
  'success',
  'Compte supprimé.'
);
```

**Comment by kubawerlos** [comment] 2019-05-31 18:11
Would https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/4183 fix your problem?

**Comment by richex-cn** [comment] 2019-06-15 12:16
```
> php-cs-fixer -V
PHP CS Fixer 2.15.1 Europe Round by Fabien Potencier and Dariusz Ruminski
```

I had the same problem at VSCode just now, PHP version 7.3.5.

Before:
```
    public function getList()
    {
        
$test = [
'property' => 123
];

$test = array_merge($test, [
'a' => 1
]);
}
```

After:
```
    public function getList()
    {
        $test = [
'property' => 123
];

        $test = array_merge($test, [
'a' => 1
]);
    }
```

**Comment by whereisaaron** [comment] 2019-06-24 04:31
I am getting the same thing using the 'php cs fixer' module in VS Code. All `array( ... )` and `[ ... ]` that go over multiple lines are being incorrectly formatted like the other examples above.

Also function calls where the arguments stretch over more than one line have the closing parentheses indented incorrectly. They creep too, every time you apply `php cs fixer` they move two spaces further to the left, until the are indented one space in from the outer function declaration.

```
.\php-cs-fixer.phar -V
PHP CS Fixer 2.15.1 Europe Round by Fabien Potencier and Dariusz Ruminski (2006451)
```

This version is creating quite a mess!!

**Comment by whereisaaron** [comment] 2019-06-24 04:57
Well this is very strange. I think I stumbling onto a workaround. Previously I was using a default install of `php cs fixer` extension for VS Code and get this bug.

Then I creates a `.php_cs.dist` file as below, and suddenly the array formatting is working and no longer creeping left. Did I effectively disable the rule causing the problem by doing this?

```
<?php

return PhpCsFixer\Config::create()
  ->setRules([
    '@PSR2' => true,
    '@PhpCsFixer' => true
  ])
  ->setIndent("  ");
```

**Comment by SpacePossum** [comment] 2019-07-05 09:26
Hi,

There are a few issues reported in the same issue;

@richex-cn  what you see is the result of indenting based on the method, it is not related to the array rule.

@weareoutman great to hear you got the issue resolved, it is hard to say what is happening at times when plugins are used as we don't know the version of the tool that was used and with what configuration.

@asuri0n can you check the PR proposed by @kubawerlos ?

**Comment by richex-cn** [comment] 2019-07-12 09:08
> Hi,
> 
> There are a few issues reported in the same issue;
> 
> @richex-cn what you see is the result of indenting based on the method, it is not related to the array rule.
> 
> @weareoutman great to hear you got the issue resolved, it is hard to say what is happening at times when plugins are used as we don't know the version of the tool that was used and with what configuration.
> 
> @asuri0n can you check the PR proposed by @kubawerlos ?

hi,I want to know how should I do can complete the indenting which was below my question.

Before:
```
<?php
namespace app;

class Demo
{
public function say()
{
$arr = [
'a',
'b',
];

return $arr;
}
}
```

After:
```
<?php
namespace app;

class Demo
{
    public function say()
    {
        $arr = [
            'a',
            'b',
        ];

        return $arr;
    }
}
```

**Comment by SpacePossum** [comment] 2019-10-10 07:52
Hi @richex-cn 

Using the following rules:

```
[
       'blank_line_after_opening_tag' => true,
       'braces' => true,
       'array_indentation' => true,
]
```

the code gets fixed to:

```php
<?php

namespace app;

class Demo
{
    public function say()
    {
        $arr = [
            'a',
            'b',
        ];

        return $arr;
    }
}

```

**Comment by asuri0n** [comment] 2020-02-10 14:42
Always same problem :/  (v2.16.1)
Like for switch case : 


![image](https://user-images.githubusercontent.com/15729117/74159107-7d67bd00-4c1b-11ea-9847-c14f91e896b1.png)

with the folowing rules : 
```
[
         '@PSR2' => true,
        'braces' => true,
	'array_indentation' => true,
	'indentation_type' => true,
	'@PhpCsFixer' => true,
]
```

**Closed** 2023-01-22 17:59 UTC

**Comment by sovetski** [comment] 2023-01-25 13:46
Hi @asuri0n, did you find a solution? If yes, what is it?

**Comment by asuri0n** [comment] 2023-01-25 15:15
Wow, that was a long time ago. Here is our rules and we don't have this problem anymore.
```
        '@PHP81Migration' => true,
        '@PHP80Migration:risky' => true,
        '@PHPUnit84Migration:risky' => true,
        '@Symfony' => true,
        '@Symfony:risky' => true,
        'use_arrow_functions' => false, // Désactivé, car fait des lignes trop longues.
        'ordered_imports' => true,
        'no_unused_imports' => true,
        'declare_strict_types' => true,
        'final_class' => true,
```
