### ISSUE TITLE
Incompete "Multiple access type modifier" Error Message

### ISSUE THREAD

**Issue by dakanji** [PHP-CS-Fixer/PHP-CS-Fixer#3938] opened 2018-07-22 15:35 UTC
Running "Find & Replace" on a project file set had left me with one file with some instances of:

```
protected public static function xyz () {
...
}
```

Running phpcsfixer on the project resulted in a rather unhelpful **"PHP Fatal error:  Multiple access type modifiers are not allowed in  on line 1444"** error message.

An indication of which file, of about 3k files, that Line 1444 was located in would have been nice!

**Comment by dakanji** [comment] 2018-07-22 17:55
I edited the files outside phpcsfixer by finding and replacing a string. THIS is not the issue with phpcsfixer and was just background information. 

Issue what when one has some thing like ...

```
protected public static function xyz () {
...
}
```

... hidden in one file among a few thousand files, phpcsfixer simply throws an error message saying **"PHP Fatal error:  Multiple access type modifiers are not allowed in  on line 1234"**

So now I know that there is an issue on Line xyz but line xyz of which file? That's the issue.

==============
TEMPLATE FILLED BELOW
==============

#### The PHP version you are using (`$ php -v`):
=> PHP 7.1.1

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
=> PHP CS Fixer 2.12.1 Long Journey

#### The command you use to run PHP CS Fixer:
=> php php-cs-fixer fix --config /server/path/to/.php_cs.dist

#### The configuration file you are using, if any:
```php
=> ....................................
```

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):
 * before running PHP CS Fixer (no changes):
```php
protected public static function xyz () {
...
}
```

 * with unexpected changes applied when running PHP CS Fixer:
```php
=> PHP Fatal error:  Multiple access type modifiers are not allowed in  on line 1234
// Note empty space between "in" and "on". 
// File name should go there but missing
```

 * with the changes you expected instead:
```php
=> PHP Fatal error:  Multiple access type modifiers are not allowed in **/path/to/file/abcd.ext** on line 1234
```

**Comment by keradus** [comment] 2018-07-22 21:46
ha, now I got your request.

PHP CS Fixer is able (by purpose) to fix only valid PHP files, the message comes from linting process. I agree, having path to failing file would be nice indeed :+1:

**Comment by Wirone** [comment] 2023-04-02 13:32
I'm going to close this because issue mentions Fixer version which is not maintained anymore. Feel free to reproduce it on latest version (if problem still exists) and create new issue.

**Closed by Wirone** 2023-04-02 13:32 UTC
Labels: kind/enhancement
