### ISSUE TITLE
Closing Parenthesis Alignment for no_spaces_inside_parenthesis rule

### ISSUE THREAD

**Issue by Billz95** [PHP-CS-Fixer/PHP-CS-Fixer#4278] opened 2019-01-24 14:02 UTC
For configuration or updating questions please read the README and UPGRADE documentation,
or visit: https://gitter.im/PHP-CS-Fixer

When reporting an issue (bug) please provide the following information:

#### The PHP version you are using (`$ php -v`):
=> PHP 7.1.19

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
=> PHP CS Fixer 2.14.0 Sunrise

#### The command you use to run PHP CS Fixer:
=> vendor/bin/php-cs-fixer fix --diff  --dry-run  to-fix.php

#### The configuration file you are using, if any:
```php
<?php

return PhpCsFixer\Config::create()
    ->setRules([
        'no_spaces_inside_parenthesis' => true,
    ]);
```

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):
 * before running PHP CS Fixer (no changes):
```php
if ($superLongCondition && 
     $foo && $bar
             ) {
    // do Something
}
```

 * with unexpected changes applied when running PHP CS Fixer:
NO CHANGE
```php
if ($superLongCondition && 
     $foo && $bar
             ) {
    // do Something
}
```

 * with the changes you expected instead:
Either 
```php
if ($superLongCondition && 
     $foo && $bar
) {
    // do Something
}
```
Or
```php
if ($superLongCondition && 
     $foo && $bar) {
    // do Something
}
```

**Comment by Billz95** [comment] 2019-01-24 14:08
I'm expecting `no_spaces_inside_parenthesis` to either fix the closing bracket to the correct indentation level, or simply move up to go to the same line as the last argument.

To implement this latter approach (move up to the same line as the last argument), I guess we can apply the following diff to `NoSpacesInsideParenthesisFixer`:
```diff
@@ -102,7 +102,7 @@ function foo( \$bar, \$baz )
     {
         $token = $tokens[$index];
 
-        if ($token->isWhitespace() && false === strpos($token->getContent(), "\n")) {
+        if ($token->isWhitespace()) {
             $tokens->clearAt($index);
         }
     }
```

**Comment by Billz95** [comment] 2019-01-24 14:15
You may ask how would someone put the closing braces for control structure to a new line.
Well, a few `is_set` conditions were on the different lines, and when they are combined by `combine_consecutive_issets` rule, what left is bunch of newlines..

**configuration**
```php
<?php

return PhpCsFixer\Config::create()
    ->setRules([
        'combine_consecutive_issets' => true,
        'no_spaces_inside_parenthesis' => true,
    ]);
```
**Original Code**
```php
<?php

if (true && false &&
    isset($a) &&
    isset($b) &&
    isset($c) &&
    isset($d)) {
    echo 'fun';
}
```
**"Fixed" Code**
```php
<?php

if (true && false &&
    isset($a, $b, $c, $d) 
     
     
    ) {
    echo 'fun';
}
```

**Comment by Wirone** [comment] 2023-04-06 08:06
Thank you for taking your time to report this, but unfortunately I'm going to close it since it refers to Fixer's version (2.x) which is not maintained anymore. Feel free to reproduce it on a latest version (3.x) and create new issue if problem still exists 🙂.

**Closed by Wirone** 2023-04-06 08:06 UTC
