### ISSUE TITLE
statement_indentation fixer got unexpected reuslts in if-else block

### ISSUE THREAD

**Issue by nilyang** [PHP-CS-Fixer/PHP-CS-Fixer#6947] opened 2023-05-10 03:42 UTC
## Bug report

I have the code 

```
if ($case) { 
    // comment1 here
    func1();
    // comment2here
} else {
    // comment3 here
    func2();
    // comment4 here
}
```

then the `php-cs-fixer` format result is 
```
if ($case) {
    // comment1 here
    func1();
// comment2here
} else {
    // comment3 here
    func2();
    // comment4 here
}



```

The `comment4 ` indent is unexpected!

### Runtime version

```
# ./vendor/bin/php-cs-fixer -V
PHP CS Fixer 3.16.0 BoY42 by Fabien Potencier and Dariusz Ruminski.
PHP runtime: 8.1.6
```

### Configuration file

```
[
        '@PHP74Migration'                        => true,
        // '@PhpCsFixer'                            => true,
        // '@PhpCsFixer:risky'                      => true,
        '@Symfony'                               => true, // PSR12，@PhpCsFixer
        'general_phpdoc_annotation_remove'       => ['annotations' => ['expectedDeprecation']], // one should use PHPUnit built-in method instead
        // 'header_comment'                   => ['header' => $header], // 
        'heredoc_indentation'                    => false, // TODO switch on when # of PR's is lower
        'modernize_strpos'                       => false, // needs PHP 8+ or polyfill
        'use_arrow_functions'                    => false, // 
        'declare_strict_types'                   => false, // declare(strict_types=1)
        'method_argument_space'                  => ['after_heredoc' => true],
        'no_superfluous_phpdoc_tags'             => false, // 
        'binary_operator_spaces'                 => [
            'operators' => [
                '=>' => 'align_single_space',
            ],
        ], // 
        'array_indentation'                      => true,
        'phpdoc_summary'                         => false, // 
        'multiline_whitespace_before_semicolons' => ['strategy' => 'no_multi_line'], //
        'no_leading_namespace_whitespace'        => true, // 
        'no_null_property_initialization'        => false, //
        'psr_autoloading'                        => false, // （Risky
        'random_api_migration'                   => [
            'replacements' => [
                'getrandmax' => 'mt_getrandmax',
                'rand'       => 'mt_rand',
                'srand'      => 'mt_srand',
            ],
        ], // （Risky）
        'no_superfluous_elseif'                  => false, // @PhpCsFixer
        'concat_space'                           => ['spacing' => 'one'], // @Symfony 
        'single_line_throw'                      => false, // @Symfony
        'types_spaces'                           => ['space' => 'single', 'space_multiple_catch' => 'single'], // @Symfony
        'unary_operator_spaces'                  => true, // @Symfony
        'ordered_imports'                        => [
            'imports_order'  => [
                'class',
                'function',
                'const',
            ],
            'sort_algorithm' => 'alpha',
        ], // @PSR12 
        'global_namespace_import'                => [
            'import_classes'   => true,
            'import_constants' => true,
            'import_functions' => true,
        ], // @symfony @PhpCsFixer
    ]
```

**Comment by Wirone** [comment] 2023-05-10 05:28
Duplicate of #6891, already fixed in master, but not released yet.

**Closed by Wirone** 2023-05-10 05:28 UTC
Labels: kind/bug
