### ISSUE TITLE
File takes multiple executions of fix to be fixed

### ISSUE THREAD

**Issue by ben-i2x** [PHP-CS-Fixer/PHP-CS-Fixer#6114] opened 2021-11-16 14:36 UTC
## Bug report

I'm running PHP CS Fixer 3.3.2 Trinacria on an existing source tree and was surprised that a number of files require multiple executions of 'php-cs-fixer fix' before they are, in fact, fixed.

I didn't notice this at first because the cache file made it so that local attempts to run php-cs-fixer repeatedly didn't attempt to fix a recently fixed file. However, when another developer checked out the code and ran php-cs-fixer against code code I'd just fixed and committed, they found that files had changed.

I've tried this with php 7.3.29 and an 8.x version with the same results.

Here is the config file we're using:

```php
<?php
$finder = PhpCsFixer\Finder::create()
                           ->in(__DIR__);

$config = new PhpCsFixer\Config();
return $config->setIndent(str_pad('', 2))
              ->setRiskyAllowed(true)
              ->setRules([
                '@PSR2' => true,
                'braces' => [
                  'position_after_functions_and_oop_constructs' => 'same'
                ],
                'switch_case_space' => true,
                'elseif' => true,
                'echo_tag_syntax' => ['format' => 'short'],
                'full_opening_tag' => false,
                'no_whitespace_in_blank_line' => true,
                'non_printable_character' => [
                  'use_escape_sequences_in_strings' => true
                ]
              ])->setFinder($finder);

```
 

### Code snippet that reproduces the problem

Consider this php file:

```php
<?php
/*
 * A PHP file for testing PHP-CS-Fixer
 */
?>

<div class='grid_6 leading table-100'>
<h2>Section A </h2>
<?= render_it($data,
    $cols,
    array_merge($keys, A("render_options")),
    "Not Found"); ?>
</div>


<div class='grid_6 leading table-100'>
<h2>Section B</h2>
<?= render_it($data,    $cols,
    array_merge($keys, A("render_options")),
    "Not Found"); ?>
</div>

<div class='grid_6 leading table-100'>
<h2>Section C</h2>
<?= render_it($data,   $cols,    array_merge($keys, A("render_options")),
    "Not Found"); ?>
</div>
```

Now, consider this transcript as I run php fixer against it:

```
$ for i in $(seq 1 5) ; do ./tools/php-cs-fixer/vendor/bin/php-cs-fixer fix --using-cache=no --diff src/example.php | grep -v ^$ |grep -v "Fixed all" > diff.$i ; done
Loaded config default from "/Users/ben/Downloads/php-cs-fixer-test-case/.php-cs-fixer.dist.php".
Paths from configuration file have been overridden by paths provided as command arguments.
Loaded config default from "/Users/ben/Downloads/php-cs-fixer-test-case/.php-cs-fixer.dist.php".
Paths from configuration file have been overridden by paths provided as command arguments.
Loaded config default from "/Users/ben/Downloads/php-cs-fixer-test-case/.php-cs-fixer.dist.php".
Paths from configuration file have been overridden by paths provided as command arguments.
Loaded config default from "/Users/ben/Downloads/php-cs-fixer-test-case/.php-cs-fixer.dist.php".
Paths from configuration file have been overridden by paths provided as command arguments.
Loaded config default from "/Users/ben/Downloads/php-cs-fixer-test-case/.php-cs-fixer.dist.php".
Paths from configuration file have been overridden by paths provided as command arguments.
$ wc -l diff.*
      56 diff.1
      22 diff.2
      20 diff.3
       0 diff.4
       0 diff.5
      98 total
```

Notice how the first three times the command runs, differences are generated. For the last two runs, no code is changed.

The files in the source tree are fixed with varying degrees of runs. Some are fixed in two passes, others may require five. This depends on the code of the file.

Here's what changed on each run:

```diff
Diff: 1
   1) php-cs-fixer-test-case/src/example.php
      ---------- begin diff ----------
--- /Users/ben/Downloads/php-cs-fixer-test-case/src/example.php
+++ /Users/ben/Downloads/php-cs-fixer-test-case/src/example.php
@@ -1,27 +1,36 @@
-<?php
-/*
- * A PHP file for testing PHP-CS-Fixer
- */
-?>
+<?php
+/*
+ * A PHP file for testing PHP-CS-Fixer
+ */
+?>
 
 <div class='grid_6 leading table-100'>
 <h2>Section A </h2>
-<?= render_it($data,
-    $cols,
-    array_merge($keys, A("render_options")),
-    "Not Found"); ?>
+<?= render_it(
+  $data,
+  $cols,
+  array_merge($keys, A("render_options")),
+  "Not Found"
+); ?>
 </div>
 
 
 <div class='grid_6 leading table-100'>
 <h2>Section B</h2>
-<?= render_it($data,    $cols,
-    array_merge($keys, A("render_options")),
-    "Not Found"); ?>
+<?= render_it(
+      $data,
+      $cols,
+      array_merge($keys, A("render_options")),
+      "Not Found"
+    ); ?>
 </div>
 
 <div class='grid_6 leading table-100'>
 <h2>Section C</h2>
-<?= render_it($data,   $cols,    array_merge($keys, A("render_options")),
-    "Not Found"); ?>
+<?= render_it(
+      $data,
+      $cols,
+      array_merge($keys, A("render_options")),
+      "Not Found"
+    ); ?>
 </div>
      ----------- end diff -----------

Diff: 2
   1) php-cs-fixer-test-case/src/example.php
      ---------- begin diff ----------
--- /Users/ben/Downloads/php-cs-fixer-test-case/src/example.php
+++ /Users/ben/Downloads/php-cs-fixer-test-case/src/example.php
@@ -18,11 +18,11 @@
 <div class='grid_6 leading table-100'>
 <h2>Section B</h2>
 <?= render_it(
-      $data,
-      $cols,
-      array_merge($keys, A("render_options")),
-      "Not Found"
-    ); ?>
+  $data,
+  $cols,
+  array_merge($keys, A("render_options")),
+  "Not Found"
+); ?>
 </div>
 
 <div class='grid_6 leading table-100'>
      ----------- end diff -----------

Diff: 3
   1) php-cs-fixer-test-case/src/example.php
      ---------- begin diff ----------
--- /Users/ben/Downloads/php-cs-fixer-test-case/src/example.php
+++ /Users/ben/Downloads/php-cs-fixer-test-case/src/example.php
@@ -28,9 +28,9 @@
 <div class='grid_6 leading table-100'>
 <h2>Section C</h2>
 <?= render_it(
-      $data,
-      $cols,
-      array_merge($keys, A("render_options")),
-      "Not Found"
-    ); ?>
+  $data,
+  $cols,
+  array_merge($keys, A("render_options")),
+  "Not Found"
+); ?>
 </div>
      ----------- end diff -----------

Diff: 4

Diff: 5

```

One of my team members noticed that if we add:

```php
                'method_argument_space' => [
                  'on_multiline' => 'ignore'
                ],
```

to the config file, this issue goes away. However, leaves the code untouched and we'd like this code properly format.

Any suggestions for how to proceed?

**Comment by SpacePossum** [comment] 2021-11-30 17:09
Thanks for reporting!
Testing on current `master` with the given configuration and test code I can confirm there is an issue/bug with the `method_argument_space` rule as it needs to be executed multiple times before the result is stable.

**Comment by erikdebruin** [comment] 2021-12-27 17:16
@SpacePossum Any update on this?

**Comment by keradus** [comment] 2021-12-30 10:24
Hey @erikdebruin ,
nobody is currently working on this issue. SpacePossum was eager to validate your bug report (thanks Space!) and that's simply it ;)

Open Source projects are driven by community - if you are interested to have this issue fixed, please consider to contribute ;) It would be warmly welcomed!

**Comment by Wirone** [comment] 2023-05-12 22:45
I'm going to close this because issue mentions Fixer version which is not maintained anymore. Feel free to reproduce it on latest version (if problem still exists) and create new issue.

Also please have in mind that Fixer is focused on modern PHP, that does not mix code with HTML markup (see [this comment](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/issues/6788#issuecomment-1438688702)), so there's high possibility that it won't be supported anyway.

**Closed by Wirone** 2023-05-12 22:45 UTC
Labels: kind/bug
