### ISSUE TITLE
php-cs-fixer breaks indentation with else and <?php

### ISSUE THREAD

**Issue by hannob** [PHP-CS-Fixer/PHP-CS-Fixer#4131] opened 2018-12-03 14:44 UTC
#### The PHP version you are using (`$ php -v`):
=> 7.2.12

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
=> 2.13.1

#### The command you use to run PHP CS Fixer:
=> php-cs-fixer fix [file]

#### The configuration file you are using, if any:
no configuration

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):
 * before running PHP CS Fixer (no changes):
```php
<?php

$a==2;

if ($a==1) {
    ?>1
<?php
} else {
    echo "2";
}
```

 * with unexpected changes applied when running PHP CS Fixer:
```php
<?php

$a==2;

if ($a==1) {
    ?>1
<?php
} else {
        echo "2";
    }
```

 * with the changes you expected instead:
same as original

As you can see above php-cs-fixer breaks the indentation after the else-clause. It should have a 4 space indentation, but it's doing 8 spaces and it also shifts the closing bracket with 4 spaces.

**Comment by Wirone** [comment] 2023-04-02 14:08
I'm going to close this because issue mentions Fixer version which is not maintained anymore. Feel free to reproduce it on latest version (if problem still exists) and create new issue.

Also please have in mind that Fixer is focused on modern PHP, that does not mix code with HTML markup (see [this comment](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/issues/6788#issuecomment-1438688702)), so there's high possibility that it won't be supported anyway.

**Closed by Wirone** 2023-04-02 14:08 UTC
