### ISSUE TITLE
The lowercase_static_reference rules is applied to enum cases

### ISSUE THREAD

**Issue by tmbenhura** [PHP-CS-Fixer/PHP-CS-Fixer#6695] opened 2022-11-23 19:40 UTC
## Bug report
The lowercase_static_reference rule is applied to enums. As a result, code referencing those enums breaks.

  ```php
  <?php

enum HyperlinkTarget: string
{
    case SELF = 'Self';
    case BLANK = 'Blank';
    case TOP = 'Top';
    case PARENT = 'Parent';
}

  ```

result after running:

  ```php
  <?php

enum HyperlinkTarget: string
{
    case self = 'Self';
    case BLANK = 'Blank';
    case TOP = 'Top';
    case parent = 'Parent';
}

  ```

**Comment by julienfalque** [comment] 2022-11-24 17:34
Duplicate of #6673.

**Closed by julienfalque** 2022-11-24 17:34 UTC
Labels: kind/bug
