### ISSUE TITLE
return_assignment rule can destroy code

### ISSUE THREAD

**Issue by mkcl-dev** [PHP-CS-Fixer/PHP-CS-Fixer#6740] opened 2023-01-04 14:43 UTC
### Description

unrisky rule can harm code

There is an issue when dealing with refereces in the return_assignment rule. As a referece can only be a variable, changing it to a const like null will result in an parse error

### Runtime version

```
./vendor/bin/php-cs-fixer -V
PHP CS Fixer 3.8.0 BerSzcz against war! by Fabien Potencier and Dariusz Ruminski.
PHP runtime: 8.1.7-1ubuntu3.1

```

### Used command

```
./vendor/bin/php-cs-fixer fix --dry-run -vvv
```

### Configuration file

```php
<?php

declare(strict_types=1);

$finder = PhpCsFixer\Finder::create()
    ->in(__DIR__.'/src/');

$config = new PhpCsFixer\Config();

return $config->setRules(
    [
        '@PhpCsFixer' => true,
    ]
)
    ->setFinder($finder)
    ->setCacheFile(__DIR__.'/.php_cs.cache');

```
### Code snippet that reproduces the problem

```php
<?php

function &dosomething()
{
    $ret = null;
    return $ret;
}

$a = &dosomething();

/**
 * -            $ret = null;
 * -            return $ret;
 * +            return null;
 */
  ```

**Comment by keradus** [comment] 2023-01-04 14:47
thanks for the report, @mkcl-dev !
would you mind to upgrade to 3.13.2 and verify if issue present there?

**Comment by kubawerlos** [comment] 2023-01-04 14:51
@keradus no need to, it is a duplicate of https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/issues/6482

**Closed by kubawerlos** 2023-01-04 14:51 UTC
Labels: kind/bug
