### ISSUE TITLE
The no_unused_imports not working in combination with global_namespace_import

### ISSUE THREAD

**Issue by alexander-schranz** [PHP-CS-Fixer/PHP-CS-Fixer#6371] opened 2022-04-26 12:20 UTC
## Bug report

Use statement is not removed when global namespace import classes are set to false.

```php
'global_namespace_import' => ['import_classes' => false, 'import_constants' => false, 'import_functions' => false],
'no_unused_imports' => true,
```

### Code snippet that reproduces the problem

```php
use Exception;

functon test(\Exception $exception) {
   // ...
}
```

Currently as workaround I used the following regex with search and replace to remove this use statements:

```
\nuse [abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789]+;
# or
\nuse [a-zA-Z0-9]+;
```

**Comment by Wirone** [comment] 2023-05-13 00:26
Can't reproduce with `3.16-DEV` (current master):

<img width="1038" alt="image" src="https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/assets/600668/16bb980d-8419-4a83-9a81-6647cfe6b944">

I'm going to close this, since it works as expected (or will be when new version is released).

**Closed by Wirone** 2023-05-13 00:26 UTC
Labels: kind/bug
