### ISSUE TITLE
allow/upgrade to sebastian/diff 5.0

### ISSUE THREAD

**Issue by jacekkarczmarczyk** [PHP-CS-Fixer/PHP-CS-Fixer#6777] opened 2023-02-09 14:38 UTC
## Feature request

Currently sebastian/diff dependency is locked to 4.0 which blocks updating phpunit to v10

```
$ composer require --dev phpunit/phpunit:^10.0.0
./composer.json has been updated
Running composer update phpunit/phpunit
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires phpunit/phpunit ^10.0.0 -> satisfiable by phpunit/phpunit[10.0.0, ..., 10.0.7].
    - phpunit/phpunit[10.0.0, ..., 10.0.7] require sebastian/diff ^5.0 -> found sebastian/diff[5.0.0] but the package is fixed to 4.0.4 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
```

```
$ composer why sebastian/diff
friendsofphp/php-cs-fixer v3.14.3 requires sebastian/diff (^4.0)
vimeo/psalm               5.6.0   requires sebastian/diff (^4.0 || ^5.0)
```

**Comment by kubawerlos** [comment] 2023-02-09 14:54
Duplicate of https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/pull/6771

Moreover, you might want to take a look at it https://github.com/PHP-CS-Fixer/shim

**Closed by kubawerlos** 2023-02-09 14:54 UTC
Labels: kind/feature request

**Comment by jacekkarczmarczyk** [comment] 2023-02-09 15:28
searched the issues, but forgot to search PRs as well ;)
thanks
