### ISSUE TITLE
Indentation doesn't work if there is commented code

### ISSUE THREAD

**Issue by hopeseekr** [PHP-CS-Fixer/PHP-CS-Fixer#4833] opened 2020-02-19 17:18 UTC
Tested in PHP 7.2, 7.3 and 7.4 using `@PSR2`.

php-cs-fixer v
> PHP CS Fixer 2.16.1 Yellow Bird by Fabien Potencier and Dariusz Ruminski (c8afb59)

**Sample:**
```php
    public function foo(Request $request)
    {
            $se->inquiry_id = 0; //$inquiry_id;
      $se->client_id = 0; //$client_id;
    //  $se->mrn = $mrn;
      $se->counselor_staff_id = $staffassigned_id;
    }
```

**Expected:**

```php
    public function foo(Request $request)
    {
        $se->inquiry_id = 0; //$inquiry_id;
        $se->client_id = 0; //$client_id;
        //  $se->mrn = $mrn;
        $se->counselor_staff_id = $staffassigned_id;
    }
```

**Actual:**

```php
    public function foo(Request $request)
    {
        $se->inquiry_id = 0; //$inquiry_id;
      $se->client_id = 0; //$client_id;
    //  $se->mrn = $mrn;
      $se->counselor_staff_id = $staffassigned_id;
    }
```

**Comment by timo395** [comment] 2021-03-12 11:33
I got the same issue here in my code

**Comment by Wirone** [comment] 2023-04-05 16:47
Thank you for taking your time reporting this, but unfortunately I'm going to close this because it's related to Fixer version which is not maintained anymore (2.x). Feel free to reproduce it on latest version (3.x) and create new issue.

**Closed by Wirone** 2023-04-05 16:47 UTC
