### ISSUE TITLE
Bug: Not fixing when rule 'header_comment is true'

### ISSUE THREAD

**Issue by xgc1986** [PHP-CS-Fixer/PHP-CS-Fixer#3397] opened 2018-01-06 13:14 UTC
For configuration or updating questions please read the README and UPGRADE documentation,
or visit: https://gitter.im/PHP-CS-Fixer

When reporting an issue (bug) please provide the following information:

#### The PHP version you are using (`$ php -v`):
```
PHP 7.2.0 (cli) (built: Dec  3 2017 21:46:44) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2017 Zend Technologies
    with Xdebug v2.6.0alpha1, Copyright (c) 2002-2017, by Derick Rethans
    with blackfire v1.18.0~mac-x64-non_zts72, https://blackfire.io, by SensioLabs
```

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
`PHP CS Fixer 2.9.0 Speechless by Fabien Potencier and Dariusz Ruminski`

#### The command you use to run PHP CS Fixer:
`bin/php-cs-fixer fix app --allow-risky yes `

#### The configuration file you are using, if any:
```php
<?php
declare(strict_types=1);

$finder = PhpCsFixer\Finder::create()
                           ->exclude('somedir')
                           ->notPath('src/Symfony/Component/Translation/Tests/fixtures/resources.php')
                           ->in(__DIR__);

return PhpCsFixer\Config::create()
                        ->setRules([
                            '@PSR2'                               => true,
                            '@Symfony'                            => true,
                            '@Symfony:risky'                      => true,
                            '@PHPUnit60Migration:risky'           => true,
                            '@PHP71Migration:risky'               => true,
                            //'@DoctrineAnnotation' => true,
                            'array_syntax'                        => ['syntax' => 'short'],
                            'align_multiline_comment'             => true,
                            'binary_operator_spaces'              => ['default' => 'align_single_space_minimal'],
                            'combine_consecutive_issets'          => true,
                            'combine_consecutive_unsets'          => true,
                            'compact_nullable_typehint'           => true,
                            'concat_space'                        => ['spacing' => 'one'],
                            'declare_strict_types'                => true,
                            'escape_implicit_backslashes'         => true,
                            'explicit_string_variable'            => true,
                            'final_internal_class'                => true,
                            'general_phpdoc_annotation_remove'    => true,
                            'header_comment'                      => true,
                            'heredoc_to_nowdoc'                   => true,
                            'linebreak_after_opening_tag'         => true,
                            'list_syntax'                         => ['syntax' => 'short'],
                            'mb_str_functions'                    => true,
                            'native_function_invocation'          => true,
                            'no_null_property_initialization'     => true,
                            'no_short_echo_tag'                   => true,
                            'no_superfluous_elseif'               => true,
                            'no_useless_else'                     => true,
                            'no_useless_return'                   => true,
                            'ordered_class_elements'              => true,
                            'ordered_imports'                     => true,
                            'phpdoc_add_missing_param_annotation' => true,
                            'phpdoc_order'                        => true,
                            'simplified_null_return'              => true,
                            'single_quote'                        => true

                        ])
                        ->setFinder($finder);

```

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):
 * before running PHP CS Fixer (no changes):
```php
<?php
$test = "single quoted string"; 
```

 * with unexpected changes applied when running PHP CS Fixer:
```php
$test = "single quoted string";  // there is no change
```

 * with the changes you expected instead:
```php
$test = 'single quoted string';
```
**Edit** I tried to detect which rules caused the issue and when header_comment is true, then does not fix anything, when removed the rule, then it worked again

**Comment by keradus** [comment] 2018-01-06 14:54
from running with `-vv`:
>        [PhpCsFixer\ConfigurationException\RequiredFixerConfigurationException]  
>        [header_comment] Configuration is required. (32)

you need to configure `header_comment` rule, see docs or example to see how.

we need to change rule to crash earlier, before start processing the files

**Comment by Wirone** [comment] 2023-04-06 07:57
Thank you for taking your time to report this, but unfortunately I'm going to close it since it refers to Fixer's version (2.x) which is not maintained anymore. Feel free to reproduce it on a latest version (3.x) and create new issue if problem still exists 🙂.

**Closed by Wirone** 2023-04-06 07:57 UTC
Labels: kind/enhancement
