### ISSUE TITLE
`no_break_comment` fixer false positive applications

### ISSUE THREAD

**Issue by GrahamCampbell** [PHP-CS-Fixer/PHP-CS-Fixer#5080] opened 2020-07-30 23:08 UTC
## Bug report

* PHP 7.4.8
* PHP-CS-Fixer master ae91c78d3465ffd14f8bac52da6d88f5db37d5be (likely to also not work on all other versions too)
* Enable only the `no_break_comment` fixer

### Code snippet that reproduces the problem

```php
<?php

switch ($var) {
    case 'foo':
        if ($foo === 'foo') {
            return 'bar';
        } else {
            return 'baz';
        }
    default:
        return 'default';
}
```

A no-break comment is not meant to added here, according to the PSR code style specs the fixer was based on, because all code paths result in a return/break/throw/exit, however the fixer adds one for the first block. I suppose the fixer needs more advanced control flow analysis to be able to correctly implement the behaviour that is really wanted.

**Comment by VincentLanglet** [comment] 2022-01-06 18:46
Same with 
```
switch ($var) {
    case 'foo':
        switch ($foo) {
            case 1:
                 return '1';
             default:
                 return '2';
         }
    default:
        return 'default';
}
```

**Comment by Wirone** [comment] 2023-05-12 23:03
Personally I think that `no_break_comment` does not bring value - it adds comment that can easily get outdated when code changes, and we all know that developers often don't read comments and don't clean them when changing code 😉. I don't see value in investing time in this fixer, I would rather deprecate it and remove in next major version. But it's only my opinion, decision is up to @keradus.

Anyway, reproduced with `3.16-DEV` (latest master).

**Comment by SpacePossum** [comment] 2023-05-13 07:56
To me I agree this doesn't bring (much) value, however it is part of https://www.php-fig.org/psr/psr-2/#52-switch-case

**Comment by GrahamCampbell** [comment] 2023-08-11 13:13
not stale

**Comment by keradus** [comment] 2023-08-11 13:26
@GrahamCampbell , if you like to bring the fix in, PR contribution is appreciated!

issue was reported few years back and unfortunately didn't got much support by community to have it solved, nor lot of ppl complain about it. looks like veeeery edge case [worth to fix, but simply not the priority]

**Comment by julienfalque** [comment] 2024-01-02 13:54
> @Wirone commented on May 13, 2023
> [...] it adds comment that can easily get outdated when code changes

For the record, the fixer is supposed to remove the comment when it detects it is not necessary, so this should not happen.

**Comment by keradus** [comment] 2024-01-03 21:52
PSR, like PER-CS, requires the fixer to be present, I would not like to deprecate the rule.

is it worth to fix this bug case? looking how much traffic we got here, not top priority for anyone and I'm actually OK to even close this issue as "won't do". Not because it doesn't make sense, but because affected userbase who complained about it is sooo little.
Same time, if anyone eager to implement fix (while this issue is open or not), it's worth to review&merge.

**Comment by Wirone** [comment] 2024-01-04 08:49
According to @keradus' [feedback](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/issues/5080#issuecomment-1876018372) which confirms [what I wrote earlier](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/issues/5080#issuecomment-1546416089) (at least in terms of investing time), I am going to close this issue as core team _most probably_ won't work on it. If anyone is interested in this improvement, please provide PR which we'll gladly review 🙂.

**Closed by Wirone** 2024-01-04 08:49 UTC
Labels: kind/bug, contribution welcome
