### ISSUE TITLE
Keep empty line breaks inside control statements

### ISSUE THREAD

**Issue by felixpenrose** [PHP-CS-Fixer/PHP-CS-Fixer#4487] opened 2019-08-02 13:08 UTC
In the following code examples below, I'm intentionally adding a line break before and after an `if/else` generally to improve readability, however these get removed. Is it possible to stop this from happening?

In some cases, I agree with the fix applied, but more often than not, there are smaller `if/elseif/else` blocks which are harder to read when there's no empty line breaks in between the control statement and the code within.

#### The PHP version you are using (`$ php -v`):
```
PHP 7.2.0 (cli) (built: Nov 28 2017 23:48:49) ( ZTS MSVC15 (Visual C++ 2017) x64 )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2017 Zend Technologies
```

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
`PHP CS Fixer 2.15.1 Europe Round by Fabien Potencier and Dariusz Ruminski`

#### The command you use to run PHP CS Fixer:
VSCode php-cs-fixer
https://marketplace.visualstudio.com/items?itemName=junstyle.php-cs-fixer

#### The configuration file you are using, if any:
```php
<?php

return PhpCsFixer\Config::create()
    ->setRules([
        '@PSR2'                        => true,
        'array_indentation'            => true,
        'array_syntax'                 => ['syntax' => 'short'],
        'combine_consecutive_unsets'   => true,
        'method_separation'            => false,
        'single_quote'                 => true,
        'full_opening_tag'             => true,
        'fully_qualified_strict_types' => true,

        'no_multiline_whitespace_before_semicolons' => true,

        'binary_operator_spaces' => [
            'align_double_arrow' => true,
            'align_equals'       => true,
        ],
        'braces' => [
            'allow_single_line_closure' => true,
        ],
        'cast_spaces'                      => true,
        'class_definition'                 => ['singleLine' => true],
        'concat_space'                     => ['spacing' => 'one'],
        'declare_equal_normalize'          => ['space'   => 'single'],
        'function_typehint_space'          => true,
        'hash_to_slash_comment'            => true,
        'include'                          => false,
        'lowercase_cast'                   => true,
        'lowercase_constants'              => true,
        'lowercase_keywords'               => true,
        'lowercase_static_reference'       => true,
        'semicolon_after_instruction'      => true,
        'ternary_to_null_coalescing'       => true,
        'no_extra_consecutive_blank_lines' => [
            'return',
        ],
        'no_extra_blank_lines' => [
            'return',
        ],
        'no_multiline_whitespace_around_double_arrow' => true,
        'no_spaces_around_offset'                     => true,
        'no_unused_imports'                           => true,
        'no_whitespace_before_comma_in_array'         => true,
        'no_whitespace_in_blank_line'                 => false,
        'object_operator_without_whitespace'          => true,
        'single_blank_line_before_namespace'          => true,
        'ternary_operator_spaces'                     => true,
        'trailing_comma_in_multiline_array'           => true,
        'trim_array_spaces'                           => true,
        'unary_operator_spaces'                       => true,
        'whitespace_after_comma_in_array'             => true,
        'elseif'                                      => true,
    ])
    ->setLineEnding("\n");

```

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):
 * before running PHP CS Fixer (no changes):
```php
if ($foo == true)
{
    
    echo 'Hi';

}
else if ($bar  == 'bar')
{

    echo 'foo';

} else {

    echo 'bar';

    echo 'baz';

}
```

 * with unexpected changes applied when running PHP CS Fixer:
```php
if ($foo == true) {
    echo 'Hi';
} elseif ($bar == 'bar') {
    echo 'foo';
} else {
    echo 'bar';

    echo 'baz';
}
```

 * with the changes you expected instead:
```php
if ($foo == true) {
    
    echo 'Hi';

} elseif ($bar  == 'bar') {

    echo 'foo';

} else {

    echo 'bar';

    echo 'baz';

}
```

**Comment by ol1s** [comment] 2019-08-14 11:01
I am noticing the same thing, the `braces` fixer probably shouldn't be making the decision to remove blank lines from within a control structure.

A google search is showing me that the same conversation was had way back in 2014, and that the `braces` fixer was changed in version 1 so that it no longer removed blank lines from control structures (in fact I think this was separated into it's own fixer). <-- Does anyone remember this, what was it called?

I wonder whether over the last few years this has unintentionally sneaked back into the `braces` fixer?

**Comment by ol1s** [comment] 2019-08-14 11:35
#567

**Comment by SpacePossum** [comment] 2019-10-08 14:51
>(in fact I think this was separated into it's own fixer). <-- Does anyone remember this, what was it called?

I think you mean `no_extra_blank_lines` and it can do the same thing as the `braces` fixer though configuration (`curly_brace_block`). If someone can confirm that we have indeed the same functionality in `braces` and `no_extra_blank_lines` we can remove it from `braces` and ship it with the next major release (will be a BC break so )

**Comment by brianlmoon** [comment] 2020-01-20 22:48
I came across this as well. For me, it appears to be the braces fixer for sure. 

My config has braces and no_extra_blank_lines like so. When I run those with the --rules option, only braces causes the issue for me. 

```
        'braces'                                      => [
            'allow_single_line_closure'                   => true,
            'position_after_functions_and_oop_constructs' => 'same',
        ],
```
```
        'no_extra_blank_lines'                        => [
            'extra',
        ],
```
```
$ cat test.php
<?php

if (true) {

    $foo = 1;

} else {

    $bar = 2;
}
```
```
$ ~/.composer/vendor/bin/php-cs-fixer fix --dry-run --diff -vvv \
    --rules=braces test.php 
Loaded config default from "/Users/brian/code/dealnews/php-libraries/template/.php_cs.dist".
F
Legend: ?-unknown, I-invalid file syntax (file ignored), S-skipped (cached or empty file), .-no changes, F-fixed, E-error
   1) template/test.php (braces)
      ---------- begin diff ----------
--- Original
+++ New
@@ @@
 <?php
 
 if (true) {
-
     $foo = 1;
-
 } else {
-
     $bar = 2;
 }
 

      ----------- end diff -----------


Checked all files in 0.006 seconds, 10.000 MB memory used
```
```
$ ~/.composer/vendor/bin/php-cs-fixer fix --dry-run --diff -vvv \
    --rules=no_extra_blank_lines test.php 
Loaded config default from "/Users/brian/code/dealnews/php-libraries/template/.php_cs.dist".
.
Legend: ?-unknown, I-invalid file syntax (file ignored), S-skipped (cached or empty file), .-no changes, F-fixed, E-error

Checked all files in 0.005 seconds, 10.000 MB memory used
```

**Comment by SpacePossum** [comment] 2020-03-02 07:35
for progress on this issue see https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/4487

**Comment by cyrrill** [comment] 2020-09-16 06:25
@SpacePossum you linked this same issue in your last comment, was that a typo? Also, any progress on this? Thanks.

**Comment by SpacePossum** [comment] 2021-01-24 14:50
indeed a copy paste thing :)
Julien is working on this here: https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/4884

**Comment by developedsoftware** [comment] 2021-03-18 21:04
Just noticed the brace fixer doing this too. Has there been any progress?

**Comment by SpacePossum** [comment] 2022-06-13 19:39
Hi @XBrayanX ,

It is not an error and the comments above yours provide link to follow the process.

**Comment by Wirone** [comment] 2023-04-06 08:11
Thank you for taking your time to report this, but unfortunately I'm going to close it since it refers to Fixer's version (2.x) which is not maintained anymore. Feel free to reproduce it on a latest version (3.x) and create new issue if problem still exists 🙂.

Also, please have in mind that braces fixer was deprecated in https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/pull/4885 and now it shouldn't be used, so if you plan reproducing this issue, please do it without braces in your config.

**Closed by Wirone** 2023-04-06 08:11 UTC
Labels: kind/enhancement, kind/refactoring, kind/feature request
