### ISSUE TITLE
False indented for multline interface in anonymous classes inside a indented function

### ISSUE THREAD

**Issue by alexander-schranz** [PHP-CS-Fixer/PHP-CS-Fixer#5422] opened 2021-01-09 16:15 UTC
## Bug report

PHP: 7.4.13
PHP CS FIXER: 2.17.3

My Config:

```php
<?php

$header = <<<'EOF'
This file is part of Sulu.

(c) Sulu GmbH

This source file is subject to the MIT license that is bundled
with this source code in the file LICENSE.
EOF;

return PhpCsFixer\Config::create()
    ->setRiskyAllowed(true)
    ->setRules([
        '@Symfony' => true,
        '@Symfony:risky' => true,
        'ordered_imports' => true,
        'concat_space' => ['spacing' => 'one'],
        'array_syntax' => ['syntax' => 'short'],
        'phpdoc_align' => false,
        'class_definition' => [
            'multiLineExtendsEachSingleLine' => true,
        ],
        'linebreak_after_opening_tag' => true,
        'declare_strict_types' => true,
        'mb_str_functions' => true,
        'no_php4_constructor' => true,
        'no_superfluous_phpdoc_tags' => ['allow_mixed' => true],
        'no_unreachable_default_argument_value' => true,
        'no_useless_else' => true,
        'no_useless_return' => true,
        'php_unit_strict' => true,
        'phpdoc_order' => true,
        'strict_comparison' => true,
        'strict_param' => true,
        'phpdoc_to_comment' => false,
        'header_comment' => ['header' => $header],
        'single_line_throw' => false,
    ])
    ->setFinder(
        PhpCsFixer\Finder::create()
            ->exclude('vendor')
            ->exclude('cache')
            ->exclude('Tests/reports/')
            ->in(__DIR__)
    );
```

### Code snippet that reproduces the problem

My Code:

```php
    protected function myFunction()
    {
        return new class() extends MockWrapper implements DimensionContentInterface, WorkflowInterface
        {
        }
   }
```

Get Fixed to:

```php
    protected function myFunction()
    {
        return new class() extends MockWrapper implements
    DimensionContentInterface, // this is false indented
            WorkflowInterface {
       }
   }
```

Instead of:

```php
    protected function myFunction()
    {
        return new class() extends MockWrapper implements
            DimensionContentInterface, // correctly indented
            WorkflowInterface {
       }
   }
```

**Comment by keradus** [comment] 2021-01-09 18:01
thanks for reporting, @alexander-schranz !
would you give it a try and send a patch PR ?

**Comment by alexander-schranz** [comment] 2021-01-10 23:00
I'm little bit lost, do you have any hint which fixer or script does could the issue?

**Comment by kubawerlos** [comment] 2021-01-11 20:49
@alexander-schranz I cannot reproduce the issue with the config and example you have provided.

Anyways, answering your question: try to run `php-cs-fixer fix --diff --dry-run -v` - the `-v` flag will make output having fixer names affecting each file.

**Comment by thomaspiedade** [comment] 2021-01-13 01:28
I think i have same bug. 

I have a class like this:
```php
class Foo extends Bar implements InterfaceOne, InterfaceTwo, InterfaceThree
{
}
```

Fixer is fixing like this:
```php
class Foo extends Bar implements InterfaceOne, 
    InterfaceTwo, 
    InterfaceThree
{
}
```

But the correct way from PSR2 is:

```php
class Foo extends Bar implements 
    InterfaceOne, 
    InterfaceTwo, 
    InterfaceThree
{
}
```

My Rules:
```php
[
        '@PSR2' => true,
        '@PhpCsFixer' => true,
        'blank_line_after_opening_tag' => true,
        'blank_line_before_statement' => ['statements' => []],
        'braces' => ['allow_single_line_closure' => true],
        'compact_nullable_typehint' => true,
        'concat_space' => ['spacing' => 'one'],
        'declare_equal_normalize' => ['space' => 'none'],
        'declare_strict_types' => true,
        'function_typehint_space' => true,
        'method_argument_space' => ['on_multiline' => 'ensure_fully_multiline'],
        'class_definition' => [
            'multi_line_extends_each_single_line' => true,
            'single_item_single_line' => true,
        ],
        'multiline_whitespace_before_semicolons' => ['strategy' => 'no_multi_line'],
        'new_with_braces' => true,
        'no_empty_statement' => true,
        'no_extra_blank_lines' => ['break', 'case', 'continue', 'curly_brace_block', 'default', 'extra', 'parenthesis_brace_block', 'return',
            'square_brace_block', 'switch', 'throw', 'use', 'useTrait', 'use_trait'],
        'no_leading_import_slash' => true,
        'no_leading_namespace_whitespace' => true,
        'no_trailing_comma_in_list_call' => true,
        'no_trailing_comma_in_singleline_array' => true,
        'no_unused_imports' => true,
        'no_whitespace_in_blank_line' => true,
        'php_unit_internal_class' => [],
        'php_unit_test_class_requires_covers' => false,
        'return_assignment' => false,
        'return_type_declaration' => ['space_before' => 'none'],
        'single_import_per_statement' => false,
        'single_trait_insert_per_statement' => false,
        'trailing_comma_in_multiline_array' => [],
        'yoda_style' => ['always_move_variable' => false, 'equal' => true, 'identical' => true, 'less_and_greater' => null]
    ]
```

**Comment by alexander-schranz** [comment] 2021-01-13 13:13
@kubawerlos Thank you hope I could get back at this at the weekend!

**Comment by Wirone** [comment] 2023-05-10 21:39
Closing as this issue refers to Fixer's version which is not maintained anymore. Feel free to reproduce it with latest version (`3.16.0`) and create new issue.

**Closed by Wirone** 2023-05-10 21:39 UTC
Labels: kind/bug
