### ISSUE TITLE
Closing semicolon not indented

### ISSUE THREAD

**Issue by bobemoe** [PHP-CS-Fixer/PHP-CS-Fixer#4624] opened 2019-11-03 19:57 UTC
For configuration or updating questions please read the README and UPGRADE documentation,
or visit: https://gitter.im/PHP-CS-Fixer

When reporting an issue (bug) please provide the following information:

#### The PHP version you are using (`$ php -v`):
=> PHP 7.3.9-1~deb10u1 (cli) (built: Sep 18 2019 10:33:23) ( NTS )

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
=> PHP CS Fixer 2.16.0 Yellow Bird by Fabien Potencier and Dariusz Ruminski

#### The command you use to run PHP CS Fixer:
=> vendor/bin/php-cs-fixer fix src/Test.php --rules=@PhpCsFixer

#### The configuration file you are using, if any:
```php
=> ....................................
```

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):
 * before running PHP CS Fixer (no changes):
```php
<?php

namespace App;

class MyClass
{
public function test($name)
{
$domain = $this->getDoctrine()
->getRepository(Some::class)
->findOneByName($name)
;

$enquiry = new Enquiry();
$enquiry->setDomain($domain);
$form = $this->createForm(
EnquiryType::class,
$enquiry,
['action' => $this->generateUrl('enquiry_new')]
);
}
}

```

 * with unexpected changes applied when running PHP CS Fixer:
```php
<?php

namespace App;

class MyClass
{
    public function test()
    {
        $domain = $this->getDoctrine()
            ->getRepository(Domain::class)
            ->findOneByName($_SERVER['SERVER_NAME'])
;

        $enquiry = new Enquiry();
        $enquiry->setDomain($domain);
        $form = $this->createForm(
    EnquiryType::class,
    $enquiry,
    ['action' => $this->generateUrl('enquiry_new')]
);
    }
}

```

 * with the changes you expected instead:
```php
<?php

namespace App;

class MyClass
{
    public function test()
    {
        $domain = $this->getDoctrine()
            ->getRepository(Domain::class)
            ->findOneByName($_SERVER['SERVER_NAME'])
        ;

        $enquiry = new Enquiry();
        $enquiry->setDomain($domain);
        $form = $this->createForm(
            EnquiryType::class,
            $enquiry,
            ['action' => $this->generateUrl('enquiry_new')]
        );
    }
}

```

**Comment by kubawerlos** [comment] 2019-11-09 22:27
@GrahamCampbell @egircys shouldn't `MultilineWhitespaceBeforeSemicolonsFixer` take care of this?

Right now it works like this:
for code
```php
        $foo
            ->bar()
            ->baz()
;
```
with `no_multi_line` it will update the code to:
```php
        $foo
            ->bar()
            ->baz();
```
then with `new_line_for_chained_calls` it will update the code to:
```php
        $foo
            ->bar()
            ->baz()
        ;
```
So two opposite (in the context of chained calls) options are not doing the opposite change.

Also, the code:
```php
function foo () {
    return 1 + 2
        ;
}
```

shouldn't have the semicolon moved for both options?

**Comment by egircys** [comment] 2019-11-11 14:18
Hi @kubawerlos,

The `new_line_for_chained_calls` checks only if the semicolon is on the same line as the last call and moves it to the new line. 

In the example the semicolon is already on the new line, but the indentation is wrong. So it's not applied. 

If there's a fixer for indentation (I'm not aware of it though), then maybe it should take care of this.

**Comment by kubawerlos** [comment] 2019-11-11 17:12
@egircys 

> The `new_line_for_chained_calls` checks only if the semicolon is on the same line as the last call and moves it to the new line.

Not exactly - it moves it to new line **respecting indentation**.

The `new_line_for_chained_calls` could check if semicolon is where it suppose to be - in next line with respecting indentation - and if not move it there.

**Comment by egircys** [comment] 2019-11-13 08:58
When initially adding this fixer I didn't have in mind that it should check the indentation too.

However, your expectations are reasonable and I didn't find another fixer which is more suitable. I think it would be a nice addition to this fixer! Thank you very much for reporting this @bobemoe, @kubawerlos .

**Comment by Nothing-Works** [comment] 2020-06-02 03:32
@egircys Hi I am just wondering any update on this? just faced this problem when using `--rules=@PhpCsFixer`.

**Comment by Wirone** [comment] 2023-04-05 16:50
Thank you for taking your time reporting this, but unfortunately I'm going to close this because it's related to Fixer version which is not maintained anymore (2.x). Feel free to reproduce it on latest version (3.x) and create new issue.

**Closed by Wirone** 2023-04-05 16:50 UTC
Labels: kind/enhancement
