### ISSUE TITLE
`no_unused_imports` - Globally-Namespaced Unused Imports Are Not Removed When Mentioned in a DocComment

### ISSUE THREAD

**Issue by rprussinSV** [PHP-CS-Fixer/PHP-CS-Fixer#8070] opened 2024-06-06 17:28 UTC
### Problem description

When using globally-namespaced classes, it seems that PHP-CS-Fixer's `no_unused_imports` rule is unable to differentiate between a word that is describing something in a DocComment, and the actual classname itself (it even ignores casing).

I was not able to reproduce this issue with classes using proper PSR-4 namespaces.

### Minimal reproducer

```PHP
use DB; // Unused Import

// ...

/**
 * db (despite being lowercase and not using a leading blackslash (e.g. `\DB`), this will prevent `no_unused_imports` rule from removing the unused import)
 */
```

### Fixer version

3.53.0 15 Keys

### PHP version

8.1.28

### How do you run Fixer?

Composer package

### Contribution Checks

- [X] I have verified if this problem was already reported
- [X] I am familiar with ["Feature or bug?"](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/master/feature-or-bug.rst)

**Comment by Wirone** [comment] 2024-06-06 17:39
Duplicate of #2814.

**Closed** 2024-06-06 17:40 UTC
Labels: kind/bug, status/to verify
