### ISSUE TITLE
"Files that were not fixed due to errors reported during linting after fixing" caused by heredocs and nowdocs

### ISSUE THREAD

**Issue by rauven** [PHP-CS-Fixer/PHP-CS-Fixer#6636] opened 2022-09-14 10:17 UTC
## Bug report

php-cs-fixer version:
PHP CS Fixer 3.11.0 (7dcdea3) Oliva by Fabien Potencier and Dariusz Ruminski.
PHP runtime: 8.1.10

php version: 
PHP 8.1.10 (cli) (built: Sep  4 2022 08:41:25) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.10, Copyright (c) Zend Technologies with Zend OPcache v8.1.10, Copyright (c), by Zend Technologies
 
Run using:
php-cs-fixer fix /file/path.php

This triggers that error
  ```php
  <?php
    $qr = <<<SQL
      **SQL CODE**
    SQL;
    $data = $db->query($qr);
  
    $html = <<<HTML
      **HTML CODE**
    HTML;
    echo bufferTags($html,$data,true);
  ?>
  ```
  
 So does this
  ```php
  <?php
    $qr = <<<'SQL'
      **SQL CODE**
    SQL;
    $data = $db->query($qr);
  
    $html = <<<'HTML'
      **HTML CODE**
    HTML;
    echo bufferTags($html,$data,true);
  ?>
  ```
  
  But this doesn't trigger that error
  ```php
  <?php
    $qr = '
      **SQL CODE**
    ';
    $data = $db->query($qr);
  
    $html = '
      **HTML CODE**
    ';
    echo bufferTags($html,$data,true);
  ?>
  ```

All 3 cases are valid php.

This is my config
```php
  <?php
    $config = new PhpCsFixer\Config();
    return $config
        ->setRiskyAllowed(true)
        ->setIndent("\t")
        ->setRules([
            '@PSR2' => true,
            '@PhpCsFixer' => true,
            '@PhpCsFixer:risky' => true,
            '@PHP56Migration:risky' => true,
            '@PHPUnit57Migration:risky' => true,
            'blank_line_before_statement' => ['statements'=>['break','case','continue','declare','default','exit','goto','return','switch','throw','try']],
            'concat_space' => ['spacing'=>'one'],
            'fopen_flags' => true,
            'heredoc_indentation' => true,
            'linebreak_after_opening_tag' => true,
            'native_constant_invocation' => true,
            'native_function_invocation' => true,
            'ordered_class_elements' => false,
            'phpdoc_align' => false,
            'self_accessor' => false,
        ])
        ->setFinder(PhpCsFixer\Finder::create()
            ->exclude('vendor')
            ->in(__DIR__)
        )
    ;
  ?>
  ```

**Comment by SpacePossum** [comment] 2022-09-15 14:17
Thanks for reporting.

The issue seems within the `heredoc_indentation`, also happens on latest `2906a4c2d41b18b0e38fe779caf5db5bb14388dd`

```
$ php php-cs-fixer fix test.txt --dry-run -vvv --diff --rules=heredoc_indentation
PHP CS Fixer 3.11.0 Oliva by Fabien Potencier and Dariusz Ruminski.
PHP runtime: 7.4.24
Loaded config default from "/home/possum/work/PHP-CS-Fixer/.php-cs-fixer.dist.php".
Paths from configuration file have been overridden by paths provided as command arguments.
E                                                                                                                                                                                                                                                                             1 / 1 (100%)
Legend: .-no changes, F-fixed, S-skipped (cached or empty file), I-invalid file syntax (file ignored), E-error

Checked all files in 0.004 seconds, 14.000 MB memory used

Files that were not fixed due to errors reported during linting after fixing:
   1) /home/possum/work/PHP-CS-Fixer/test.txt

                                                                                       
        [PhpCsFixer\Linter\LintingException]                                           
        Parse error: Invalid indentation - tabs and spaces cannot be mixed on line 3.  
```                                                                                       

Note to self: when copy/pasting the provided example do not allow your IDE to "fix" the indent on paste ; )

**Comment by Wirone** [comment] 2023-05-12 10:09
Can't reproduce on 3.16, using provided config.

Snippet 1:
![image](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/assets/600668/41857f66-a96c-404d-8065-4af7234868dc)

Snippet 2:
![image](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/assets/600668/2e5effbd-71eb-4c8e-860c-186e29b57985)

Snippet 3:
![image](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/assets/600668/cea281c2-0168-4a98-804f-046d77f4db43)

I'm going to close this as completed, it had to be fixed at some point 🙂.

**Closed by Wirone** 2023-05-12 10:09 UTC
Labels: kind/bug

**Comment by YLivay** [comment] 2023-07-17 15:42
This doesnt seem to be fixed.

```
<?php

if (true) {
	if (true) {
	    $a = true;
	}
}
```
in the above example `$a = true;` is indented with one tab followed by 4 spaces. this correctly gets fixed to whatever indentation style is specified in the config.

```
<?php

if (true) {
	$a = <<<'EOD'
	    test
		EOD;
}
```
but in this example the `test` line is also indented with a tab followed by 4 spaces, but php-cs-fixer throws a linting exception:
```
Files that were not fixed due to errors reported during linting before fixing:
   1) /path/to/reproducer.php

                                                                                       
        [PhpCsFixer\Linter\LintingException]                                           
        Parse error: Invalid indentation - tabs and spaces cannot be mixed on line 5.  
                                                                    
```
this is using PHP CS Fixer 3.17.0 (3f0ed86)and PHP 8.2.8

I havent tested on latest php cs fixer yet but skimming the changelogs there doesnt seem to be a fix related to this.

Should this issue be reopened or make a new one?
