### ISSUE TITLE
New line added in description of fields of @param array

### ISSUE THREAD

**Issue by mlocati** [PHP-CS-Fixer/PHP-CS-Fixer#2964] opened 2017-08-07 06:57 UTC
As per [PSR-5](https://github.com/php-fig/fig-standards/blob/f3b931327d3bc17a1045125646e2648170c97975/proposed/phpdoc.md#713-param) (currently in *proposed* state), we can describe the fields of an array parameter using this notation:
```
 * @param array $options {
 *     @var bool   $required Whether this element is required
 *     @var string $label    The display name for this element
 * }
```

BTW, php-cs-fixer does not to indent the `@var` lines and adds an extra new line before the first `@var` line.

### The PHP version you are using:

`PHP 7.1.6 (cli) (built: Jun  8 2017 02:06:32) ( ZTS MSVC14 (Visual C++ 2015) x86 )`

### PHP CS Fixer version you are using:

`PHP CS Fixer 2.4.0 Silver Gingerbread by Fabien Potencier and Dariusz Ruminski (63661f3)`

### The command you use to run the fixer (and the configuration file you are using if any).

`php php-cs-fixer.phar  fix --rules=@Symfony,-phpdoc_align test.php`

> A minimal sample of valid PHP code that is not fixed correctly (if applicable).

```php
<?php

/**
 * The function description.
 *
 * @param array $data Some data {
 * @var int|null $field1 An array field
 * @var string $field2 An array field
 * }
 */
function f($data)
{
}
```

### The fixed version of that code after you run the fixer

```php
/**
 * The function description.
 *
 * @param array $data Some data {
 *
 * @var int|null $field1 An array field
 * @var string $field2 An array field
 * }
 */
function f($data)
{
}
```

### and the version you expected.

```php
/**
 * The function description.
 *
 * @param array $data Some data {
 *     @var int|null $field1 An array field
 *     @var string $field2 An array field
 * }
 */
function f($data)
{
}
```

**Comment by keradus** [comment] 2017-08-07 09:21
we do not support this syntax at all, that's probably why you got weird output.
I would strongly suggest you to switch to ParamBag (any strongly typehinted object with needed parameters) instead of using assoc arrays.
if not and this annoys you a lot, please open a PR with fix. yet, as claimed, since there is no support for this syntax at all, it may be required to modify few rules :(

**Comment by mlocati** [comment] 2017-08-07 09:28
> we do not support this syntax at all

Any reason for that? If/when PSR-5 gets approved, this syntax will become more and more common...

**Comment by keradus** [comment] 2017-08-07 09:37
We do support PSR-5 partially, yet keep in mind that it is 4 years old proposal that is never ending story, ppl were leaving group working on that particular document and so on, I am really eager to see it finished, yet I don't believe that will happen soon.
We do not support that particular notation to document nested params.
Why ? As in general, this is not good practice anyway, and this project is based on community - community write fixers for rules they want to follow. For that, so far there were simply no interest of community to support that syntax. If you are interested in it, you are more than welcome to introduce support of it.

**Comment by mlocati** [comment] 2017-08-07 09:41
> We do support PSR-5 partially, yet keep in mind that it is 4 years old proposal that is never ending story

That could hopefully change: see https://groups.google.com/forum/#!topic/php-fig/bcV4KXIW6dQ

**Comment by Wirone** [comment] 2023-04-06 07:54
Thank you for taking your time to report this, but unfortunately I'm going to close it since it refers to Fixer's version (2.x) which is not maintained anymore. Feel free to reproduce it on a latest version (3.x) and create new issue if problem still exists 🙂.

**Closed by Wirone** 2023-04-06 07:54 UTC
Labels: kind/feature request, topic/annotation
