### ISSUE TITLE
PhpdocSeparation - remove part of PHPDoc

### ISSUE THREAD

**Issue by javaDeveloperKid** [PHP-CS-Fixer/PHP-CS-Fixer#4681] opened 2019-12-01 09:41 UTC
I have a controller where there are several roles that can access it. Keeping this in one line makes this line very long so I pushed every role to it's own line **with asertiks** at the beginning. However annotation `@Security` breaks when there are asteriks, so I removed them as you can see in **before running PHP CS Fixer (no changes)** code sample.  Unfortunatelly, now there is problem with `phpdoc_separation` fixer...
Should this be a reason to consider this fixer as risky?

#### The PHP version you are using (`$ php -v`):
7.2.21

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
2.15.1

#### The command you use to run PHP CS Fixer:
php-cs-fixer fix

#### The configuration file you are using, if any:
```php
=> ....................................
```

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):
 * before running PHP CS Fixer (no changes):
```php
    /**
     * @Security("has_role('ROLE_ONE')
               or has_role('ROLE_TWO')
               or has_role('ROLE_THREE')")
     *
     * @return Response
     */
    public function action(): Response
    {
    }
```

 * with unexpected changes applied when running PHP CS Fixer:
```php
    /**
     * @Security("has_role('ROLE_ONE')
     *
     * @return Response
     */
    public function action(): Response
    {
    }
```

 * with the changes you expected instead:
```php
=> ....................................
```

**Comment by javaDeveloperKid** [comment] 2019-12-13 12:22
Anyone?

**Comment by SpacePossum** [comment] 2019-12-18 11:56
Hi @javaDeveloperKid ,

Thanks for reporting this issue, this seems to be a bug within the `phpdoc_separation` rule indeed.
Reproduced on 2.15 using `$ php php-cs-fixer fix test.php -vvv  --diff --rules="phpdoc_separation"` with PHPDoc sample as provided.

**Comment by javaDeveloperKid** [comment] 2022-01-26 12:47
:(

**Comment by keradus** [comment] 2022-01-26 14:09
@javaDeveloperKid , if you still experience this issue, please do not hesitate to raise the fix PR.
we strongly rely on community, the core team is focusing on tickets having biggest impact only.

**Comment by Wirone** [comment] 2023-05-12 23:21
Closing as this issue refers to Fixer's version which is not maintained anymore. Feel free to reproduce it with latest version and create new issue with proper reproduction example. It would be even better with a PR 😉.

**Closed** 2023-05-12 23:21 UTC
Labels: kind/bug
