### ISSUE TITLE
[PHP8.2] Support Disjunctive Normal Form Types

### ISSUE THREAD

**Issue by SpacePossum** [PHP-CS-Fixer/PHP-CS-Fixer#6608] opened 2022-09-02 09:33 UTC
rfc: https://wiki.php.net/rfc/dnf_types

example:
```php
function generateSlug((HasTitle&HasId)|null $post) 
```

- [ ] create new custom tokens for `(` and `)` (https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/6629)
- [ ] update existing transformers to work properly with PHP8.2 code (https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/6629)
- [ ] update existing rules to work properly with PHP8.2 code
- [ ] create new rules if needed

I suggest creating new custom tokens for new supported syntax to ease the support for it in all the rules. This won't be BC break for 3rd party fixers because we don't support 8.2 yet. As such we should only insert these new tokens on PHP8.2 and only claim 8.2 support when we've added all the new tokens (not just for this case)

**Comment by Wirone** [comment] 2022-09-05 22:27
[As I found out](https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/6621#issuecomment-1237500506) in #6621 complex DNF intersections, like `A|(B&C&D)` with more than 1 `&`, cause fatal error (tokenizer problem?). `php -l` on file that uses such intersections does not detect any syntax errors.

It must be solved because it would break Fixer for people using such complex DNFs.

**Comment by SpacePossum** [comment] 2022-09-06 06:57
If you take the code that causes the fatal and tokenize it locally yourself on PHP8.2, like 

```
<?php
$tokens = token_get_all($brokenCodeAsString, TOKEN_PARSE);
```

do you get a good output?

**Comment by Wirone** [comment] 2022-09-06 07:15
Yes, the code provided in `tests/Fixtures/Integration/misc/PHP8_2.test` work properly with `token_get_all()`:

```php
<?php

$tokens = token_get_all($content = file_get_contents(__DIR__ . '/dnf.php'), TOKEN_PARSE);

var_dump($content);
var_dump('Tokens found: ' . count($tokens));
```

<img width="619" alt="image" src="https://user-images.githubusercontent.com/600668/188570251-b728e02e-e247-4cb7-9ec3-20d0166a36fc.png">

**Comment by SpacePossum** [comment] 2022-09-06 08:34
Thanks :+1:  Than it likely an issue in our tokenizer.
You can try something like:

```php
<?php

require_once __DIR__.'/vendor/autoload.php';

$tokens = \PhpCsFixer\Tokenizer\Tokens::fromCode($yourCode);
echo $tokens->count();
```

It might give us details about with `transformer` doesn't like the code.
We should 100% sure add a new `transformer` for all  `(`, `&` and `)` for these cases anyway (and than update the existing fixer and than add new ones if we want new ones)

**Comment by Wirone** [comment] 2022-09-07 07:05
It also return 289 tokens, so the problem is not in tokenizing. I don't know internals enough, but [fail points to](https://github.com/FriendsOfPHP/PHP-CS-Fixer/runs/8196636666?check_suite_focus=true#step:11:562) `PhpCsFixer\Linter\ProcessLintingResult->check()`. I'll try to look at it more.

**Comment by SpacePossum** [comment] 2022-09-07 08:06
Ah i see the check now, 
so what happens is that the tool takes valid PHP8.2 code, changes (`fixes`) it and by doing that creating invalid PHP code. We check if the result is valid PHP and if not we do not write back the result.

**Comment by SpacePossum** [comment] 2022-09-07 20:00
```php
<?php
class Dnf
{
    private A|(B&C) $a; // valid
    private (B&C)|A $b;  // valid
    private readonly A|(B&C) $c;  // valid
    private readonly (B&C)|A $d; // invalid?
}
```

With `php -l` results in `Parse error: syntax error, unexpected token "(", expecting variable in app/test.php on line 7` , when running on `php:8.2.0RC1-zts-alpine3.16` docker image. Wondering if this is expected
cc @Girgias (sorry for the ping out of nowhere)

**Comment by SpacePossum** [comment] 2022-09-07 20:18
Thanks for the fast reply! :+1:  :)

**Comment by Wirone** [comment] 2022-09-09 13:10
After #6621 gets merged, we need to create another MR that would add and fix such fixtures:

<details>
  <summary>SHOW DIFF</summary>

```diff
Index: tests/Fixtures/Integration/misc/PHP8_2.test
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/tests/Fixtures/Integration/misc/PHP8_2.test b/tests/Fixtures/Integration/misc/PHP8_2.test
--- a/tests/Fixtures/Integration/misc/PHP8_2.test	(revision 6c6655389b3b2d6d5f0ebaab6248daf10b76e1d7)
+++ b/tests/Fixtures/Integration/misc/PHP8_2.test	(date 1662728878343)
@@ -56,6 +56,57 @@
 
 array_filter([], fn (true $n) => true === $n);
 
+// https://wiki.php.net/rfc/dnf_types
+interface DnfA
+{
+    public function foo(): void;
+
+    public function bar(): void;
+
+    public function baz(): void;
+}
+interface DnfB
+{
+    public function foo(): void;
+}
+interface DnfC
+{
+    public function bar(): void;
+}
+interface DnfD
+{
+    public function baz(): void;
+}
+interface DnfE extends DnfB
+{
+}
+interface DnfF extends DnfC
+{
+}
+interface DnfG extends DnfD
+{
+}
+
+class DnfTypes
+{
+    private DnfA|(DnfB&DnfC&DnfD)|(DnfE&DnfF&DnfG) $whatever;
+
+    public function __construct(
+        private DnfA|(DnfB&DnfC&DnfD)|(DnfE&DnfF&DnfG) $notSure
+    ) {
+    }
+
+    public function notSure(): DnfA|(DnfB&DnfC&DnfD)|(DnfE&DnfF&DnfG)
+    {
+        return $this->notSure;
+    }
+
+    public function setWhatever(DnfA|(DnfB&DnfC&DnfD)|(DnfE&DnfF&DnfG) $whatever): void
+    {
+        $this->whatever = $whatever;
+    }
+}
+
 // https://wiki.php.net/rfc/constants_in_traits
 trait WithConstants
 {
@@ -111,6 +162,56 @@
 
 array_filter([], fn     (TRUE     $n)     =>     TRUE     ===     $n);
 
+// https://wiki.php.net/rfc/dnf_types
+interface DnfA
+{
+    public function foo(): void;
+
+    public function bar(): void;
+
+    public function baz(): void;
+}
+interface DnfB
+{
+    public function foo(): void;
+}
+interface DnfC
+{
+    public function bar(): void;
+}
+interface DnfD
+{
+    public function baz(): void;
+}
+interface DnfE extends DnfB
+{
+}
+interface DnfF extends DnfC
+{
+}
+interface DnfG extends DnfD
+{
+}
+
+class DnfTypes {
+    private DnfA | ( DnfB & DnfC & DnfD) | ( DnfE & DnfF & DnfG ) $whatever;
+
+    public function __construct(
+        private DnfA | ( DnfB & DnfC & DnfD) | ( DnfE & DnfF & DnfG ) $notSure
+    ) {
+    }
+
+    public function notSure(): DnfA | ( DnfB & DnfC & DnfD) | ( DnfE & DnfF & DnfG )
+    {
+        return $this->notSure;
+    }
+
+    public function setWhatever(DnfA | ( DnfB & DnfC & DnfD) | ( DnfE & DnfF & DnfG ) $whatever): void
+    {
+        $this->whatever = $whatever;
+    }
+}
+
 // https://wiki.php.net/rfc/constants_in_traits
 trait      WithConstants      {
     public    const ONE   = 'one';

```
</details>

Those fixture were failing, so they were removed in order to be able to merge integration test's base.

**Comment by Wirone** [comment] 2022-09-09 13:11
@SpacePossum could you add checklist to the issue's description, like [here](https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/6605#issue-1359429795)? This will allow us track required work.

**Comment by SpacePossum** [comment] 2022-09-09 13:44
Not 100% sure what you want me to add here. I'm in the middle of developing the needed changes and tests for this issue btw.

**Comment by Wirone** [comment] 2022-09-09 13:53
@SpacePossum checklist in the issue description, with link to [my comment](#issuecomment-1241958302), like in 6605 or 6613:

<img width="254" alt="image" src="https://user-images.githubusercontent.com/600668/189365819-796e18e4-8a39-42a5-975e-70176ad4e153.png">

It's hard to track what's left from the comments, so it's better when it's tracked at the top 🙂

**Comment by SpacePossum** [comment] 2022-09-12 07:41
would be nice to clean up this as well
```php
<?php

function foo1 (A|A $a) {
   // valid even before PHP8.2
}

function foo2 ( (A&B)|(A&B) $a) {

}
```

```php
<?php

function foo1 (A $a) {
   // valid even before PHP8.2
}

function foo2 ( A&B $a) {

}
```

**Comment by Girgias** [comment] 2022-09-12 10:22
> would be nice to clean up this as well
> 
> ```
> <?php
> 
> function foo1 (A|A $a) {
>    // valid even before PHP8.2
> }
> 
> function foo2 ( (A&B)|(A&B) $a) {
> 
> }
> ```

They might be syntactically valid, but those things will emit compiler errors due to type redundancy: https://3v4l.org/sfRi7

> ```
> <?php
> 
> function foo1 (A $a) {
>    // valid even before PHP8.2
> }
> 
> function foo2 ( A&B $a) {
> 
> }
> ```

**Comment by SpacePossum** [comment] 2022-09-12 11:08
Ah yes, thanks for the demo! so no action needed here on that one :)

**Comment by Wirone** [comment] 2022-09-12 11:09
@Girgias yeah, that's why [I proposed](#issuecomment-1241958302) more complex, "real world" combinations without reusing the same intersection 🙂 Since integration test is merged (6621), these fixtures can be re-added to the file and fixed.

**Closed** 2022-11-07 19:22 UTC
Labels: kind/feature request, topic/PHP8.2
