### ISSUE TITLE
Add phpdoc xxx[] -> array<xxx> fixer

### ISSUE THREAD

**Issue by mvorisek** [PHP-CS-Fixer/PHP-CS-Fixer#7077] opened 2023-06-22 12:11 UTC
## Feature request

`xxx[]` is an old way to define the type is an array of some types. The modern syntax is `array<xxx>` which is much easier to understand as the native type is on the left side and support key type definition like `array<kkk, xxx>`.

This is a feature request to offer a fixer to transform/normalize all phpdocs (and even if part of some inner phpdoc type like `\Closure(int[]): void` or `Foo<X>[]`) from `xxx[]` -> `array<xxx>` syntax.

**Comment by Wirone** [comment] 2023-06-22 12:18
There's [`PhpdocArrayStyleFixer`](https://github.com/kubawerlos/php-cs-fixer-custom-fixers#phpdocarraystylefixer) from @kubawerlos' custom fixers. You can use that already, so this won't get priority here 😉.

**Comment by julienfalque** [comment] 2024-01-02 14:50
Duplicate of #4698.

**Closed by julienfalque** 2024-01-02 14:50 UTC
Labels: kind/feature request, contribution welcome, has userland alternative
