### ISSUE TITLE
Braces fails in multiline arguments methods declarations

### ISSUE THREAD

**Issue by Mapteg34** [PHP-CS-Fixer/PHP-CS-Fixer#4617] opened 2019-11-01 10:21 UTC
#### The PHP version you are using (`$ php -v`):
```
PHP 7.3.11 (cli) (built: Oct 28 2019 18:21:06) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.11, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.11, Copyright (c) 1999-2018, by Zend Technologies
```

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
```
PHP CS Fixer 2.15.1 Europe Round by Fabien Potencier and Dariusz Ruminski (2006451)
```

#### The command you use to run PHP CS Fixer:
Run from phpstorm

#### The configuration file you are using, if any:
```php
<?php

$finder = PhpCsFixer\Finder::create()->in(__DIR__);

return PhpCsFixer\Config::create()
    ->setRules([
        '@PSR2' => true,
        'braces' => [
            'position_after_functions_and_oop_constructs' => 'next',
            'position_after_anonymous_constructs' => 'same',
        ],
    ])
    ->setFinder($finder)
;

```

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):
 * before running PHP CS Fixer (no changes):
```php
    public function __construct(
        TransactionService $transactionService,
        MatchService $matchService,
        CommissionService $commissionService
    )
    {
...

    public function create(User $user, Match $match, MatchEventEnum $event, BetResultEnum $result, int $sum): Bet
    {
```

 * with unexpected changes applied when running PHP CS Fixer:
```php
    public function __construct(
        TransactionService $transactionService,
        MatchService $matchService,
        CommissionService $commissionService
    ) {
...

    public function create(User $user, Match $match, MatchEventEnum $event, BetResultEnum $result, int $sum): Bet
    {
```

 * with the changes you expected instead:
```php
    public function __construct(
        TransactionService $transactionService,
        MatchService $matchService,
        CommissionService $commissionService
    )
    {
...

        public function create(User $user, Match $match, MatchEventEnum $event, BetResultEnum $result, int $sum): Bet
    {
```

Phpstorm format multiline arguments methods `{` in next string, and this right for us.
But CS Fixer format it in same string, and no way to reconfigure at.
When we change `position_after_functions_and_oop_constructs` to `next` this behaiviour apply to all methods, but we need only for multiple-argiments-line.

Please add way to fix it.

**Comment by chekalsky** [comment] 2019-12-03 20:23
Have the same issue.

**Comment by tavy315** [comment] 2019-12-12 12:08
> Actually found this is part of the standard
Standard what?

**Comment by SpacePossum** [comment] 2019-12-18 13:47
@Mapteg34 can you provide a complete yet minimal PHP sample that shows the problem, I kind of struggle to reproduce what you describe

**Comment by Mapteg34** [comment] 2019-12-19 06:49
```
<?php

/**
 * Class Test4617Class
 * @see https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/4617
 */
class Test4617Class
{
    /**
     * @param int $a
     * @param int $b
     */
    public function test(
        int $a,
        int $b
    ) {
        echo $a + $b, PHP_EOL;
    }
}
```

I record a video (see attachment)

[2019-12-19 10-45-19.flv.zip](https://github.com/FriendsOfPHP/PHP-CS-Fixer/files/3982066/2019-12-19.10-45-19.flv.zip)

**Comment by SpacePossum** [comment] 2019-12-19 10:03
I think I understand now; you want support for this code style:

```php
<?php
class Foo
{
    public function test(
        int $a
    )
   {
        //
    }
}
```

which should be applied only for multi line signatures.

Currently we don't support that style, mainly because it is not part of standard like PSR nor is it used by a bigger PHP community. For us this is important as we like to promote standards and rely on the communities to help out here, so the more it is used the more we can expect support.

The change is done by the `braces` fixer which has too many responsibilities; https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/823

When that one is split up you might be able to disable a more dedicated rule. To be honest; I don't think the requested style is going to be support from a rule within this project. Therefore it might be better to accept another style, or create a custom rule and use that one.

**Comment by tavy315** [comment] 2019-12-19 16:51
I noticed that PSR-12 says "When the argument list is split across multiple lines, the closing parenthesis and opening brace MUST be placed together on their own line with one space between them.", so I guess you can choose to use PSR-12 code style.

Or make sure that "Preferences | Editor | Code Style | PHP | Wrapping and Braces | Function declaration parameters | Keep ')' and '{' on one line" is checked. This way PHPStorm will format your code exactly like PHP-CS-Fixer does it (using PSR-12).

**Comment by keradus** [comment] 2023-03-31 20:07
Hey! I'm closing this as no traffic around anymore. The idea could be valid, yet it didn't get any movement around.
If any of you see a value in it and are ready to implement it, please draft mini-RFC what you would like to achieve and how.

**Closed by keradus** 2023-03-31 20:07 UTC
Labels: kind/feature request
