### ISSUE TITLE
HeaderCommentFixer and NoExtraBlankLinesFixer taking multiple runs

### ISSUE THREAD

**Issue by dmvdbrugge** [PHP-CS-Fixer/PHP-CS-Fixer#3845] opened 2018-06-28 13:07 UTC
#### The PHP version you are using (`$ php -v`):
```
PHP 7.1.18 (cli) (built: May 25 2018 19:18:59) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.1.18, Copyright (c) 1999-2018, by Zend Technologies
```

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
`PHP CS Fixer 2.12.1 Long Journey by Fabien Potencier and Dariusz Ruminski`

#### The command you use to run PHP CS Fixer:
`vendor/bin/php-cs-fixer fix -v --using-cache=no processes/daemon_<redacted>.php`

#### The configuration file you are using, if any:
Basically the same as [dmvdbrugge/dynamic-components](https://github.com/dmvdbrugge/dynamic-components/blob/5dfba1d7ea9573b2f2d75468556c988019be541c/.php_cs.dist), except `explicit_string_variable`, `no_alternative_syntax`, and `no_unset_on_property`

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):
 * before running PHP CS Fixer (no changes):
```php
<?php
/*-----------------------------------------------------------------------
    Start				 : end 2009
    By					 : Colleague
    For					 : Company (c) 2009
    What it does			 : Daemon for <redacted>
-----------------------------------------------------------------------*/

// For local debug purpose:
//$_SERVER['SERVER_ADDR'] = '127.0.0.1';

define('SOME_CONST', 'value');
require_once(__DIR__. '/../vendor/autoload.php');
// More code follows
```

* First run:
```
1) processes/daemon_<redacted>.php (concat_space, include, phpdoc_summary,
align_multiline_comment, header_comment, multiline_comment_opening_closing,
no_alias_functions, no_blank_lines_after_phpdoc, blank_line_before_statement,
binary_operator_spaces)
```
```php
<?php


// For local debug purpose:
//$_SERVER['SERVER_ADDR'] = '127.0.0.1';

define('SOME_CONST', 'value');
require_once __DIR__ . '/../vendor/autoload.php';
// More code follows
```
Note the double newline that should've been made single

* Second run:
```
1) processes/daemon_<redacted>.php (header_comment, no_extra_blank_lines)
```
```php
<?php


//$_SERVER['SERVER_ADDR'] = '127.0.0.1';

define('SOME_CONST', 'value');
require_once __DIR__ . '/../vendor/autoload.php';
// More code follows
```
Still or again the double newline. (Priority issue between the two?)

* Third run:
```
1) processes/daemon_<redacted>.php (header_comment, no_extra_blank_lines)
```
```php
<?php


define('SOME_CONST', 'value');
require_once __DIR__ . '/../vendor/autoload.php';
// More code follows
```
So, it removed both the last comment, and one (or two?) of the newlines, but there's still a double newline.

* Fourth run:
No changes. But what about the double newline?

* Fifth run, try with `--rules=no_extra_blank_lines`
No changes. Hmm...

* Manually remove the second newline, sixth run with all rules again
No changes. Ok...

* What did I expect
I expected only the actual block to be removed, as `//` doesn't signal "header comment" to me, and then to not have a double newline, aka this:
```php
<?php

// For local debug purpose:
//$_SERVER['SERVER_ADDR'] = '127.0.0.1';

define('SOME_CONST', 'value');
require_once __DIR__ . '/../vendor/autoload.php';
// More code follows
```
However, if the `header_comment` rule does remove all the comments it finds, the expected outcome changes to this:
```php
<?php

define('SOME_CONST', 'value');
require_once __DIR__ . '/../vendor/autoload.php';
// More code follows
```
And all should be done in a single run.

**Comment by Wirone** [comment] 2023-04-02 13:30
I'm going to close this because issue mentions Fixer version which is not maintained anymore. Feel free to reproduce it on latest version (if problem still exists) and create new issue.

**Closed by Wirone** 2023-04-02 13:30 UTC
Labels: kind/enhancement
