### ISSUE TITLE
NoMultilineWhitespaceAroundDoubleArrowFixer should not apply to short closures

### ISSUE THREAD

**Issue by enumag** [PHP-CS-Fixer/PHP-CS-Fixer#6002] opened 2021-09-13 06:53 UTC
## Feature request

For arrays this fixer is a good thing. For short closures though it becomes problematic:

```php
return fn (LongClassName $firstParameterName, AnotherClassName $secondParameterName): ReturnType => $firstParameterName->someKindOfWayTooLongExpression($secondParameterName);
```

This line is way too long so I'd prefer to wrap it like this:

```php
return fn (LongClassName $firstParameterName, AnotherClassName $secondParameterName): ReturnType
    => $firstParameterName->someKindOfWayTooLongExpression($secondParameterName);
```

Which the fixer prevents.

**Comment by Wirone** [comment] 2023-07-01 16:11
Duplicate of #5908.

**Closed by Wirone** 2023-07-01 16:11 UTC
Labels: status/to verify, kind/feature request
