### ISSUE TITLE
`no_unneeded_control_parentheses` rule must do nothing when there is a comment inside

### ISSUE THREAD

**Issue by mvorisek** [PHP-CS-Fixer/PHP-CS-Fixer#6911] opened 2023-04-24 14:14 UTC
## Bug report

```diff
 $condMain = false;
 $locale = 'DE';
 $condIt = true;
 $condDe = false;
 
 if ($condMain
-    && (/* $locale === 'IT' || */ $condIt)
-    && (/* $locale === 'DE' || */ $condDe)
+    && /* $locale === 'IT' || */ $condIt
+    && /* $locale === 'DE' || */ $condDe
 ) {
     var_dump('wrong');
 }
 var_dump('ok');
```

Such transformation can change the meaning of the comment and must never be done.

repro (after comments are uncommented): https://3v4l.org/UclHL/rfc#vgit.master

### Runtime version

any

### Configuration file

`@PhpCsFixer` ruleset - see implied rule options here: https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/master/doc/rules/control_structure/no_unneeded_control_parentheses.rst#rule-sets

**Comment by kubawerlos** [comment] 2023-04-24 14:49
I cannot see any bug here, all that I see are examples not relevant to diffs.

I've made those similar to the claimed-to-be-breaking-code diffs - can you update the lines with `@todo` (and only those lines) in here:
```php
<?php
$useMin = true; // @todo
$rule = []; // @todo
$x = ', pro ' . $rule['text'] . ($useMin ? ' > ' : ' < ')
    . ($rule['num_range'][$useMin ? 'min' : 'max'])
    . ' ' . $rule['num_range']['unit'];
```
and here:
```php
<?php
$condA = true; // @todo
$condB = true; // @todo
$locale = 'IT'; // @todo
if ($condA
    && (/* $locale === 'IT' || */ $condB)
) {
    $x = true;
} else {
    $x = false;
}
```
the way that `no_unneeded_control_parentheses` will change the value of `$x`?

**Comment by mvorisek** [comment] 2023-04-24 15:52
@kubawerlos I apologise for the first testcase, I was wrong. I have readjusted the issue title/description.

**Comment by Wirone** [comment] 2023-04-24 16:39
In [3v4l](https://3v4l.org/UclHL/rfc#vgit.master) example there are no comments, but actual AND/OR combination.

```
var_dump($condMain && ($locale === 'IT' || $condIt) && ($locale === 'DE' || $condDe));
var_dump($condMain && $locale === 'IT' || $condIt && $locale === 'DE' || $condDe);
```

Of course it behave differently. But in example here you have commented left side of the `||` so it's not the code and logical condition anymore:

```
 $condMain = false;
 $locale = 'DE';
 $condIt = true;
 $condDe = false;
 
 if ($condMain
-    && (/* $locale === 'IT' || */ $condIt)
-    && (/* $locale === 'DE' || */ $condDe)
+    && /* $locale === 'IT' || */ $condIt
+    && /* $locale === 'DE' || */ $condDe
 ) {
     var_dump('wrong');
 }
 var_dump('ok');
```

From the PHP perspective it like you would write:

```php
if ($condMain && $condIt && $condDe) {
}
```

How is it a bug? Fixer does not know what's inside comment, as far as I know AST tree inside comment produces only string, not actual code tokens. Even if Fixer had proper code context from the comment, it's not its responsibility to treat comments as potential code. Your example shows bad practices and tool can't be responsible for people's actions _after_ fixes are applied. If someone uncomments such comments and change the logic, it's one's fault.

Sorry, but I'm going to close this one since there's nothing Fixer should support here.

**Closed by Wirone** 2023-04-24 16:39 UTC
Labels: kind/bug

**Comment by Wirone** [comment] 2023-04-24 17:00
With your approach this would be untouched too:

```php
 if ($condMain
    && (/* Foo */ $condIt)
    && (/* Bar */ $condDe)
 ) {
 }
```

which does not make sense because these parentheses _are_ useless. And since you don't want comments analyser how would you determine which comment is dangerous and which not? It's impossible. Keeping all useless parentheses just because they have comment inside is wrong IMHO.

PS. As a side note: it's not a bug, it's feature request.

**Comment by mvorisek** [comment] 2023-04-24 17:16
IMHO we do not need to remove the comments as long as we are not sure what is inside the comments and be defensive in the `no_unneeded_control_parentheses` rule. If comments are not wanted inside expr, it is a job for another rule, and if no comments are present, the proposed solution, will have no (negative/any) impact.

**Comment by kubawerlos** [comment] 2023-04-24 21:19
> IMHO we do not need to remove the comments

One can say "IMHO we do not need to keep the comments".

The fact is `no_unneeded_control_parentheses` removes them correctly and not breaking any code.

If you could predict the future and/or intention of an author then we can update the fixer to do that and based on that remove or not the parentheses. But since it's currently not the case let's keep current, perfectly fine behavior.
