### ISSUE TITLE
Array alignment has changed in recent versions

### ISSUE THREAD

**Issue by aowie1** [PHP-CS-Fixer/PHP-CS-Fixer#6731] opened 2022-12-29 01:22 UTC
I wasn't able to nail down which version this changed in.

In v3.8, this was the alignment:
```
$a = [
        'a'             => 'foo',
        'some long key' => [
            'nested a' => 'stuff',
            'b'        => 'other stuff',
        ],
        'shorty' => 'baz',
    ];
```

and now in v3.13.1
```
$a = [
        'a'             => 'foo',
        'some long key' => [
            'nested a' => 'stuff',
            'b'        => 'other stuff',
        ],
        'shorty'        => 'baz',
    ];
```

I would prefer the former alignment since a very large array, which might have long keys, will force the double arrow out to that length but depending on which portion of the array you're viewing, you may not see that long key and be confused why the spacing is so large.

So is this a bug or was it the original intention of 
```
'binary_operator_spaces' => [
  'operators' => [
     '=>' => 'align_single_space_minimal'
  ]
]
```

**Comment by julienfalque** [comment] 2022-12-29 16:54
Duplicate of #6716 (possibly fixed by #6724).

**Closed by julienfalque** 2022-12-29 16:54 UTC
