### ISSUE TITLE
Wrong indentation of arguments for multiline function calls

### ISSUE THREAD

**Issue by ghost** [PHP-CS-Fixer/PHP-CS-Fixer#4281] opened 2019-01-27 13:53 UTC
#### The PHP version you are using (`$ php -v`):
=> PHP 7.2.12 (cli) (built: Nov  9 2018 11:00:45) ( NTS )

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
=> PHP CS Fixer 2.14.0 Sunrise by Fabien Potencier and Dariusz Ruminski

#### The command you use to run PHP CS Fixer:
=> php vendor/bin/php-cs-fixer fix ./src

#### The configuration file you are using, if any:
No custom configuration.

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):
 * before running PHP CS Fixer (no changes):
```php
<?php

class C{
  public function __construct(){
    sprintf(
      '%s',
      'A',
      'B'
    );
  }
}
```

 * with unexpected changes applied when running PHP CS Fixer:
```php
<?php

class C
{
    public function __construct()
    {
        sprintf(
      '%s',
      'A',
      'B'
    ); // -> whoops?!
    }
}
```

 * with the changes you expected instead:
```php
<?php

class C
{
    public function __construct()
    {
        sprintf(
            '%s',
            'A',
            'B'
        );
    }
}
```

**Comment by dmvdbrugge** [comment] 2019-01-28 10:40
_I think_ this is a priority case where `BracesFixer` needs to run before `MethodArgumentSpace`, or `MethodArgumentSpace` needs to be(come) aware of indentation level and indentation configuration.

**Comment by simon-tma** [comment] 2019-03-06 06:30
I get a similar issue with just `indention_type` set. Reappling the fixer will keep decreasing the indent level until every line is indented at most once.

```
--- Original
+++ New
@@ @@
 <?php
 
 function foo() {
   if (mt_rand() % 2) {
-    return 1;
+  return 1;
   }
 
   return 100;
 }
```

Test file:
```
<?php

function foo() {
  if (mt_rand() % 2) {
    return 1;
  }

  return 100;
}
```

Test config:
```
<?php

return PhpCsFixer\Config::create()
  ->setIndent('  ')
  ->setRules(['indentation_type' => true]);
```

**Comment by asccc** [comment] 2019-03-18 10:08
Same behaviour in arrays

```php
$foo = [
  'bar' => [
    'baz',
    'qrz' => [
      1,
      2
    ]
  ]
];
```

After 1st fix:

```php
$foo = [
  'bar' => [
  'baz',
  'qrz' => [
    1,
    2
  ]
  ]
];
```

After 2nd fix:

```php
$foo = [
  'bar' => [
  'baz',
  'qrz' => [
  1,
  2
  ]
  ]
];
```
 Configuration:
```php
$finder = PhpCsFixer\Finder::create()
  ->exclude('vendor')
  ->notPath('*.phtml')
  ->in(__DIR__);

return PhpCsFixer\Config::create()
  ->setIndent('  ')
  ->setRules([
    'indentation_type' => true,
  ])
  ->setFinder($finder);
```

This only happens if indentation is user-defined (not 4 spaces).

**Comment by Raphy** [comment] 2020-09-30 18:03
I have the same issue as #4282 

The original code :
```
    public function __construct(
        UserPasswordEncoderInterface $userPasswordEncoder,
        AccessTokenManager $accessTokenManager,
        RefreshTokenManager $refreshTokenManager,
        AuthorizationCodeManager $authorizationCodeManager
    )
    {
        $this->userPasswordEncoder = $userPasswordEncoder;
        $this->accessTokenManager = $accessTokenManager;
        $this->refreshTokenManager = $refreshTokenManager;
        $this->authorizationCodeManager = $authorizationCodeManager;
    }
```

And PHP-CS-Fixer fix : 
```
    public function __construct(
        UserPasswordEncoderInterface $userPasswordEncoder,
        AccessTokenManager $accessTokenManager,
        RefreshTokenManager $refreshTokenManager,
        AuthorizationCodeManager $authorizationCodeManager
    ) {
        $this->userPasswordEncoder = $userPasswordEncoder;
        $this->accessTokenManager = $accessTokenManager;
        $this->refreshTokenManager = $refreshTokenManager;
        $this->authorizationCodeManager = $authorizationCodeManager;
    }
```

Do you have any workaround to bypass this ?
Our CI/CD is broken because of this :(

**Comment by Wirone** [comment] 2023-04-06 08:05
Thank you for taking your time to report this, but unfortunately I'm going to close it since it refers to Fixer's version (2.x) which is not maintained anymore. Feel free to reproduce it on a latest version (3.x) and create new issue if problem still exists 🙂.

**Closed by Wirone** 2023-04-06 08:05 UTC
Labels: kind/feature request
