### ISSUE TITLE
"braces" fixer mess up indend of last comment before closing curly brace

### ISSUE THREAD

**Issue by endelwar** [PHP-CS-Fixer/PHP-CS-Fixer#3638] opened 2018-03-27 14:47 UTC
Using "braces" on a if/else block removes the 4 spaces indent on last line of `if` block if it is a comment (`//` or `/*` is the same).

Removing the `else` block and rerunning php-cs-fixer indents correctly the code.

#### The PHP version you are using (`$ php -v`):
=> php -v
PHP 7.2.3 (cli) (built: Mar 21 2018 15:47:37) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.3, Copyright (c) 1999-2018, by Zend Technologies
    with blackfire v1.18.2~mac-x64-non_zts72, https://blackfire.io, by SensioLabs

#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
=> vendor/bin/php-cs-fixer -V
PHP CS Fixer 2.11.1 Grey Devil by Fabien Potencier and Dariusz Ruminski

#### The command you use to run PHP CS Fixer:
=> vendor/bin/php-cs-fixer fix

#### The configuration file you are using, if any:
```php
$config = PhpCsFixer\Config::create()
    ->setRiskyAllowed(true)
    ->setRules([
        'braces' => true,
    ])
    ->setFinder(
        PhpCsFixer\Finder::create()
            ->in(__DIR__)
    );

return $config;
```

#### If applicable, please provide minimum samples of PHP code (as plain text, not screenshots):
 * before running PHP CS Fixer (no changes):
```php
if (true) {
    echo 'hello';
    //hello comment
} else {
    echo 'else hello';
}
```

 * with unexpected changes applied when running PHP CS Fixer:
```php
if (true) {
    echo 'hello';
//hello comment
} else {
    echo 'else hello';
}
```

 * with the changes you expected instead:
```php

if (true) {
    echo 'hello';
    //hello comment
} else {
    echo 'else hello';
}
```

**Comment by SpacePossum** [comment] 2018-03-27 15:59
Hi and thanks for reporting,

I _think_ your issue is the same as https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/3490 so link to it anyway ;)

**Comment by endelwar** [comment] 2018-03-27 17:03
Indeed it's the same issue! I didn't searched on closed issue before posting, my fault :(

**Comment by SpacePossum** [comment] 2018-03-28 06:39
No worries @endelwar ! all good
Not sure if someone started on a configuration option for this. I'm going to tag this as `feature request` , although I'm aware some think this a bug, in the end it will result in the same fix ;)

**Comment by raveren** [comment] 2023-02-09 19:44
Not to mention this behavior is incompatible with PHPStorm, ugh :(

How can anyone look at this code and say "Yup, looks like it should"
![image](https://user-images.githubusercontent.com/364220/217920639-1326eaa4-f6aa-4f8b-b5e2-561bab20aeeb.png)

**Comment by Wirone** [comment] 2023-04-06 07:59
Thank you for taking your time to report this, but unfortunately I'm going to close it since it refers to Fixer's version (2.x) which is not maintained anymore. Feel free to reproduce it on a latest version (3.x) and create new issue if problem still exists 🙂.

**Closed by Wirone** 2023-04-06 07:59 UTC
Labels: kind/feature request, braces related
