### ISSUE TITLE
no_unused_imports does not remove some unused imports

### ISSUE THREAD

**Issue by gnutix** [PHP-CS-Fixer/PHP-CS-Fixer#7908] opened 2024-03-24 10:43 UTC
### Description

Some unused imports are not removed by `no_unused_imports` fixer.

I've seen this issue happen randomly for a long time now on a private project I work on, but could never manage to produce a small code sample to share here, nor understand why it fails to do so. Usually, I discover that some unused statement was not removed either because PHPStorm highlights it, or Rector fixes it.

And then, the issue happened again while contributing on `brick/date-time`, which is an open source library. So I've created a small reproducer repository : https://github.com/gnutix/php-cs-fixer-no-unused-import-fixer-reproducer/

### Runtime version

> PHP CS Fixer 3.52.1 15 Keys

### Used command

```bash
vendor/bin/php-cs-fixer -vvv fix
```

### Configuration file

```php
<?php

return (new PhpCsFixer\Config())
    ->setRules(['no_unused_imports' => true])
    ->setFinder((new PhpCsFixer\Finder())->in(__DIR__ . '/tests'));
```

### Code snippet that reproduces the problem

cf. [AbstractTestCase.php](https://github.com/gnutix/php-cs-fixer-no-unused-import-fixer-reproducer/blob/master/tests/AbstractTestCase.php)

**Comment by Wirone** [comment] 2024-03-24 13:34
I believe it's a duplicate of #2814 - `no_unused_imports` just uses naive lookup and doesn't remove imports if it finds any usage of short name. In your case it's most probably [here](https://github.com/gnutix/php-cs-fixer-no-unused-import-fixer-reproducer/blob/master/tests/AbstractTestCase.php#L58), basically any occurrence of `Month` (case-insensitive) will prevent `use Brick\DateTime\Month;` from being removed.

When I changed all the `month` usages in the PHPDoc, fixer removes the import:

<img width="732" alt="image" src="https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/assets/600668/50fd8b4a-eb44-41ba-b479-36e42b032235">

**Closed by Wirone** 2024-03-24 13:34 UTC
Labels: kind/bug

**Comment by BenMorel** [comment] 2024-03-25 21:22
Nice catch, @Wirone. I was recently wondering what black magic PHP-CS-Fixer used to not remove imports used in commented out code; turns out it's not that magic! :slightly_smiling_face:
